# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fastest"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "simple"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

