hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "4cf30e65cc64f5df736a38740e30730aba2794643e73446a786cc15535a72f1c"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "a8d750cc4c3a9723282fcfeb8b882acc11ab47b3340a048d7406cf376de53898"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "859e34b70c9430605631ec5fdb9d43ead8318b24a8baa9e1cb26c5d5b19361ef"

[[files]]
file = "config/yosbr/options.txt"
hash = "e840840d9d85a5722e3a9fdce284048916259088a074513b9fd116ff08e4f585"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "eefa86fa9a8df6eda5d39d3bbbf53138a44df71a01a24262c27584badea97d79"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "b04558e3aa16f01cb56278cbb0ae1a2a7c65b5288ee056865a07b2764a850f65"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "e4b230e3eccc42c8b650eebb49945f4d9bde3746e5de2e969a89c18e8c4ef85f"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "97a19031a10809c206b89c366bf1e802e4f2d39e9df798c3c627bf0d63448447"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "41397f8ebb5a1137f559761cee66b18a85c7289e89ac84a738140d651eecccdd"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "5d4ebf1c83e189cc4b67a579f89fc473aded16d6487683dabafff261a944190f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "f8120fc5db92a8923a02424e0b9a32e72ca1606ef01eda7661dff7aafdba6b44"

[[files]]
file = "mods/antighost.pw.toml"
hash = "b023edfcaca9f400d9afed65ec077cc98a35943fedb4392542f87fbf8613e839"
metafile = true

[[files]]
file = "mods/betterbeds.pw.toml"
hash = "e32d39231226295367d30ab01e9a542b1ae3644dc2b38e05f005c37cf10d0bce"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "3c166fe5bb9777c16f216d1858ddfa04fea30076e100ddcbca28e8d026e225fe"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "64b46649facff7bb1b20ed8bb93f7ece4f8e397e5a18f670aba5b741fa16973f"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "b6fdebc38bf3e988d5386bd781394545a06456e0f8fd238f2a380023de2165a7"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "2d15ca4433c2f72c9993abeb452efc16ec5a1b70be1fef99e998d6e9aa4dc2bd"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "6ad1232c234e042f0abdd2a02878a34c87ed151bac5095a241fec709716b275f"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "7c5caeb7e0652bdaa73614281535d015fb45ef303edb607f4dc4baa4c493bbac"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "6719f0a25609762408233f4826be8872e0508c9c1ebe16ba9a631a3f89ef3a05"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "9e367a3b4407bf1941a5b7cc7041545d1a243e30440262c9d7cd745e1b0b8535"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "ca199c56727323ca124d5c4c4d6be14748d6602ca94e17daca9d7046f80170e4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9d43225a578cd36fbaf754c73a8ba77d8583b1c34bdcb9fdd8199b6a807bdf94"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "4fcc158eecc17087c671edf24a5037baf4edbdcf3bbf040910f2901b09daa8cf"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "d8a626fcad947cc8ec16f59b03dda8c755a36142ca7b73c31dc9c6fc8a096e65"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "333cbe6d99393791a6ec11774f496131ec9fa8f8becdc9f5fa0ea79dd6247ebc"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "6f5d26e9943c5837bc2094d0a0dca55e3ec6251d9a1efd867e0bc5d1f388cb18"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "6c488254b38b239ed76c5315bd8d733e789c328aa89e25d7c68d3466a6a88d51"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "cabc105f32fa00d7988e1c8ebe1d9d2ee95ada93ffcfef59c33251ed2c602714"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "1b242182d81d92734769025a6e13805764213dfd1f676b1e4745e80c5077691f"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "c895b10d9f5fda7098a2ca162639a850e9dfaeec43ff24fe09830f7491acc7c4"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "c44a30e6eadd17f75b313f1bf26011c58b4c60af96a2cfe1f042e3510adec127"
metafile = true

[[files]]
file = "mods/holdthatchunk.pw.toml"
hash = "4c4a2b3c782e78cd1a47aa6b078ec3f4fd9bd44808eb8d6c98fbe79e8453053e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "a58b5d45eb34a87798c5746f6027b74f2ce9d8442ae0cf487e803532786f4d22"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "c0b59e6a01005aa93d354c58e02548b047f685f03396b67529753a600426d28f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "1f617d264ae48e96ae9269400a16dc93fa011a89c6e6ec17189ae5121a217df9"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "122d3d07c920c2154e1c041f3acd17c4b4f1c2556b57418adebe2b46aaaef1ca"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b6de5927635eec4e625581fd4457ff16bb023068ed2d14622c0e708f88794ead"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "a8c3a598ab5619672bd3516198953e6e19efcafe00533a67e5119d612bd62ac9"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "13ca48713a50af57796f5252317d156fcfbde3325a021187410ff85db7e0f182"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "a20d5a58944f864486b032842c5b440ab848e6c31c9cdfb2dfe6569d78e30462"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "24e905f67dfa82bbc818cd97e9cdf8e3652ec7db77b761c9c2174aa89ece8419"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6ab383f3071837739e78e36eb7d476b01fafbd6a42a184f03d1c7454a3ca5c12"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "d3a760f6ae8911ab42b674b554ac624e6e78969e332bde962fa6555b261fca7d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "aa662f7b6251a81d47c2e2131bad682d7f514ba5aaa720129bb5c53cf80f8925"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "7621d6f81c3b2be23a5ff49a520299a26596cf454b8876429f51a50ccf62d71d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2c4c14cf325fa22c0786e872ee0b36646790706da68bdfd32e33c28805be3e8a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "7a9517fd58e106598c4f52881986de3339197eec01d85dd11d6c74dd7257b658"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "736bb573b96ab40f1afaa6e0353f03b509bc164285821fe8a16e99d9ccce8dbf"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "b3db869e78e3e49f8ef4d95e02445bf38566e46f52943f049d710b1d6719e821"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "e13d84282eadfb56b43feca620ab4a133b36cd7d20161567817b9a1de8a2dc98"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "abf68f34e70bb2a07e77032a3db21f85ab6d145000c521f8bd2684bfb905a64b"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "1185e63e7327860f0e1f0a1e3c4f96bd83dfd3ac524fd2ac8e93b360bcb18e9c"
metafile = true
