hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/entity_texture_features.json"
hash = "cef51db1150ae1f30f504c8932c274ba174441d4fa177cda048b407da59d5865"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "8d7ec7a9d250a6220b5d134864e6143d3475dc12b1198f78d52d293a40b899a4"

[[files]]
file = "config/immediatelyfast.json"
hash = "f0fa91c42d9a753f8f2773f193864fe248fe1a3527189d1490a0e0094bcd7049"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "9cf446e340fd06256a0f02df38afa751afae6b857e7b8161690376df8818ddb2"

[[files]]
file = "config/yosbr/options.txt"
hash = "3726397a0653de32af2af47d736d8d13b05b55f30c059cc9656757979a6c8b25"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "ba199dc4caf8bd40d40e319e0a28ee21553a65006219f989f3930331fa3e6295"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "d5cc0bf222ff1fa9fcc1293a443a3ea340710c68db96261fbc8d0f42d8aec491"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "30bf7c21557b8e83356ef043c044d76478b531013a290c97443740b2c7a1b73d"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "3c5317882a50941e2384b9739ec3aa688f297105691c9d8d577936ad29c1d575"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "dacff858c9d3d3d96a4b6b902133d0691e320e21a2f57adc6bb6cb9875763582"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "b2ff60a305956fb2a381c6c61d960d2b220d83d9c7737e2ac4ab34a1f604af56"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "41397f8ebb5a1137f559761cee66b18a85c7289e89ac84a738140d651eecccdd"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "89a7af00ca38519e83575601dece118e5ed6da33a3d4219e52ea3b04d5dbe45b"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "3bc3e90be75188a9798eec3a4239a2b53f6be990e620c32594a17844645c5fbb"

[[files]]
file = "mods/animatica.pw.toml"
hash = "65df17c363eed6e37080d134f548a22aa0b14a9fecf94d5045d5b451bdeb88f4"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "3c166fe5bb9777c16f216d1858ddfa04fea30076e100ddcbca28e8d026e225fe"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "5a556c11e63e10346fc83a280dfeb6835c58baf7b15bf763b43e6d43e33a8e96"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "08273307f0b1df02aabffcea657747e6308ca00d301c6c0f4cce42818a8f53f5"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "2d15ca4433c2f72c9993abeb452efc16ec5a1b70be1fef99e998d6e9aa4dc2bd"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1ff600b065c61c459ec4601764f922c7465fc58cec468e5ebffef392254b6cbd"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2481588ce600e2a77400f48b193a44db3d2dee7a3d571db332ea70c1cd57375a"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "14c8a6fcb06528d34e9503aab06c6574c39cbf59106867eb738a0d38b5972ac5"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "458653fc6189fa2cd4b624e52c9a37a028a5e1f5b98df40e2e3321578b3a5e3c"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "cf288276dffdb3d163b7f1420756382b4ef8cbb1bfbda9f1e4e685f2616a8736"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "83508b385b24abc42539a53f6a4412d4b46aaedcf0fd0f188358392919e80127"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "76146f84f2567f4275ba2ecbf43caf3c0740aa87c605d3f2cd489d3d7597ffd2"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "676d42752de490a571af628b9a353885bcc30dcdb133d1fe32be4bb78ac4a01a"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "109ef9ca28a2ad132ff77e4334715335d6bbcc25fe2db8b9bfc5eef9603eb2b5"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "1fe9162e26ca731547b774aadc3a4c752e58246bc1e6f2d27dcb4d01a3d23739"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "058940feb6c2fc7605562fce3e771544bad228a5dbee972f77165c7ed3b01360"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "54db7e2b74a2bf050e69e27db45c6a4c434da51398fcbfaa1db5b3019c651061"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "fc2775479e9d7946db86d4eacec894b9e45fb93bbf62bb96401b6b45d29f11ae"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "a660173f854ce29f69ec9ae483e5f68d90a8897f1cb592f0b0ac43b9664e745f"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "10cb7ae191440b474e74c7c9fb263c4745c4247dfec3cc5cb04c7b5c6c06ee58"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "b7e46c064d700c2cc83158064ea77becc48afb4696a7c377b570ad963b7463ed"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "31e3db7c895d5a4bcbaf68c196036b6b345264ab18ed74437a46819345ea4e01"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "eb9782953c41732e9f707c7386c70f6c0bfb9191cef4707a1ad157597ef08620"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "74302037e7ad7670973671237dbdea6dab5d2272500e073f9af641fe3878cb29"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3bb1ce9cdeb48eb1023295b212b8f9907214e5fd25bf005adc2086e1de7eec30"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "152d49bfea89dd0854f7fe5983a894375f2a3f3fa84646cda2da79c64cea6700"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "c370b6ac296cd050db5c9f5e65bd1ef8ffee1d575ac8462042df9e6a84e7d9ed"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2e0fd691be28b97a84a49bb490a39aa6ac5068f012202e43e0d2ff26c6125445"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "a8c3a598ab5619672bd3516198953e6e19efcafe00533a67e5119d612bd62ac9"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "38f94a9f4aaff8aa39f36b963c15c8e740e55cbce6d5d43681a62c073fdb1c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "0c819d82356d9914c761a88e47aed1dec5376cf1720bf517964967b9d5390a92"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "72c14f80c01a91085225b316e0e93ac39036d75c626ef69f33d9492695c23ffb"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "2e0d757e7237216942c72bf8dbb8805ead00be6b9ab59b7933729101b171fe4a"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "d9c8353976b3543ac685f84582049df9a589bcddb85aa116ff86b446bbd64629"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9abe7d821b510b4d5eeeb7b640582a02ab35afe58a64f4c6b56e73d826ffdae6"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "da1a36a95cf65ff6b733b585e476d2a0ac2b874f1722e0a6ec01e907247aa15e"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "83bd85bd70d961f783039936a1c5c24ae6d5e91f28c3404686f555553ae0e0f7"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "71a2f6da2b35a4906ea3dafcb60ee39926ed2ebe6e6018cf024892e654dbfb36"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "10c00327cd05085ac76c5b8112b90659f79761edaac8b49ccbb3207f2309d06b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d4dc3f4e3773eda6c6f2d67115adebc602a8a082c15a7399ad54ded71ff335de"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "2ba79840f134759faf13090f58cad2768a23b72d29318233d97dee644286fc77"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "89833ed52e9ac2859a23180b4dbab392a76532053255870535fc23508430eb2a"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "10f38e5987b54c59e5d5d5045a8b48d108a297ce29fc3b8d6de1564b2e3e70bc"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "933445520a24c0100a1567a95d8b8d7b74fb197b496bfc9c09cea1b4625b6e18"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "29e217821eaad5d505bd20ffce827d911ec7313ad7962f8e86e71f9a47ac5dfd"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "6ea63283562414fe054c422a99eb6dcc96894e9e7794c229ff477e218de17fbe"
metafile = true
