hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "5acf512802d5341bb9d879cc998299cdafbcfaf884a25511ede83b75bba17def"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "cb3608fec5b5dd266874687af72073e0a6aeaac839e681305dbac6c94f847e86"

[[files]]
file = "config/modmenu.json"
hash = "66b6aa43c888678b69e1639cc1f253dff65dde38f55cbbab70f7235573a85385"

[[files]]
file = "config/yosbr/options.txt"
hash = "0b5cd70ec834c5373ec7a92e747eb7669d5be9cab7c341d2e556c1217050173f"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "ba199dc4caf8bd40d40e319e0a28ee21553a65006219f989f3930331fa3e6295"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "d5cc0bf222ff1fa9fcc1293a443a3ea340710c68db96261fbc8d0f42d8aec491"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "30bf7c21557b8e83356ef043c044d76478b531013a290c97443740b2c7a1b73d"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "cef51db1150ae1f30f504c8932c274ba174441d4fa177cda048b407da59d5865"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "f0fa91c42d9a753f8f2773f193864fe248fe1a3527189d1490a0e0094bcd7049"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "3c5317882a50941e2384b9739ec3aa688f297105691c9d8d577936ad29c1d575"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "b2ff60a305956fb2a381c6c61d960d2b220d83d9c7737e2ac4ab34a1f604af56"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "41397f8ebb5a1137f559761cee66b18a85c7289e89ac84a738140d651eecccdd"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "89a7af00ca38519e83575601dece118e5ed6da33a3d4219e52ea3b04d5dbe45b"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "5cc43f6eda17bc068c4d0e8657e3cb1f4e9adbc858c0d09dda139ca9f6034670"

[[files]]
file = "mods/animatica.pw.toml"
hash = "65df17c363eed6e37080d134f548a22aa0b14a9fecf94d5045d5b451bdeb88f4"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "3c166fe5bb9777c16f216d1858ddfa04fea30076e100ddcbca28e8d026e225fe"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "5a556c11e63e10346fc83a280dfeb6835c58baf7b15bf763b43e6d43e33a8e96"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "08273307f0b1df02aabffcea657747e6308ca00d301c6c0f4cce42818a8f53f5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b705c29727a077b428b8ccca60b138ec29416d3bc8c66759cdcea338da830777"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2481588ce600e2a77400f48b193a44db3d2dee7a3d571db332ea70c1cd57375a"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "f0e0297e071b8227464e618d5b944bf6d2dd2643e841e643c33d28c0d5501677"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "412e02058f673d4548528f9cf075686313f1a0d520b1314a9f235e5c5c2d26aa"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "c01246e5aecb2198cdad019aecd19a88575fb7956adc4277dda2740dfaefea83"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "83508b385b24abc42539a53f6a4412d4b46aaedcf0fd0f188358392919e80127"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "76146f84f2567f4275ba2ecbf43caf3c0740aa87c605d3f2cd489d3d7597ffd2"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "528c05a81083b3b1760154863f02fbb5a58b5999e94242592f6684439dc3b157"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "51cbafd397e6d907f25effa59199e84ee6f4319b37e8d3151cf5ccd31c11b279"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "f8000c743650484042abe5064e135545c272a78ce5236b704b43f195593a46cb"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "a936ffd4606e1990368c56bef026760c3508a862ee65252dd6ef06d8fbecedbf"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "5fe18fac8fa96339268e15f14721c308e076327d68b43bd1d458a11563e589cb"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "fc2775479e9d7946db86d4eacec894b9e45fb93bbf62bb96401b6b45d29f11ae"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "9320866236b43f1a6610e0656a504ab5fc45df2b5bf0b42df5cbfbac2e9f221e"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "638295e4eb1954f9df3f79121df3a240b2c63f1ba393561737f626e98f1a27e4"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "31e3db7c895d5a4bcbaf68c196036b6b345264ab18ed74437a46819345ea4e01"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7061c7625deeee2375345d8cb19332c5a3d029a58fe499a99ff54b9d6c44b988"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e058243c0836aa4d3183015022f03919754586001d0b75cfe923b8284df4218c"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "915313289a88246b41181c8823a5b3385caf3843f045d3598602de13f595b41a"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "a64acfa3725ac6037030178f28c263fd248e55e2ef4da1980e0a760bfaecb477"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0006f3c5bf832bfb1473d97a1b295df655ce1d2659f918203a4ef96950a3699d"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "a8c3a598ab5619672bd3516198953e6e19efcafe00533a67e5119d612bd62ac9"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "38f94a9f4aaff8aa39f36b963c15c8e740e55cbce6d5d43681a62c073fdb1c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a32bf0d290f5261cb418bf7275e32513f1123eb129c3feb23c7b830de54a6fa6"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cf7a3a57ddc99413d33a81b8cbff1fa3cf8761a45652e5b3a61a6ee1a1069e9"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "2e0d757e7237216942c72bf8dbb8805ead00be6b9ab59b7933729101b171fe4a"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "ef584100cc02316c05f8ec91628e5b244e08b806a13e869c7f41f115f3a8a034"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "96ae4a6d53223d3f6b8fabf1d572c7231fa646fc9bc20a6c6b75673d351f542e"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "86c8e8a437965b4da10430e4629086ba9d6fcb7608d56de46fc858ecb4b75c8b"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "c8e63d0b1770e8e36bee5ae3172693113b56ead0095ec101ed8562c5cf7066ad"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "71a2f6da2b35a4906ea3dafcb60ee39926ed2ebe6e6018cf024892e654dbfb36"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "10c00327cd05085ac76c5b8112b90659f79761edaac8b49ccbb3207f2309d06b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d4dc3f4e3773eda6c6f2d67115adebc602a8a082c15a7399ad54ded71ff335de"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "637c14fb70aadb1b1717e15d0de482e2728b9e48630a043685ae46984a735cb0"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "0035ebf5c3ba72a86aff250e50e344b2810754bc4b5b06f00e5f4726d2a6abb5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "10f38e5987b54c59e5d5d5045a8b48d108a297ce29fc3b8d6de1564b2e3e70bc"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "5c7fc82192e5c85a0613b3262afe9a3d1c333202ce6f4c10b22b1d64ee35327c"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "29e217821eaad5d505bd20ffce827d911ec7313ad7962f8e86e71f9a47ac5dfd"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "e998521eefb84ac72743826ad9d3e82dadc7c75e3b44a7ee3443b40d286bc2b5"
metafile = true
