hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "b2daacd720fd4470a4eda7e6f980cea6f2dbc0100bc512942b4b584a2c0f7813"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "78c1ddaca3ecd299f46837f58730195ca905f6cdded8ab2d316008e407e67993"

[[files]]
file = "config/yosbr/options.txt"
hash = "071148fed751e319de41a6a614ca0bd273c3b2e92a7079921641a172d48ae187"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "ba199dc4caf8bd40d40e319e0a28ee21553a65006219f989f3930331fa3e6295"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "30bf7c21557b8e83356ef043c044d76478b531013a290c97443740b2c7a1b73d"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "cef51db1150ae1f30f504c8932c274ba174441d4fa177cda048b407da59d5865"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "f0fa91c42d9a753f8f2773f193864fe248fe1a3527189d1490a0e0094bcd7049"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "3c5317882a50941e2384b9739ec3aa688f297105691c9d8d577936ad29c1d575"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "dacff858c9d3d3d96a4b6b902133d0691e320e21a2f57adc6bb6cb9875763582"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "41397f8ebb5a1137f559761cee66b18a85c7289e89ac84a738140d651eecccdd"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "ade080447491d2a630c65b7343df636833f8283fe5af9db74b51c4e122bf0550"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "9e222692bd038587c1d128e995645f11182c18b2d143dc3639241db126174ae5"

[[files]]
file = "mods/animatica.pw.toml"
hash = "65df17c363eed6e37080d134f548a22aa0b14a9fecf94d5045d5b451bdeb88f4"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "3c166fe5bb9777c16f216d1858ddfa04fea30076e100ddcbca28e8d026e225fe"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "08273307f0b1df02aabffcea657747e6308ca00d301c6c0f4cce42818a8f53f5"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "44661e2e5601686cc65f52eee1f36150ba3e6cf2d8f42bb00761c48cebceb451"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b705c29727a077b428b8ccca60b138ec29416d3bc8c66759cdcea338da830777"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2481588ce600e2a77400f48b193a44db3d2dee7a3d571db332ea70c1cd57375a"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "eed430c64109310fa59cea091c8a42e14ef8b7c32dfa75a4c749c8046208ae1e"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a0426ebbc7ddbe1bd99aea015f713913771e0701ad292359371422fbb73a6f66"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "412e02058f673d4548528f9cf075686313f1a0d520b1314a9f235e5c5c2d26aa"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "eddad0af34215a88d738dd76dea4f2e47769a2f5de874ad7e71951cf18ac9593"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "83508b385b24abc42539a53f6a4412d4b46aaedcf0fd0f188358392919e80127"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "76146f84f2567f4275ba2ecbf43caf3c0740aa87c605d3f2cd489d3d7597ffd2"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "13d2bf498c5078d093be5561c8cc9919c5e018a1574b06ab2a6717156bb1f243"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "74efa97f0f55e252635966ab08c9ae6d20acb2dbb54754d8dd25fdc04c85af59"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "e4ed99791bd910c36ebe63eb0cd1d123f0429b4d2afacfc275c72f0d801e7759"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8ccaa7671f1f5f059dffe024189207915ea6a808a7ae54450361beaa87538e7d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "731ca414932a8a08904a9719e4b9b0e6504b05772a158746b38407c2476fd6e1"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "fc2775479e9d7946db86d4eacec894b9e45fb93bbf62bb96401b6b45d29f11ae"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "9320866236b43f1a6610e0656a504ab5fc45df2b5bf0b42df5cbfbac2e9f221e"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "6ff05404cca11475e2e4b436b092a61cef75e36af38ee9931c009dcc8734e77a"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "638295e4eb1954f9df3f79121df3a240b2c63f1ba393561737f626e98f1a27e4"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "31e3db7c895d5a4bcbaf68c196036b6b345264ab18ed74437a46819345ea4e01"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "08131ecfae19b5191f2de4fcbb1876adc85f4f170ab9bc79d9d323560bd8319e"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "fc34f10a6ed5a5e2eef2d290b651622939feaf00b5e3d67d3085c1f547181dff"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "2bd94d1d142a96594c05096798ad98774d0e52012ceccfa78bafc7622a9ccb0c"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "bad70b56b4d0112871be034ff4dad2303b1810bdd61a75894af73b7ba25250da"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "a64acfa3725ac6037030178f28c263fd248e55e2ef4da1980e0a760bfaecb477"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0006f3c5bf832bfb1473d97a1b295df655ce1d2659f918203a4ef96950a3699d"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "a8c3a598ab5619672bd3516198953e6e19efcafe00533a67e5119d612bd62ac9"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/moddetectionpreventer.pw.toml"
hash = "8a4d1fff0a68e4260fffd2e1d9609df508755d7c6c097bb510e1108ce8ee2094"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "38f94a9f4aaff8aa39f36b963c15c8e740e55cbce6d5d43681a62c073fdb1c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "3ac8a1067b5cb46adae1f4acf6fb8f7b417a64212c04c3c36396512d2cebdd67"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cf7a3a57ddc99413d33a81b8cbff1fa3cf8761a45652e5b3a61a6ee1a1069e9"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "67cecae7c6a9e93fa2042ca4cb59c8376f3dcf4c4dd3d1991d2112f949c57b8e"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "97497db58a0185fd5ab43e82b692a1434d9c7a7b6ce9337ea6577437664c65b3"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "ef584100cc02316c05f8ec91628e5b244e08b806a13e869c7f41f115f3a8a034"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "96ae4a6d53223d3f6b8fabf1d572c7231fa646fc9bc20a6c6b75673d351f542e"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "86c8e8a437965b4da10430e4629086ba9d6fcb7608d56de46fc858ecb4b75c8b"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "c8e63d0b1770e8e36bee5ae3172693113b56ead0095ec101ed8562c5cf7066ad"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c4e1654765948dba7415d2a9962e2b6f81dc53684e8ec6d90ddf2e2746b79072"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "89190fedce5c041b60040a05f4c1cb3781a74bd871a602a438cdb7c24fa289a6"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "99f4867fa2fe5e24fb0b8cb618c2b6f9446f9caa054201fd74c166bf4b58ae57"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "444ed719e36bcb706540ebeebbb59cef08ce24ee252f22a1f1ce593ee9ae611c"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "649f7a94077ee871457552258a226c022559ffd9a1dabf6bddba58508be380b3"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fc17aaf440b65f3c4ab3d97c5b03aa0963248b4ab6c642b0daf3a27180ecb1c5"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "953083e19d28ce384a4fe93b3951a1eb413dd2ea08999abbd9a05e4f2ee34369"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "29e217821eaad5d505bd20ffce827d911ec7313ad7962f8e86e71f9a47ac5dfd"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "821c0f8d9942038ce144ed5c7591280f830ffdafc61a16391c51cdaac2148b95"
metafile = true
