hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "68ad55a8421814e6bd802b664244e40540a37eaf3ee8aded87fea53520d25d38"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "1403e32b3b825b88619ba552f18f5d971ef869bd48391c8462af8b4f06238103"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "cbe4aff8f01718b0715fe897387a3bcc0e2d7c5bde6c40530abf0334bdcb1dd1"

[[files]]
file = "config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/yosbr/options.txt"
hash = "8417a8629d8fb25f7de12a971f55c1b14024f834864110e51f36c0402aed1c35"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "7de3087b5a435f770ed45b1b73ac9b37f3d36ab2fd71a1404d7a49e299738821"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "1656c1ce6af02cfb451541c7d5c938c51cc9e7aee962aee526c46f4be40cada3"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "547ab8638d23a570798766eda715653914d4fd34fd60317dbfeb62a3c51ba56f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "4d945a5abd8801037b2f13352459054152d0a6b9cde735619103aa6a41a72f45"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "707e9af170cd9c9282d25bfb5f1a337039348636183564cfa1a86ebde52f48df"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "fc6f57352dd11f3fc8aab4e2dd6d4f22d7182da45975c4b49aba1d2a03b5fa48"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "03586e60a57ea47f8c0f67e6ae8e74c411a1e3787979f593530e9c8cb9f2a2ca"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "181b6bda59e65cadc29604b2053955e9fd8299939ccc4604309e4ac97f2659ac"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "a848857985e7dfd249d3a7eb32a62e04b60edfb3d57a11fa8a49703065ef3e0a"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "a26a337fce738a7bcb616ad11865b27076b615449516d982353f71d4e94297f7"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "de041e2c7a3a94cebdef9e22bebb7b81c1340762423209bb9a3fbc4934a9da1d"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "181e51852d990e383707a23c415ab51a9bc5925298c45b6185aad23ba3956d6d"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "6f2fc55eaefc6cf2ebb84337e494ec849ca37f91125f36a8532c7beafb956b35"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "ee1b4f6aa31f789dc845fa936be733bccf56714d90782ba574c8968cb89604d9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "bf395ee2b548aa4e21df962ade82a1f97fa6ad487e904334715a6f9b2a163e66"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "716ae4fd4d1d58db3b4b7a9dc2fb0d0df6ecf9c913e04869812a6a5d9a1d90bb"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "5327a51301b2007611c06a415db6b0fc87a8d65bcea31a8f723ae1e2b7b54641"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c7eccad65192d2a53d94454f187551b10cf8f6b07e17b48f4850cb31efe3a1c6"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "1bf1172a83d261202c4fb902bca2dc7997905f7a6a8009aa9fb23baa902473c8"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "3b3d6b2c0a9256dab61c5e084b3a89d1f946cac9c2da8601dbc184d82053584c"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "f83b09bffc8ac73221dc3222cc1e7d02cbfcd67f675ae03df0970558e2408d74"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f2118fd73ca56893fea2e5ed35ae8592562481d1875bc65204db1de54f748fed"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "b0fc97f78eb93c52048bb96a5c1c062b8e15358538d5af860e256117559b227c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c059c82e3e081179d153c160abd48364209dfa988207641ed9ce1f617106e844"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "0e14eaf8104875ea374368fe472912edad55a61af871c7af4e9ee4e69fcd42f1"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "e6c247070d3eadd977416e63d0200bf108e80ddace67f2e2012d88be54711b21"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "3bf54134dbf492b27b52b95cc994bfe0e3ec089a884ea1fdad0ee4cc33cf28e3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "cb7abda638c96f6b259fafe92c4ee94e4ba08126216adbfc646209147d6c5092"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "0e0c461da2cb8a1dabdf2b0efd2bf754ba96229cfaec364291dce5ba6499c47f"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "8482b7bcca9084e2f745367c1936641454acdd48dedc4223fcc55c22f89d5365"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "eb586c82b82374cbae08d6cbb80a947834020159b4d06256cce2095a832b5636"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3a198a385c9648a82374c2aa64898567fd028c5763fe1b1bce0a1f47d05c7269"
metafile = true

[[files]]
file = "mods/itemmodelfix.pw.toml"
hash = "8b7d66d060cd640af8df7bac02529d4d0773c24d3a83399219942df1c41f44c5"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "3af75e77b79fb1135b043fe8cd7c8653af582088b4edf716439d2c2454abef81"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "5b8154c5ef8ceac56c428a56fd8d1161a2aa278965c0c2966d77fd4c0fa4398d"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "22a0de25b7483bfcf7ba1484e563b53f93cb13ca0a1cb5932ac8ebf537bd4fcd"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "caf5cf800e403f44a64813bf8f4263dd9743983d66a5fabb9bc03d4560996394"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e5585228feab4b9bd84a84282d6b49ba3cc0ac0a1ab4e5b3b6e06e5f07d0f754"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bf619ec7dae9e2dcd694424a7c702c7fa1f549c3589f9ea0f4ef4d40d9041c2a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "a14b732551a1c7ab36adb5adbd178a9a87c75ffb854e476845ea9226bd0c932e"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "46b93eb3b7c661bf0aa59bb713cdc32a88f7f9960e4f20e2a120eeb76c1bf583"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "4d7792023b4cdd7ba399ddf95bbb3af9c3b69557ccfd7177a9aa19b07495e5b6"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6737e21b85c1e0cfd12da615de535fb7b4d11eb4f79b4ef092f3c859b3cffe51"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "bbbba894f37c75d3f7911ab2bf4bd8feedd4ee6bb92060eb03ffc378a38c07b3"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "cbc992bd5c0a572dd4712f8eeef4fedd531cf4a1642876ab579039488dabfe8f"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "36a7721dde240a58c154bc34c59008983fe747917ae68ac798ba44774ae73837"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "782c6072a2cab1513a196c8fe1d1cd4bbf86b408a569937b4a811bfab6a61cdc"
metafile = true

[[files]]
file = "mods/smoothboot.pw.toml"
hash = "ee3d980387c796b4342db65d9769dd21222bf4b7250f4a380518a611291cfeea"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "61f910b3505681cf956b5e584d374107417844ec9052f0a3add29b94d2c6459f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "daadcc5007f5f3ede01e59f97ae566243840fa38f0e5df4fc455260ea133b3a0"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7c42bb0fe982cf5004bfcb62690e9b433890ebd76ea94611fd91c68b00f386fe"
metafile = true

[[files]]
file = "mods/yet-another-config-lib.pw.toml"
hash = "2738177155e3d66ddac7519ebb2caee1621d71e398363a14210edc64e19518e8"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "5289bc7bbf2a12b831e1f65ff7b6579d1d04e96c5257b5a81d6997d20decdce9"
metafile = true
