hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "20c4cfacf81141312dedc9e78696522687e7fa9161c62de4167e94e3c498fb50"

[[files]]
file = "config/midnightlib.json"
hash = "8bffacf0777bdc9e35022109e9580583d40fcaa05f0abfed1bf32220a5b39ab3"

[[files]]
file = "config/modmenu.json"
hash = "7e94b21de48ce733607b86c3c60f7297a066e3d6141f27fc6de994e2fe5d46db"

[[files]]
file = "config/slightguimodifications/cts.groovy"
hash = "bafee22e66e93f46f686b2dd5c775f7d004cfe7fb83673f724d17035da8bd590"

[[files]]
file = "config/sodium-mixins.properties"
hash = "051558518a6f3350fadb1546346d937e7f78f69834a075bf91b59921f151cc26"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "67e294546dd7b0c9e0490574590273283da61a4363c68c9a4dcc86e4ba4b4195"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "94f7fc7719381bc6e474b6df30840d2aab0e8c4ed80d2f6191cf1b5b7d92be3f"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "99ecb0cc231f75abd0e0cfb6ebcfae0fa407c1dab9956587c1792d45e715b6c7"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/yosbr/config/colormatic.properties"
hash = "e0dfdbd6f39f1fc0a92b3fd18c981d20953e681f56eec736038f8940afa20d72"

[[files]]
file = "config/yosbr/config/cullleaves.json"
hash = "6ba25b17d218c13aecd7773fb0dd9f01783997854cc7123891e526e82490662e"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "d755fffa95330f9083560f4a9f197c01bd18acccf5f262e506b4d80a4809e6bf"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "05b7909baff3cd0087fe07937c86a7fede1a904ace562b8df5116eca50f1f1e4"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "2744ebcd3589f1124ab556b12e3d73b878fe89901789fdf18787cca12e6a6c0b"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "1a0c50101df35b82a3015882331c4b1b76bec59a05c25cac50bff3547b891f25"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "8bffacf0777bdc9e35022109e9580583d40fcaa05f0abfed1bf32220a5b39ab3"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "7e94b21de48ce733607b86c3c60f7297a066e3d6141f27fc6de994e2fe5d46db"

[[files]]
file = "config/yosbr/config/slightguimodifications/config.json5"
hash = "7da931e9b7389034de203f2719b99ab74ab8e500a898ad5d563d64f13c501120"

[[files]]
file = "config/yosbr/config/sodium-mixins.properties"
hash = "051558518a6f3350fadb1546346d937e7f78f69834a075bf91b59921f151cc26"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "d7db2ecda246d459f1d65c2c60d3581b8d5c02242a957d0c66b2e17a51d86af0"

[[files]]
file = "config/yosbr/options.txt"
hash = "f04ded89072ee70abeca7354bebfa78e4e5097e30d8d8ed17dcdcff758784443"

[[files]]
file = "mods/advancementinfo.toml"
hash = "24dc90f146b01cf980984ff345e7621610aecadeaa1dcb9dd3bb48196b927926"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "e17cc68c6e8ead8e14a00dad783a116cded2a4706f135860b0e3a57c5b9d9c71"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "edb8c30b84c0e3f39b6e0becb95222e1cf38f4b3f6e67960ef129d5061e993fe"
metafile = true

[[files]]
file = "mods/better-beds.toml"
hash = "01ff120031ccd1e5d9e5a192cb12d35f9e479f6a8750a9bd6e134622f17fd1c0"
metafile = true

[[files]]
file = "mods/borderless-mining.toml"
hash = "ade1294a6a99fab76447a9b5da4c8851deb80f9d9245c6dd6c7550e5e9de1244"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "423dbc87f0006c24a4a48dac358da1005e84cddcfbeba2950e41fd822a575574"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
hash = "883319490d214a92959c8621ff6dd7476e670af023abacd612f68c7a08a68f67"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "71c842d27ea4b8ceaafd80012efd3f225859dfb4630ff87a9cc14e3b2717cd96"
metafile = true

[[files]]
file = "mods/colormatic.toml"
hash = "7a2e0d24e6480f25e16ee6083f4c4b75b5d860d36642cbbdb208923d4d67ff6a"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "fb6eda2ffc0dc5cb86c008fbb125c027626b6ceaa84490519054d97375c10e05"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.toml"
hash = "ee30eaaa15b5042923249deb38ccbd1fd908387fc362a29fffa5a3c83afc756d"
metafile = true

[[files]]
file = "mods/custom-fog.toml"
hash = "b86acb01735ca3f4e8746404d33e95c4904390b2b8bb12192c21622c6cbbd71b"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "776ed4e3dab53f365f5258964f3c1cc07992baeda01926ecabb84156f52ccf6f"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "c7d57aae44ec63ecf5f75702f2b4260b2802ae0b700937e80bd51918d5fe9ea0"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "01238fde6bb89276f9452002dd708ef2b36be7a1ec356d849b2007e1845ce92c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "51254a0566840c20f2f335d0152aa2a212f383c8eb84deaee693a72195acea22"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "0777edc4169de8b81edad967af5e682b9a82562c88d5bfe9f6d3212f87ab6307"
metafile = true

[[files]]
file = "mods/fastchest.toml"
hash = "f40870f79914257f0a354a8574b9cce84233274fddb6c1c60d822ae643b8bf85"
metafile = true

[[files]]
file = "mods/fastopenlinksandfolders.toml"
hash = "cfcfca681b376a3f30990a5845ccf7a95255b054674bcefd32c0f02e06f9346c"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
hash = "2534e0d459b174f3c60aeba2774d7f8c9d348f388bd5feabb5033fa009cdb1cd"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "97e364b7078bfbb6846f0c31ac06337eed7fc4c089cfadc11e79f1d9ad34a28e"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "c3d80287766645df566afd44b9cd0358721d93ab0bb26b2a216f8b8603ac4019"
metafile = true

[[files]]
file = "mods/irisshaders.toml"
hash = "7310a7cbfdbbeba193402484b5a9035fcdc3d387f8dedfec1c79d8d23d1592a7"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "d1d089832c56f988c5dbcbd894e904399789fba342525dff9d74a6427acc08a3"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "58df1965a5b70ea3f1b24e3a7e5990ab0096ca845855b4bb623d55450b2a3a72"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "f0a506b8763b9ce7a161b98327423cb12cfa6dafd9c1f78e9e514ccde353588e"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "d469405ae3ba7e17c6603477e0c444914e48932ffca884f630b9ee459ffe0039"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "8ddf577bf21ae957ecab5976bece86001eb073d22cb1779b573c5629827c47fb"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "9003f1379f8ee53c803d7dfa0a34b22f7ddcac395bc0b7290e9358114c286f91"
metafile = true

[[files]]
file = "mods/no-fade.toml"
hash = "657fde7589ed3e09405c72fa52625c80b1f28c9d95351a2acfeccf887c115f1d"
metafile = true

[[files]]
file = "mods/no-potion-offset.toml"
hash = "3baaed144c75bd2a45dc6563478401e0dceb6ba946d3a9d213f2e0c8f9933431"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "6ee12ae9603047eef8cd28df43b5135b2ff69904faef8ffe7e043ca5aff3f573"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "97826dcadbf54e3818b63cb561d4f2d34b5c5b693a66a6edf260c9d23388598b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
hash = "d96687b4f045fc08342f83ca03ec75c7c078a8befcbf2eede340bdcbb8bd98a1"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
hash = "d28af8793971e54ab847379aa5b199bb7a73c4e4df23ece54a2a5d7a779d7bdd"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "03b0fea337b0d6514375aa6fbb7617e6681cbc6409e9355b5828665959f41d0f"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "adbd96356d2c9053fe72d4ff113fd6275b9a7acbe21502cb0e95076094418c2b"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "9290c6767a28583ae994c64b1d5d93c24779299c66bc5c489a03f13796493f18"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
hash = "5f7cfddb7f4129d998e2a41351091d3f9584a9d4fb68b778ba1f7efe49627079"
metafile = true

[[files]]
file = "mods/wi-zoom.toml"
hash = "3fcc363133399c962bd1aef9a5bd56c2d8e6da7280de8f6704e0eff7d0b1f7d4"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "527e21c9bc55b0d1db9016a2fec4ff2dee2a93c53edb8c1363d2d2ee7730afd0"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "d2b7e786063dc6bafc91edfef13f89f6aa9e91e184a85fff90c199757903fd90"
