hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "20119b3fb97992a775f526ebe1dbed2ec79322e590854c82837adb8047722d82"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "891304e6a1bb40fc15b1dc53e74c0e4fd354d7378542c60476f60064d02bc3ca"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "8c79b471bad59fcb9d73c4689dd6687be63facefd73a17f11f1bf4acf00c158d"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "904f649068d150556bdc1d4477610a3f9234d663ac8af69bf2366b70cbcc8bec"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "c27c2904c6857c9429afe2fb0f516a16a7f520c047a26c9c179d44ec133400ad"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "cab638ef75572d2c4bcc9dfd583283e7bbe927fd6c3834930bed52e2dbcac063"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "6b222180584c27fde0fc5c7f94fd3c926f7251f624e676e8b90c0216fb886910"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "b4bd6b6a9cc4d2d821c176442b399139a2aa42581b2e07be77815397a917931d"

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "d22d241a1eee8176561f0c16bf8396e8ded7aa8fd808cf1205cbba3bb5db56a4"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "ed2bc1f554879c214c0ada21c96ee02c8a1b64cdc2f32b8d571c3a860eec74b4"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "159443320977ff331e83b7a6c09aec896efb27666864a71128540e0a8fee2a77"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "a65cb4f97e3600f22f03e28f7e46bf7e2bc66e32350db4fa33f80d094d7252ad"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "1f2b7115dbc44b2c19a4fe4bf4cd5b3095a35f95f2d6a6026f6c48378ba6c9d7"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "1c6797fe2ad866cce4b874038bf74172a2f5872009fc47e8a797c3713d2a7b7d"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "a02a12b02749ee7e040755b792b6b1414948904700cf0234208c11d7056856f8"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "e53a628f53063a042bf622c6409b92685a4de3bcfc7f39df334ebbea8441fe78"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "55074ae1c0026162bb0d8fc3f0b0caa00a1ddd715fa5abe4a03775fb64c80895"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "6efc6d5edb5e2014f0413992fde9e05ba6ad1c4e08f668d3b57b9decf98fc677"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "cbfdad2522d043a57fabcf4096cfd0a893bac7db7327ef7203859dd8c3ba215b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "28a78d91d0844393bea4b4488373501432ade88030c7c341c02456d9a4970455"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3bde4103af9e98fd1124d294c492bd58a6c7b6942f957c4549d51023575f709b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "a331cfae27ee25818e8b27c2a623773c9b82dbd491365e035fdf9869ec6661c1"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "a5f2f793b269bc4834d57c673accde2e2a116c5f364e536555f1d8bb8532a5c5"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "b61f214870361f453bee6de091f4912931ac2a76fda1edaeb11e0c540e572d22"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "bb7f9b806b59200addb38bb67106a5e5ccebd44f350bf65e9d821b37719678a5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "405c5265a1b635934163b26a46bd95dcdce7653360e85e547200c91a5b1b8744"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "9ea3ce665c6837221f44be60a294c404ca117d33aba4470a1804433dde1983ee"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "7319ea77f42bac3f627918b3a2295c73a1e065ba08010466004f707e9ddf9700"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "554e16855ff3f58851c98bfefd892aa07006f40a16d37434a35e21c422dbe363"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2917d17eef3ce35707a3eabc9eff2e1b33254dd77d316e55498d2e82a73aa4c9"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "9eea1d94e8be3ca49d8f889ccb65a820d6dbbba874355652752db11beb2f4852"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "1c9caaf6a0b890d4742ae05b4a3c372867e9ff8ba273b2cf4c63859e9eaa74c0"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "acc4516d208d0fec2d4646253529c42fa3d6ee439b168c38fdf55ef48d7f9bbc"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9fd4ac9a884b81ba36c4906c294652b6fd64c1382de641c48a8dd756c8ffc3d1"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b4a2630c646e451cf53f66e4f96551e4b0475a42711b947eff8bfbafe5c0c966"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "3c9ecc37e1bdfb593a488ba307d0e06b6ed8d5f53c1d4a1a5ca2cf21db2333cb"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "de4f90c9f410c193d28bbfc66dff5ebcacf56a53acd3a507e4a7d2a47d2c9251"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "e9396d7068428886c41c6be66d00897deb2c9870deda2c165b5a519af9c323c5"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "d2019718c50fbc5c33bb29b1418e3bc2e5effd9b89d510782b288036ea03aa75"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "dbccc0c6dd173899a0be461d314ebaeb65b4668dbf057c7f4f1d533b0d26ddb4"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "3e7147d8d6f1e8c34cb7be62dfee8064874b95a0c2cbf9d48c3ae2c93a27603d"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "a2b9f9215f3966160efdc0fc600f8a90989a6983ba59fd1675ec2dad981a7c6c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a13df679f0a76f5bee2aef84948537b610114aaf25258535b8664ef87c0a939b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "7286a1a8b0681862cad1f3409bd23e62ae7d027c59067dba73eaecca76e0e3a4"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "a377db522cb901dd73b4219d497e51554bff1489d8d8e560a0811da2bc7e5e1c"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "74bf2ec0105b4e7d4f6b60332136c98b5fa620a994c13c592ea70874ecfe9626"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "8459c71fa5c28389cc758425b8c1d1cf9462883d870fde2e5f9f39458ec244df"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "084a75f8f0486115c84916e21aa1f5a8e7725d47b416b22010f347d73f0bfcd3"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "ddf5f4f840cebf9ce8c2dc84c56a662ffef020d6ac23fc56c81929ed751c422b"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "8a7b2865d23c76dcbfa47d97a339f3a4ab158ec1fa93ed6a746962c0e3ffd27b"
metafile = true
