name = "Fabulously Optimized"
author = "robotkoer"

[[Resource]]
name = "Mod Menu Helper"
filename = "Mod Menu Helper.zip"
action = "override"

[[File]]
name = "Copy all 3 folders!"
filename = "Copy all 3 folders!"
action = "remove"
