[global]
	#Allowed Values: ALL, LOADING, RELOADING, NONE
	hideOverlays = "RELOADING"
	blockOverlay = false
	miniRender = true
	enableScissor = false

[splash]
	animationSpeed = 500.0
	#Allowed Values: PROGRESS, TEXT, TEXT_WITH_BACKGROUND, NONE
	type = "PROGRESS"
	rgbProgress = false
	reloadText = "Edit in config!"

[other]
	earlyPackStatusSend = false
	resetResources = true
	reInitScreen = true
	#Allowed Values: FORCE_LOAD, LOAD, NONE
	doubleLoad = "FORCE_LOAD"

[platform]
	skipForgeOverlay = false

[interpolation]
	interpolateProgress = false
	interpolateAtEnd = true
	#Allowed Values: LINEAR, CONSTANT, INSINE, OUTSINE, INOUTSINE, INCUBIC, OUTCUBIC, INOUTCUBIC, INQUAD, OUTQUAD, INOUTQUAD, INQUART, OUTQUART, INOUTQUART, INQUINT, OUTQUINT, INOUTQUINT, INEXPO, OUTEXPO, INOUTEXPO, INCIRC, OUTCIRC, INOUTCIRC, INBACK, OUTBACK, INOUTBACK, INELASTIC, OUTELASTIC, INOUTELASTIC, INBOUNCE, OUTBOUNCE, INOUTBOUNCE, CATMULLROM, STEP
	ease = "INOUTQUINT"
	easingArg = nan
