hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "76e6ca1ea09f13d97c2f13bd1ffc5dba6e7f5f610112763bcb0d2d27c9199b84"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "0c5c56dd2004da59d494c4d46acc77e4e9e28855c0b449200bd83c24f275c509"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "d9dc11d57a5593b0a16daa4cbbaaa0973eef2745e753d7d06c9a5447d9b424b3"

[[files]]
file = "config/yosbr/options.txt"
hash = "612ec6d11cbbfed40a8cf0528010370b122d675fb3f2f5d2361ad5d45a144502"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "eefa86fa9a8df6eda5d39d3bbbf53138a44df71a01a24262c27584badea97d79"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "5d4ebf1c83e189cc4b67a579f89fc473aded16d6487683dabafff261a944190f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "3cda5867a305a3bc434feb57ba727e7dbf59ad91a7d8e5e2f25e46acad3ae15b"

[[files]]
file = "resourcepacks/Chat Reporting Helper.zip"
hash = "116811a9848393ef84ef8f457268543d11102244383e16792918dac9ca6cf102"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "8310ec393091be6d401492ddfe38c83ef33a232dba5b3b1bdb57562175611558"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "181b6bda59e65cadc29604b2053955e9fd8299939ccc4604309e4ac97f2659ac"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "b023edfcaca9f400d9afed65ec077cc98a35943fedb4392542f87fbf8613e839"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "bdbbc306c1affe5017f7ff15ffdeb053d019f7c8882253f2579b21e9a7ee06ee"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "b6a392ba7dd5cc8a7c2fa41156da28764936f6f7ce234c07dc67aaef6e7a87d4"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "1d28d6fea844baf44245881614be07154144dc8cee21331a985a6b9895f45506"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "606c450e4f109960a84d3f8af3a989fd9fed4fca5f613510e6da7e6c94d1338d"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "b752ed7ac0a4c09c77d36a48043f75791a69a79d378775794b0e92272163ee92"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "70a11caaea34a1f42da47128409cede3075e719d226e6aa8b9743498200565b0"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "5f77ffe1c914206a0527cab6c563aecfd3a1ccb7ae36e4ed35709445f3327717"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "c7deb0849752ceaab459705e86948d293134f0ece3d00a10e5b9d440476f763c"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "3b3d6b2c0a9256dab61c5e084b3a89d1f946cac9c2da8601dbc184d82053584c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0b2ced37cfac1e790982182f976330350ea90f9bcc7e70d218143ff34e0efb1e"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "df758ccaeb0717137c64653539ddfc1c9fa77085e575d815c89621dbda534187"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4f9965d4bf75ecfbca3c605a48ad7cb8aec9b2f634a7bab557b8600417c904dc"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "820ebe4caec309d9593efcae8b02f35fc2c4672e6d8029ce31d2441df95d5639"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "8fc41ee9c0bb2746b685b5367e7516fda6be4a57f87f661b06e349485532b5bd"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "3bf54134dbf492b27b52b95cc994bfe0e3ec089a884ea1fdad0ee4cc33cf28e3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "cb7abda638c96f6b259fafe92c4ee94e4ba08126216adbfc646209147d6c5092"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "9a245b1cb7d21970634a7d92257c3521a0ec071ae73a08e97d0c302bc493895e"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "cca39b10d2c4c2114da78f89e53a780e3e1440cbe3b5ffd9ced7ca02f75d0573"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "8150f3870de34f177afed881d3bdffad6a07399f3306b336a6810178fa311e84"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5260ff6c72fdf07db862abed1aaa4c063d31a70c175e9b6c1310aff3847d070b"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "4849b74b12da5ec3abdacadd0dc5b1c103917c84847d38023b0a1b0bfac02d6c"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "c8ff90ebc9c700b6729c9b925b8066ff7d8e87fb82aed40faf08ba5d201d3eb6"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "caf5cf800e403f44a64813bf8f4263dd9743983d66a5fabb9bc03d4560996394"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b98f4fabbf58b883dc6834edbed10749bcc5607c15a276f8073986e810f40441"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bf619ec7dae9e2dcd694424a7c702c7fa1f549c3589f9ea0f4ef4d40d9041c2a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "f121bc8142747b9e2b9815f4629c8c7b46046ab210f7d0d312674888bbc6877e"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "0634ad2e90a2be341e9fa98f41d1c2912d19892c3b9cdd0411235fb8d99d289b"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "4d7792023b4cdd7ba399ddf95bbb3af9c3b69557ccfd7177a9aa19b07495e5b6"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "7f2099a5a205f7ce1dfea0f41d2310605042a6c88375d4f7f825bc40e3ede6af"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "7f6579fa0b374c47ac698a7d7fca6d3414231153ad83e75d2cf9295eceffd672"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "2942d4cbf9a81f81caa61d22478a1d416d2a90cee9db43467a776aece85cc07b"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "cbfe5857490ef36a66f5806480e6f7ef7afb94cf0fdae6ef052ea4a371007582"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "1e530c44daa8f494e6ed2c277d1a546dc962042966b97d40708b5205b342ce2b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6155450f14d3d48671b5e96e3d06eb4e6e0262a2e5e917be25edda3abf1d5b8d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "294bc39dfe537f9760f96020140b80828c848809986289a087d5b4d85bc9ccd7"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6842d59da7df8cdccb110287afa1f99d7e9f9a635014fe98b70a0b13e37351f1"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7c42bb0fe982cf5004bfcb62690e9b433890ebd76ea94611fd91c68b00f386fe"
metafile = true

[[files]]
file = "mods/yet-another-config-lib.pw.toml"
hash = "02f733362142989ee648e50b98435a2b4a280f611c9f5a90935a18485bb12bf6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "86ec0fb654b79f16bea7a48be8e018ca8ea6968f8af78583c78cdedb5972facf"
metafile = true
