hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "76e6ca1ea09f13d97c2f13bd1ffc5dba6e7f5f610112763bcb0d2d27c9199b84"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "f4f06b0f74a1328f559860cc8db3315ca2310269313c2b4b9f1cae626fd8cfed"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "58e2bae2a502bb5c7c710ab4c3e5324024b96e7a458e8bcc247d7bbf958e29d1"

[[files]]
file = "config/yosbr/options.txt"
hash = "193b9ea611fa490856a4e795a8d1a6a2a0cc4c9c78f62384d5cac0d90bbd2431"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "eefa86fa9a8df6eda5d39d3bbbf53138a44df71a01a24262c27584badea97d79"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "b04558e3aa16f01cb56278cbb0ae1a2a7c65b5288ee056865a07b2764a850f65"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "245846dc2c37fcebaccc08299c0b345552c2f031b5603b68b0bc3a1b869224c0"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "97a19031a10809c206b89c366bf1e802e4f2d39e9df798c3c627bf0d63448447"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "5d4ebf1c83e189cc4b67a579f89fc473aded16d6487683dabafff261a944190f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "cb2555f4fdcc6c3bdb47f07cc5a8a92998a27f9273befe3836d3c6b652032ee4"

[[files]]
file = "resourcepacks/Chat Reporting Helper.zip"
hash = "d434a29ba370ba43ca34b1c6b44a7f882869a136bf935729bd53db965c1c824d"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "8310ec393091be6d401492ddfe38c83ef33a232dba5b3b1bdb57562175611558"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "181b6bda59e65cadc29604b2053955e9fd8299939ccc4604309e4ac97f2659ac"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "b023edfcaca9f400d9afed65ec077cc98a35943fedb4392542f87fbf8613e839"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "bdbbc306c1affe5017f7ff15ffdeb053d019f7c8882253f2579b21e9a7ee06ee"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "b6a392ba7dd5cc8a7c2fa41156da28764936f6f7ce234c07dc67aaef6e7a87d4"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "6bda1d6e217b5fb97a0006e99871367658c1b17220fdd3d3b1a90b5fc454ea8c"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "ee3bdb9b1293bb25e0979e030750a9d788a2edb0e7c854f0f63b9101443e6f44"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "b752ed7ac0a4c09c77d36a48043f75791a69a79d378775794b0e92272163ee92"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "70a11caaea34a1f42da47128409cede3075e719d226e6aa8b9743498200565b0"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "c7deb0849752ceaab459705e86948d293134f0ece3d00a10e5b9d440476f763c"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "3b3d6b2c0a9256dab61c5e084b3a89d1f946cac9c2da8601dbc184d82053584c"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "578a704b4f0767fcd311ccd170a6e674a2178cf00f973ae33fae1e65599f64cf"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d50351d5201a0d1d21c8b2caa9b123cfaf46765287d4a21fd12dde57e79124dc"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "a0712066132be92036c967095502caadb46a151a55fe7bbbf600518987e7d70f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "de4c8ba57b81c8945a096b98e1bcbc1d255d6ee119bd24370d78f0bc39952c93"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "860a1c62c4fab41dc5f0084a7f83cf21c9d87a201a0593d049208114146e11ad"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "3b9806348675a2ac2b6f39d9e6e61adbe9317ab16330c444856626e261389d47"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "3bf54134dbf492b27b52b95cc994bfe0e3ec089a884ea1fdad0ee4cc33cf28e3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "248e44131bf9ab35abdd27646066ede72f2128d51fd43150c9676d6eb5eeb64b"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4378ed8c8083eb922d2e4dd552b3525986cbb0d509a2d6ed0e4872866da3b0a8"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "9a245b1cb7d21970634a7d92257c3521a0ec071ae73a08e97d0c302bc493895e"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "47c82d9f6ced15a94513b513a411e403d003db17ad22e9c91b8b3f58aa4e516b"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "a8b989c17eea5120c846bb378cf80511f99dcf17502ae54fca7c548ed27dbf9a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f7e8e5f3cef2b620a488ef4b13a9151597825cd267bf39c60be79d9e9cda1a67"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "4849b74b12da5ec3abdacadd0dc5b1c103917c84847d38023b0a1b0bfac02d6c"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "2e8726d9ae522970614b362d25bee15427c26adf61fffde1858fcae2d99fb4b1"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "caf5cf800e403f44a64813bf8f4263dd9743983d66a5fabb9bc03d4560996394"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5068ecb1119e140028af648cee7d5c1d0f78cb45c389abc3a65e5644e2c42a5a"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bf619ec7dae9e2dcd694424a7c702c7fa1f549c3589f9ea0f4ef4d40d9041c2a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "e1693c2bf2af46cf7b67d2271ffbea317b3da2733fb13025d46d7ea35d8025b7"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "0634ad2e90a2be341e9fa98f41d1c2912d19892c3b9cdd0411235fb8d99d289b"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "4d7792023b4cdd7ba399ddf95bbb3af9c3b69557ccfd7177a9aa19b07495e5b6"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "24e905f67dfa82bbc818cd97e9cdf8e3652ec7db77b761c9c2174aa89ece8419"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "ec726d28b77c4a483fc3818ac0baefb035bbbf30321689137f4fc377bfb66f31"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ce12417586a03a7d277ee5afcf5b52439464e54de56200aadc13965bc0586d99"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "494600107f9f5795094d5f41cc5fd02cd77a093a919abe1ab9953f8d5c90c6f0"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "cbfe5857490ef36a66f5806480e6f7ef7afb94cf0fdae6ef052ea4a371007582"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "1e530c44daa8f494e6ed2c277d1a546dc962042966b97d40708b5205b342ce2b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6155450f14d3d48671b5e96e3d06eb4e6e0262a2e5e917be25edda3abf1d5b8d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "62de7e5dd00ef1e4846e45c692bd5570b48c26d8929b5b9b54fb76c9b929b0ac"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6f73b45f0d1232e9d35a552b7f90bd9b4820cd72d56aaac1bd7dceb93e979ba0"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7c42bb0fe982cf5004bfcb62690e9b433890ebd76ea94611fd91c68b00f386fe"
metafile = true

[[files]]
file = "mods/yet-another-config-lib.pw.toml"
hash = "02f733362142989ee648e50b98435a2b4a280f611c9f5a90935a18485bb12bf6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "86ec0fb654b79f16bea7a48be8e018ca8ea6968f8af78583c78cdedb5972facf"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "16687487f47771adc2cbb021de843ea985112aa49ff8b549e56319921b03a18c"
metafile = true
