hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "76e6ca1ea09f13d97c2f13bd1ffc5dba6e7f5f610112763bcb0d2d27c9199b84"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "df20bd148cec818d72e0b5ab442c91bb2a5c84b769ef0df04924f7985b83ec04"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "f2bc2bf583c437bc4d13bcbd22fed9082710ba2b14e35b798e7da57bd49d69c3"

[[files]]
file = "config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "ffcf8a2a08327db7a17ead4640bde4df6d97eb9253c4bf4ad2c5a5fcd1234547"

[[files]]
file = "config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/options.txt"
hash = "adcd87b44677e5f674cb75c9456edc8e14e9c9c70d28d7f3a283e262f697279c"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "7de3087b5a435f770ed45b1b73ac9b37f3d36ab2fd71a1404d7a49e299738821"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "1656c1ce6af02cfb451541c7d5c938c51cc9e7aee962aee526c46f4be40cada3"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "31027fdd3f059f54bf91a8a8f19c08c0dd27d95446469f00f65ff5431d32c6b7"

[[files]]
file = "resourcepacks/Chat Reporting Helper.zip"
hash = "84fb1448e9d738d58a4916a15acd81dc33b76d699ee3153f5d7e34bd02de145b"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "8310ec393091be6d401492ddfe38c83ef33a232dba5b3b1bdb57562175611558"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "181b6bda59e65cadc29604b2053955e9fd8299939ccc4604309e4ac97f2659ac"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "b023edfcaca9f400d9afed65ec077cc98a35943fedb4392542f87fbf8613e839"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "bdbbc306c1affe5017f7ff15ffdeb053d019f7c8882253f2579b21e9a7ee06ee"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "181e51852d990e383707a23c415ab51a9bc5925298c45b6185aad23ba3956d6d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "70a11caaea34a1f42da47128409cede3075e719d226e6aa8b9743498200565b0"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c7eccad65192d2a53d94454f187551b10cf8f6b07e17b48f4850cb31efe3a1c6"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "8c915406fc76caa13f19d16b9cc16bac1f44c69c8ed39851d7b8ca7b32a896a0"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "3b3d6b2c0a9256dab61c5e084b3a89d1f946cac9c2da8601dbc184d82053584c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0b2ced37cfac1e790982182f976330350ea90f9bcc7e70d218143ff34e0efb1e"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "9c56cf76719f88d9e235db6e9d2f3ba1c8c868810b6c6926ee05a781eee18e17"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1745f52b7225d9ff2a7bddc7dfd8eb9b6d65c324a4a39e420c946f0cb364dfd8"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "66b57e089f4908fc98dd34e70fd55be04f35d2ed529b88966e15c8682b10dba2"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "8fc41ee9c0bb2746b685b5367e7516fda6be4a57f87f661b06e349485532b5bd"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "3bf54134dbf492b27b52b95cc994bfe0e3ec089a884ea1fdad0ee4cc33cf28e3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "cb7abda638c96f6b259fafe92c4ee94e4ba08126216adbfc646209147d6c5092"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "9a245b1cb7d21970634a7d92257c3521a0ec071ae73a08e97d0c302bc493895e"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "cca39b10d2c4c2114da78f89e53a780e3e1440cbe3b5ffd9ced7ca02f75d0573"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "41495351c7a06440696e284865a584aea86164a81b49f76bc9c125ac7f521047"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "ef0f19aac80868f61dab6be6386cdf50f71be4174cf0be13bd0b15ba2b340a7c"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "caf5cf800e403f44a64813bf8f4263dd9743983d66a5fabb9bc03d4560996394"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b98f4fabbf58b883dc6834edbed10749bcc5607c15a276f8073986e810f40441"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bf619ec7dae9e2dcd694424a7c702c7fa1f549c3589f9ea0f4ef4d40d9041c2a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "f121bc8142747b9e2b9815f4629c8c7b46046ab210f7d0d312674888bbc6877e"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "4d7792023b4cdd7ba399ddf95bbb3af9c3b69557ccfd7177a9aa19b07495e5b6"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "be981e54e68763f18dc364f51430875a48e34b9f0c5ccd8f84c2f7c94ef16136"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "69b55583506ac5247b7477927fad1a2e84e40909297255a5937b979dcd9bcfcd"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6155450f14d3d48671b5e96e3d06eb4e6e0262a2e5e917be25edda3abf1d5b8d"
metafile = true

[[files]]
file = "mods/smoothboot.pw.toml"
hash = "ee3d980387c796b4342db65d9769dd21222bf4b7250f4a380518a611291cfeea"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "220bc42911e2f24b50c9d705a20b64a9193064a356a59ca1b98c3416a45783b9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "897958a92fafee84ba04033f6fce9a2b1ae912309e3a46d8e43c573e69207cd4"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7c42bb0fe982cf5004bfcb62690e9b433890ebd76ea94611fd91c68b00f386fe"
metafile = true

[[files]]
file = "mods/yet-another-config-lib.pw.toml"
hash = "1636a4b46d872b09b5f59878ba7f567256e58ff8b5a59f8439ff5bf11807541d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fb2d59112294b5fa973c5726c1ac7d804e51a8837cb74badae970aea5ed7dce1"
metafile = true
