hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "76e6ca1ea09f13d97c2f13bd1ffc5dba6e7f5f610112763bcb0d2d27c9199b84"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "91a609eb7584a7acc6f271aee37397bac4f086a20a69196b46928ad97aa49f2d"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "e13a034493d362a41b86bddcd1cc1628813abc83c3da399a6bc54724b4796385"

[[files]]
file = "config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "5d4ebf1c83e189cc4b67a579f89fc473aded16d6487683dabafff261a944190f"

[[files]]
file = "config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/options.txt"
hash = "b76bfbdaab1c66e4b622f5a4cb549fd4504f40cb6186255e5e77c4f0d14fdfb6"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "1656c1ce6af02cfb451541c7d5c938c51cc9e7aee962aee526c46f4be40cada3"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "838a2f1aa41a71f4e47bf4a89f3c4a7b04943fa28150fbb19070fd3c915dc492"

[[files]]
file = "resourcepacks/Chat Reporting Helper.zip"
hash = "bb811554df21719a614e3eaf9b9c421a95376222257e33be69ee27a6e750afc7"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "8310ec393091be6d401492ddfe38c83ef33a232dba5b3b1bdb57562175611558"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "181b6bda59e65cadc29604b2053955e9fd8299939ccc4604309e4ac97f2659ac"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "b023edfcaca9f400d9afed65ec077cc98a35943fedb4392542f87fbf8613e839"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "bdbbc306c1affe5017f7ff15ffdeb053d019f7c8882253f2579b21e9a7ee06ee"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "b6a392ba7dd5cc8a7c2fa41156da28764936f6f7ce234c07dc67aaef6e7a87d4"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "1d28d6fea844baf44245881614be07154144dc8cee21331a985a6b9895f45506"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "606c450e4f109960a84d3f8af3a989fd9fed4fca5f613510e6da7e6c94d1338d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "70a11caaea34a1f42da47128409cede3075e719d226e6aa8b9743498200565b0"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "5f77ffe1c914206a0527cab6c563aecfd3a1ccb7ae36e4ed35709445f3327717"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "c7deb0849752ceaab459705e86948d293134f0ece3d00a10e5b9d440476f763c"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "3b3d6b2c0a9256dab61c5e084b3a89d1f946cac9c2da8601dbc184d82053584c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0b2ced37cfac1e790982182f976330350ea90f9bcc7e70d218143ff34e0efb1e"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "9c56cf76719f88d9e235db6e9d2f3ba1c8c868810b6c6926ee05a781eee18e17"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "46b1d01ff523b8bb890b2b782387149dfbd101dade2b6cbcf45622e4feee91ed"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "66b57e089f4908fc98dd34e70fd55be04f35d2ed529b88966e15c8682b10dba2"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "8fc41ee9c0bb2746b685b5367e7516fda6be4a57f87f661b06e349485532b5bd"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "3bf54134dbf492b27b52b95cc994bfe0e3ec089a884ea1fdad0ee4cc33cf28e3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "cb7abda638c96f6b259fafe92c4ee94e4ba08126216adbfc646209147d6c5092"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "9a245b1cb7d21970634a7d92257c3521a0ec071ae73a08e97d0c302bc493895e"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "cca39b10d2c4c2114da78f89e53a780e3e1440cbe3b5ffd9ced7ca02f75d0573"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "090360b549c314bb8c94c41d04a0832dd4686da956046547017c692e0f09ef59"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "41495351c7a06440696e284865a584aea86164a81b49f76bc9c125ac7f521047"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "ef0f19aac80868f61dab6be6386cdf50f71be4174cf0be13bd0b15ba2b340a7c"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "caf5cf800e403f44a64813bf8f4263dd9743983d66a5fabb9bc03d4560996394"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b98f4fabbf58b883dc6834edbed10749bcc5607c15a276f8073986e810f40441"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bf619ec7dae9e2dcd694424a7c702c7fa1f549c3589f9ea0f4ef4d40d9041c2a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "f121bc8142747b9e2b9815f4629c8c7b46046ab210f7d0d312674888bbc6877e"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "42eee30bd9b283a3d88d5a906b49501a4904725e9e208a85196574f7d6de3db4"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "4d7792023b4cdd7ba399ddf95bbb3af9c3b69557ccfd7177a9aa19b07495e5b6"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "7f2099a5a205f7ce1dfea0f41d2310605042a6c88375d4f7f825bc40e3ede6af"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "7f6579fa0b374c47ac698a7d7fca6d3414231153ad83e75d2cf9295eceffd672"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "2942d4cbf9a81f81caa61d22478a1d416d2a90cee9db43467a776aece85cc07b"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "cbfe5857490ef36a66f5806480e6f7ef7afb94cf0fdae6ef052ea4a371007582"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "6155450f14d3d48671b5e96e3d06eb4e6e0262a2e5e917be25edda3abf1d5b8d"
metafile = true

[[files]]
file = "mods/smoothboot.pw.toml"
hash = "ee3d980387c796b4342db65d9769dd21222bf4b7250f4a380518a611291cfeea"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "9bbcf97aa5a4290e4c04610f809aacd8b4cf1b4bc31438e78d7236c022efe01c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "897958a92fafee84ba04033f6fce9a2b1ae912309e3a46d8e43c573e69207cd4"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7c42bb0fe982cf5004bfcb62690e9b433890ebd76ea94611fd91c68b00f386fe"
metafile = true

[[files]]
file = "mods/yet-another-config-lib.pw.toml"
hash = "31e5a54adaf2fa071eac06f662fb66a7c2fbbb58ac653a1d561648b2726803f5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "86ec0fb654b79f16bea7a48be8e018ca8ea6968f8af78583c78cdedb5972facf"
metafile = true
