name = "Fabulously Optimized"
author = "robotkoer"
version = "4.6.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "403512cf838f478d9b3b162430cd9154b175f7cea65214a5560a8ca34945dbf3"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
