hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "722d32f543b636f46f3bcee6a0692e49681cfece53392545e5834d4be0068c72"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "d032c8240cd72cc60904a86d4a3878e3f8e2152bdff196a0f6f95c1461b96932"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "8c79b471bad59fcb9d73c4689dd6687be63facefd73a17f11f1bf4acf00c158d"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "904f649068d150556bdc1d4477610a3f9234d663ac8af69bf2366b70cbcc8bec"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "c27c2904c6857c9429afe2fb0f516a16a7f520c047a26c9c179d44ec133400ad"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "cab638ef75572d2c4bcc9dfd583283e7bbe927fd6c3834930bed52e2dbcac063"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "59fa5a7fdbcc83cc2dd9a23542d0f950d2e6ba64c368b456c4afc5f8900d8e1d"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "5be0f4c13807a28059e1aec037b1a27449369be6a7e07aec5f73c2d4fb23c5e8"

[[files]]
file = "mods/animatica.pw.toml"
hash = "8cf639c849e6c731af3fba8d8f42fb8aca6e3a9dae102411c38c4c44e6872af7"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "2015444afd860c79fe1ca3737053873cc44cc9cef78c6384a3c82c7df73ee57e"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "2a375a9423ee8b9f10bba8457433263412cb328484d94ddf284e467dd41ebf77"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "54903e0c688ac551485ad60ff6944b43fbe26bf808705d3a079231d08a8f67a4"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1b160fa40eedcca394d73215ccc1f48d9305493a1c6a886f1e8355ea38dfe55e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "fd9b37c0dd351191944a8ebef602b1f0f35aaeb151dd236f773638bf8b609131"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "1c694e057b1716db058a93243bcb44af84fd37e55e3417b1a6fd6d32458bac0a"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "0fc3a1d40088236625c545c3f76d61e51cadca7ca1d69a196c3061d36978ae78"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "e3dbc76d36c6fdca359b48d56d179da8399dc928dd1ff4d265041eae0d89c480"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "d6f182cfc4ec0f9ce54912628dd0552e0b765b5a64710977025e98de1188913c"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "e42814880e0fb251356a3bcb3269bf47d7e8ed295e8f0d3e56787f8cabbc52d7"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "add6231ab8479da7625a44683862906ea1dd6586e75c253e90eac7c082d1e8c2"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "a50d4f9c44337d7cba36c1b5bd6a48deee5ff6f07c7e5aab3c0c2d6a8d300fa7"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "562d0ab03949c41308ca7e95e7c2ea949870eab4517ea56e22152c2a47c814e3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6f5a9a26a69c080e6ece18a1188bfefb0192a6fa6662edf404522a5286f1e386"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "dc58a4ad2392122c72423d17d6e1c59f1b9bb87f6f807a31dd3b09116f5824ed"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "135336f2c9807eff59748dc12948b29075136073889e65972a05e0d34c460502"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "7f416e1e3f87291645fa70a03c5e907f862bc653b1af33d90453550724cbb886"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "4ee00a5436bf144f0eca2010a1dc3e4813117ee159e24c51337cfcde6a356eb1"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ad68291896e892edafe6d0ef625f0e909a01045bc1e25f5e34a0ceb072f42351"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "fdf540c4ae42d59d6c1b8e6a9fb1c8e43e990df12ce2254064d4f40294266417"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "b0479f25fa47d29a6f0f3d09df3859efc2fed95d829e24ee70765227115b8833"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "990f8363ccc2e08afd4abc86997c42bc4f0b9058c45958080a725da650c4c551"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "ef0ae849e0db9dbcf57381c934de8c1c20f8867d44e099c48c737a51c6b053d1"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "2f63ef42a78f97ae2c88b91b5e5fa66843b27f0290d4ec9e4f594adc5b4fc48b"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "4f3fb61385f4b3fc00edb67ea7f3c7cfb708830c12613a44660bc355d8a16df1"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "427a352ffd706af44b8626175b3a735c8a70f8e42272abcf29a391843e28fd31"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "9eea1d94e8be3ca49d8f889ccb65a820d6dbbba874355652752db11beb2f4852"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "3873dcd36167b0bb9f1e26d1a9292325b21584974f36f52884d5ba7dfb592e24"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "38d81316590545e95d32f49c65d9424cc76bdbef261ee8c629add735b05c3143"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "0bf519c81bdf898ad3b9ad4ba4172427e90f82429669d85d6c12f7acfc3712aa"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "a70105438f11495884d645c716605182185dc49853a0fb85c249cdc9ca20d121"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "4ed6639a3ee7eb1806bcf14e8fc895ad134d11811b20245269441bb80d1828f7"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "88e0b9fa2de16838bffaafe1838d9b4d4a562eb216ba8355770caf2f4d4df52a"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "0db86f115a313d0dce5b0068a470f6bf51faab6cbb659a2c84b0cd5e7d187072"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "18a9af79feb21c9e907d211b97242688f20d2b5008b01af7bdbdd0b938c0bbd2"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "5550afd80525dfe97ca9fddd3291f3765e1328bfa9661ad9ea0aaef73d4d5873"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "08a438f3bc8e725598679eceed1f17e60231183628e5fe6b8b3b59ebac1e0368"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "2592a155dfab4861f74d69654632deef08c01b60f9a64010223788d9a182debc"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "9d9cbcddb3629a1aefa4d4d1150fc725e5423a63f55627aef4c275313a35d08c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "038451ae03dc9f1f61561add2e4c31053369b01951c2d547214809669c0fc910"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "9ff006c160bde3a9a319a162b25614dccb59f53e8863784cfb125971d384722a"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "24f8f1b92dc6199ac4646cf490365eb457740b103e643b85a646bb9b4542eb60"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "11dd46c1570434086cb1a850d828f2d6285833dea1e941a15927d181681315bd"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "5be451b61321fa135382e5e93772e1093464254cd1bba622e3823cbfff2308c2"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "c1183271a7455b211de3013288e4edfa5c658e366c981b52a685efaf76315c49"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "ffdd3f3fcb3fc1ddd2ef2270bd3345e37431fccf02fd8325e61e669ce4a743fc"
metafile = true
