hash-format = "sha256"

[[files]]
file = "config/entity_texture_features.json"
hash = "e93eff83c16cdcfca6b41ef7d44d511d59e9e8adc05aaa0989e1f69ebe0e77f4"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "930ebc914fd115d2ff8a61811156e3633023b6e48ab8ea21cf3fb60521a132ce"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "c636572d218713628b5e0d7e14fb5a8d5b6bf4940980df0ee31dbc0b0db9fb9e"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "8c79b471bad59fcb9d73c4689dd6687be63facefd73a17f11f1bf4acf00c158d"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "904f649068d150556bdc1d4477610a3f9234d663ac8af69bf2366b70cbcc8bec"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "cab638ef75572d2c4bcc9dfd583283e7bbe927fd6c3834930bed52e2dbcac063"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "59fa5a7fdbcc83cc2dd9a23542d0f950d2e6ba64c368b456c4afc5f8900d8e1d"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "5be0f4c13807a28059e1aec037b1a27449369be6a7e07aec5f73c2d4fb23c5e8"

[[files]]
file = "mods/animatica.pw.toml"
hash = "8cf639c849e6c731af3fba8d8f42fb8aca6e3a9dae102411c38c4c44e6872af7"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "2015444afd860c79fe1ca3737053873cc44cc9cef78c6384a3c82c7df73ee57e"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "2a375a9423ee8b9f10bba8457433263412cb328484d94ddf284e467dd41ebf77"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "957b30b969708a447637579e64964d73dc972ca096d5be09b284d65ea625e480"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1b160fa40eedcca394d73215ccc1f48d9305493a1c6a886f1e8355ea38dfe55e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2dcd21cccf1b66ebc5d4a3acd86a74947670289271ad2de7f9c5991173999ae3"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "ab781b221900879c4cd79547282978c6fff6ccd4a23d94bcb1d7c257bb9cc847"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "428eec696f3d3c6be80a562e14c9c125ea76052c5b2dd7023e8d1ceba504c3bb"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "e3dbc76d36c6fdca359b48d56d179da8399dc928dd1ff4d265041eae0d89c480"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "e4a7919f482cbb4be33d7369325cb4fdc9c18de8988bb0b0f636b3fb75bc4b7e"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "414767580618ef4e044153dbce5abc67673b1ffd9ecfc41c306855773f701eb3"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "8fd00f42dbe6e3fa657f3efea07a94235c99e4895e6495dfa8d6e6cee7467e9d"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "5b83f72d83f95a32264dba8ec9fba782a19b10a534d5c78af746b88a3e93a387"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "511a9c7a5b6d990c624c9125f213070e6aea2720303e2c0ba3311e83a288e5d0"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "264107f58b33c5e139037c9a7affcd5e8b59a48a81da3ff9673756c7de9dcb42"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5ae3a5016d401c9ed0f84cb6218177e8fce054793c8ced35eab31c7bfe2cd442"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2c12c941a04bbdcc4430bae31b8c24c616ed8a57d9184f5d741b7dc3db2e9c97"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "7f416e1e3f87291645fa70a03c5e907f862bc653b1af33d90453550724cbb886"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "4ee00a5436bf144f0eca2010a1dc3e4813117ee159e24c51337cfcde6a356eb1"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ad68291896e892edafe6d0ef625f0e909a01045bc1e25f5e34a0ceb072f42351"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "286845bf12586c4e2ade76793c426243fd4699f02a51d076415050214abc67fc"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "b0479f25fa47d29a6f0f3d09df3859efc2fed95d829e24ee70765227115b8833"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2c6d07a1e380d1d0c666edfc9791feed9482436b4c98b5887af6fda2ad07545f"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "fee53c465de97783c1db91816038a25569679c82a0d3579f84acd3f9e97da516"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e8fcfd0031b396bc2d41a29171750ccbbe8fd2cf0bbf56cff9781c030b6bff07"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "ec1b08599de799e00f251a4828793d2f88ac50c7c9ff78b25b5c9c7455e1e12f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "4efa10d757e3af2f3b26d4769be6edad91b8fb68cb4872463aa4e73c6d7d14c0"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "9eea1d94e8be3ca49d8f889ccb65a820d6dbbba874355652752db11beb2f4852"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "3873dcd36167b0bb9f1e26d1a9292325b21584974f36f52884d5ba7dfb592e24"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "4fe5680c0425a6dccd57ab2eee1324b283a80a5a1a6799f348a243b7e738c63e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "765d106a839a861f41023980da128e522062e494567f0471de493d31748d96b0"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0bb4c79e97f3eb1a710d7621d028682068a7504b9c53be56b40bd57cd0c0ef6a"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "d834e6b79315c53ddfa4020900fc062c27aa123a4f335a183561e43c8b674eaa"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f3fd21cc85f5450699e3b2a48e97527b8323a18b3af5130592a19631e56080f6"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "0db86f115a313d0dce5b0068a470f6bf51faab6cbb659a2c84b0cd5e7d187072"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "de69b8d7af8921e840d153ac2f2cd31ba3704580cd67e438be841eb399310d42"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "245e07a03f111baae143708690e2413588e95748db610cf6b4c786b70518bbbe"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "481281dcc5eb94fc3493a1289c62dcd398e5909263e3e5a070012100cb08cce9"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "6b598cc85e66cc29aa8d2919b66ebf89473fbe5b062f8f5628071bf92865f9a7"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "197427b59c8b24eef976d58683f4211a8810f9fede63652f46fa19608707615a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6646f0a19b38b583cf44a68d5b31e17e1ad3104ec28121e49c5de73d214333ec"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "23ef9d9c164ebe23ad26ff89669b1d13d7ec33ce0bab05d4f509a3647fe086cc"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "f542b36feed9ada4b99cc2170abfbc1988f9cbcb1b72a775cc267493cbc57cb8"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "ea3b63cf31c31efd9d5d7aff5d726ab39b52d5ee55ab61953e1a5f956717916a"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "290391e0d98878f0a9218891f04e7fd8d6259c8feb032a3c503c75007a3189ef"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "606d03266d569298bfda30c68071b7241fb8df2a07d2bef088065ceae6d51bac"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "cc66b707f02055671b3faa15ec5713cd2ede57c6b89babd5cb19e132c3757ac8"
metafile = true
