hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "93e4a7eab3977c9aaec84a8fc7971183be80d934bc498cdc552f864a5dd5a095"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "923b953e224626cc955d997ef0be532dfcf454ba5028681ef597b8666deddfd7"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "8c79b471bad59fcb9d73c4689dd6687be63facefd73a17f11f1bf4acf00c158d"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "904f649068d150556bdc1d4477610a3f9234d663ac8af69bf2366b70cbcc8bec"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "c27c2904c6857c9429afe2fb0f516a16a7f520c047a26c9c179d44ec133400ad"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "cab638ef75572d2c4bcc9dfd583283e7bbe927fd6c3834930bed52e2dbcac063"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "59fa5a7fdbcc83cc2dd9a23542d0f950d2e6ba64c368b456c4afc5f8900d8e1d"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "5be0f4c13807a28059e1aec037b1a27449369be6a7e07aec5f73c2d4fb23c5e8"

[[files]]
file = "mods/animatica.pw.toml"
hash = "8cf639c849e6c731af3fba8d8f42fb8aca6e3a9dae102411c38c4c44e6872af7"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "2015444afd860c79fe1ca3737053873cc44cc9cef78c6384a3c82c7df73ee57e"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "2a375a9423ee8b9f10bba8457433263412cb328484d94ddf284e467dd41ebf77"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "54903e0c688ac551485ad60ff6944b43fbe26bf808705d3a079231d08a8f67a4"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1b160fa40eedcca394d73215ccc1f48d9305493a1c6a886f1e8355ea38dfe55e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "fd9b37c0dd351191944a8ebef602b1f0f35aaeb151dd236f773638bf8b609131"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "8cc92bf5474422ebedd2baca5599b25c3126efdba52ade4dfb892018c9cbb197"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "0fc3a1d40088236625c545c3f76d61e51cadca7ca1d69a196c3061d36978ae78"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "e3dbc76d36c6fdca359b48d56d179da8399dc928dd1ff4d265041eae0d89c480"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "0e9a2871c9da278f08e5e7323e201646f1ec5517ed3361219bdbd56988b0f660"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "55074ae1c0026162bb0d8fc3f0b0caa00a1ddd715fa5abe4a03775fb64c80895"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "add6231ab8479da7625a44683862906ea1dd6586e75c253e90eac7c082d1e8c2"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "a50d4f9c44337d7cba36c1b5bd6a48deee5ff6f07c7e5aab3c0c2d6a8d300fa7"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "562d0ab03949c41308ca7e95e7c2ea949870eab4517ea56e22152c2a47c814e3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0f10868cffb2a2849cf23802996493f1965a33c8968535dca356cd72432fb3d3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3a8e36009ad7c6716b93387238ad78474d1dbb8e0adecbc4c2e0d2762c4c6ef7"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "a331cfae27ee25818e8b27c2a623773c9b82dbd491365e035fdf9869ec6661c1"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "7f416e1e3f87291645fa70a03c5e907f862bc653b1af33d90453550724cbb886"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "4ee00a5436bf144f0eca2010a1dc3e4813117ee159e24c51337cfcde6a356eb1"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ad68291896e892edafe6d0ef625f0e909a01045bc1e25f5e34a0ceb072f42351"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "fdf540c4ae42d59d6c1b8e6a9fb1c8e43e990df12ce2254064d4f40294266417"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "b0479f25fa47d29a6f0f3d09df3859efc2fed95d829e24ee70765227115b8833"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d3ed368e824b7509012327b74f931fe882a98b6bb20982464dc5aa8e283d5b28"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3964436f8ec12f7804fde98d878292f25524716aa03a1bfa4c5db074e23b5f5b"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "142e36d673ef1daede716bb8ad40ea4fa4c14abf9cf89f9203657f183e62a43c"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "d4100793deadc522342f728b2851db9808fbe39b1d925cfc0ce7086d7cb3b601"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9d02f07da78f50e1d6743a4b77d3572817d5f494d36563cb771e292f8fde6fd9"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "9eea1d94e8be3ca49d8f889ccb65a820d6dbbba874355652752db11beb2f4852"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "3873dcd36167b0bb9f1e26d1a9292325b21584974f36f52884d5ba7dfb592e24"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "38d81316590545e95d32f49c65d9424cc76bdbef261ee8c629add735b05c3143"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "0bf519c81bdf898ad3b9ad4ba4172427e90f82429669d85d6c12f7acfc3712aa"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "7a8dfee002d9a5e68c4f1dc5e71051915ee07499512155626e5cc95141e2832d"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "4ed6639a3ee7eb1806bcf14e8fc895ad134d11811b20245269441bb80d1828f7"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "88e0b9fa2de16838bffaafe1838d9b4d4a562eb216ba8355770caf2f4d4df52a"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "0db86f115a313d0dce5b0068a470f6bf51faab6cbb659a2c84b0cd5e7d187072"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "bd0e9a8b1c31d9eb27b3177986d35548fb6fe14d638f41f9fa046e1b976c5a75"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "5550afd80525dfe97ca9fddd3291f3765e1328bfa9661ad9ea0aaef73d4d5873"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "08a438f3bc8e725598679eceed1f17e60231183628e5fe6b8b3b59ebac1e0368"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "632201db506dce7b7c595e6fbe1736e5ffeba94711bb80d724abf02b9041ffae"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "9d9cbcddb3629a1aefa4d4d1150fc725e5423a63f55627aef4c275313a35d08c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c1e212ee0c2341d74b4a233ca7728a410c6f6d9f1b8258c7db146d05a353ed04"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "e0738e457f016beffd0f157c0111ef8286511d40fa551dbc52357de1e8e05704"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "24f8f1b92dc6199ac4646cf490365eb457740b103e643b85a646bb9b4542eb60"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "3a33952de65d450c775ecda6ba7f1ce514b3a7a38cad08decffb7dcb4b7a2c4e"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "084a75f8f0486115c84916e21aa1f5a8e7725d47b416b22010f347d73f0bfcd3"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "1104ee52af4be993906e2ef2a1cf1798bc0a417480228019acde4670fa77e61c"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "0033872b37d4f48bd052f635c259966054ec2b095f8e6a8d51073fa8d8f887e3"
metafile = true
