hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "b887260707a50a6ea37a559c8646a1742a8b0c6ef96ee8564ac701f0e7f947b9"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "823c8d3cc20afb8e6857d31e35a37880581bfb827f7d021a10e6178ebb13dcdd"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "8b36ea8af428943d85a7594b9d2e8144be3f77bab05a150e8b2db4dbe8f25a37"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "88a4b9df8024bfb56294ee78b9c85e569f35c66cc9f14e88284512335a3638d2"

[[files]]
file = "mods/animatica.pw.toml"
hash = "23b3d1ad268ba3a1eaaea01b74ff3dd5ae9123c0cb0ba29ec85c98b0e6eadfba"
metafile = true

[[files]]
file = "mods/bettergrass.pw.toml"
hash = "8c4051285a26835f261d0f7ebc5170d27e072c22185cb445c27502502f730567"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "24b0177dacb547321d83487699e13bf6f6fa004c0d8199dbcc0867b2c21097ee"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "bbd8863b1b4d77d30bb31310d4e549a4f3f28b580fdf76f742d7b4c1f2f79f71"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "cf821651d19efbd89824d89972e592723b1e9e2c5dee3495e9366cfe904e27ec"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "705bc0827aed5af8d86de5b7aa7fdd7cadd647075635bad690e0c54d7f467425"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "e1136108f97f3daa01a51217f18b32c0998a74efd16a17d35f76fe3c00889442"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "867f8e4be9bc139a517dbcf55aefc2938c5e461640bd08024ec4716fce068025"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "05ebc0d7cef895e766ce7fbd6198519239e839d7650b7a654951a267034c0115"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "445b648266c321b8a8e2a9189d6f0c8f193a2741c890302d1dda3f5c2ede00a7"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "4fccf07488477e34089ffc2b6fff107975fc08c90bae9ae5d08b30244476e597"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "810b6b06d6381ac4fa830ae815fc801ce1958d70a32c250d148b1e1c3f9de693"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "2c2e857891194fafb155b5c0555d3eff6de1792c72fe287097ad8aece96c228b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6fe9c343db0c5abf50fb43ba5a18eea33e1fbac41a9ed61efd3211fa45920855"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1c02b1956b127730825075a488cf802339f955ab6eba95ba25786c7a366ca964"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7f53b315580609c3da12ae3338d201003eb54dfaf5dd6e1d4dafb168c8bda1f5"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "b48425ffebfd1bb954a6c33bab91e938eaa4559d97361c006b22b3da6717f814"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "9c5a8362cfa0fdc8c07216a1c89bb73dbc615eeda96cd7d5ef1e4b62fdfed2df"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "03c31dadebeddd79891e6cb1d4ce146b382ca848e1fca30d4fb0008e361a565d"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "91cfc2f817b141f65bf8e94ae6b5c2c191dfa005e53f80998ad5cdbe552a76b8"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7d75b45e1bc218146375446fa380d0c9235cef92993423fdd70dd208dc2d53d5"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "97860114e0a95f00362d46fcdfce256a90085f57428143907830d404887cbc1a"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "21843e75802603fc737c7599bbd6550e85d77e882e9b0aa5df279ae1270392d6"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "bba5d5b62fc2c447c3c7abacb416e378a6bf5b8ce47f97133c7ce4d93888afe4"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "415fdd5369d81f64f6cf24fcb4f8c819e4d1d35fa843415f57e32304f5ad27cb"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3d18c5e20f516a81cc5ffb69c1449235ca632d9a31abf31158266a48a0aa03cb"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "fd74b1f2a8d333712b05eebc675fe50d0f603d1242ab5434eac95df44ba438d7"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "cf7f77758b79b463a142ca6caa6780fa15bb3f6436be6b2ccf12be03f1bfee84"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "3da6d6a2d659406a1a4f764c6c756720086280f78950d22637c66501697d2bc5"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "7fd9d9561750943412788fab95afd4bf5c64f73d89c1fd70e393de82f4147731"
metafile = true

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "66409514260315948f6b974008a22417db948dfe931c56df4e167301a2ee35ab"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "4023849811ea2ac8f66f2345047d39de650e329d8ae3c4be79c38f8cf4153e61"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "9274cfd70ae43c57009a1abec9c70054c7abab92dd2572acd66104c7f89d4355"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "e0676e443d9c0a16b0fc3f730143ef3a6e9ed02ba04ead7648575f1bc4795517"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "68a78e168ace3dd6056d9682fb30c33b363bec353453fa348fc2e518913ea0f5"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "fa20fdf3e53f602ca389d6211a190883e03bf50d691f7e7546af91927845e497"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "6da787becbc2ce731bf585b4bb02d8fddaa68e49dcf507733cc2aad0e79d4240"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "53d2199ebe4fc547b09cfa951c9612272e9bc146ba7929b82082c202ccb954f8"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "524ec56fcbda8803262391056f1958d367b017587bf97f2202a5d296f165021d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "7aef5e79f23aab4f77472379cfbe508f9b8a7fe18b311c9ec54e7c8752347fa6"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "a237aaba875ec361e621c5fbc6c10d1b6eee20fcdb2d38619c8cf13b62f318aa"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "7de04f88c4af997e6cd712ee3719c8412d89d7ac91f93c06d4e7922600af0279"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "198fcfb73cc9f2d32a75ca457d63ea8d995c66095df781aea0d3a79ba8e2bd02"
metafile = true
