hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "576f429a1be6eaca9eccc14adc28885a077142c0d0dbb62b182c1790bc8fa497"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "c704558740d92fc998a5d17fac0fe9c7710865550842b2308fdc75eafe4adc25"

[[files]]
file = "config/modmenu.json"
hash = "8b36ea8af428943d85a7594b9d2e8144be3f77bab05a150e8b2db4dbe8f25a37"

[[files]]
file = "config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "8b36ea8af428943d85a7594b9d2e8144be3f77bab05a150e8b2db4dbe8f25a37"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "88a4b9df8024bfb56294ee78b9c85e569f35c66cc9f14e88284512335a3638d2"

[[files]]
file = "mods/animatica.pw.toml"
hash = "23b3d1ad268ba3a1eaaea01b74ff3dd5ae9123c0cb0ba29ec85c98b0e6eadfba"
metafile = true

[[files]]
file = "mods/bettergrass.pw.toml"
hash = "fad608cbcee132e75f28e6633275800760c0b07fed91553f20aa43772e924890"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "24b0177dacb547321d83487699e13bf6f6fa004c0d8199dbcc0867b2c21097ee"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "bbd8863b1b4d77d30bb31310d4e549a4f3f28b580fdf76f742d7b4c1f2f79f71"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "cf821651d19efbd89824d89972e592723b1e9e2c5dee3495e9366cfe904e27ec"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "705bc0827aed5af8d86de5b7aa7fdd7cadd647075635bad690e0c54d7f467425"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "550a7e3c0455588bf466582065b574ee75e2ad2e4d6e0f566516c46e75d17a85"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "867f8e4be9bc139a517dbcf55aefc2938c5e461640bd08024ec4716fce068025"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "05ebc0d7cef895e766ce7fbd6198519239e839d7650b7a654951a267034c0115"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "445b648266c321b8a8e2a9189d6f0c8f193a2741c890302d1dda3f5c2ede00a7"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "4fccf07488477e34089ffc2b6fff107975fc08c90bae9ae5d08b30244476e597"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "810b6b06d6381ac4fa830ae815fc801ce1958d70a32c250d148b1e1c3f9de693"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "2c2e857891194fafb155b5c0555d3eff6de1792c72fe287097ad8aece96c228b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e69de5b02d660ccff49dab30345a63dee5e5fafd80ff22cff9846b6bf4eb7a39"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d0a11cc1a951367a0840b447801ca71e41a1f81dd99fb7f3e41a1e12c3dc6233"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "216006067453efa7a750f0d8bac6ea84c503b79e40aba32bd77c9edd183ec232"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "b48425ffebfd1bb954a6c33bab91e938eaa4559d97361c006b22b3da6717f814"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "9c5a8362cfa0fdc8c07216a1c89bb73dbc615eeda96cd7d5ef1e4b62fdfed2df"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "03c31dadebeddd79891e6cb1d4ce146b382ca848e1fca30d4fb0008e361a565d"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "91cfc2f817b141f65bf8e94ae6b5c2c191dfa005e53f80998ad5cdbe552a76b8"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "794718b95c11183285224342ac13f1fd7f1440ae17ce13df7b7e2fe8da179dd5"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e49f0ab01766eff703f7ebfec0cbe75176d76a78af7679e821de7e3894ee027e"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "21843e75802603fc737c7599bbd6550e85d77e882e9b0aa5df279ae1270392d6"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "018ff635f48fe28581fa6f2f8221c9a17b135f4e0ceb4bedece6d5d6cb5e063b"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "415fdd5369d81f64f6cf24fcb4f8c819e4d1d35fa843415f57e32304f5ad27cb"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3d18c5e20f516a81cc5ffb69c1449235ca632d9a31abf31158266a48a0aa03cb"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "fd74b1f2a8d333712b05eebc675fe50d0f603d1242ab5434eac95df44ba438d7"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "cf7f77758b79b463a142ca6caa6780fa15bb3f6436be6b2ccf12be03f1bfee84"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "3da6d6a2d659406a1a4f764c6c756720086280f78950d22637c66501697d2bc5"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "b2484dbeb2eb2fbdefa2497f2061c98438aab667d90e802194d23db1b1c51931"
metafile = true

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "45422b61170ac8e900b21b2bfff8f77f157f2c61cdcba2c181018253d939d056"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "4023849811ea2ac8f66f2345047d39de650e329d8ae3c4be79c38f8cf4153e61"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "9274cfd70ae43c57009a1abec9c70054c7abab92dd2572acd66104c7f89d4355"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "e0676e443d9c0a16b0fc3f730143ef3a6e9ed02ba04ead7648575f1bc4795517"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "68a78e168ace3dd6056d9682fb30c33b363bec353453fa348fc2e518913ea0f5"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "fa20fdf3e53f602ca389d6211a190883e03bf50d691f7e7546af91927845e497"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "6da787becbc2ce731bf585b4bb02d8fddaa68e49dcf507733cc2aad0e79d4240"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "431013d6c417a775b7481a68560da3c746d59e1ce757473c084948804f7acf4a"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "524ec56fcbda8803262391056f1958d367b017587bf97f2202a5d296f165021d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "7aef5e79f23aab4f77472379cfbe508f9b8a7fe18b311c9ec54e7c8752347fa6"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "a237aaba875ec361e621c5fbc6c10d1b6eee20fcdb2d38619c8cf13b62f318aa"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "f21a25d262460c7cfe0cd1c66ab2ca78563766d0babd03806338430bf9373e86"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "6de8e1fe37adeecd85b5f7858b0d47e69cb872a67d6382eb459a4f167d92eafa"
metafile = true
