hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "745da5107ecb302f0bdcc3871db964a105f50745730c59882c0e7c3bfbbfe9b0"

[[files]]
file = "config/midnightlib.json"
hash = "8bffacf0777bdc9e35022109e9580583d40fcaa05f0abfed1bf32220a5b39ab3"

[[files]]
file = "config/modmenu.json"
hash = "8ea79f86612f7167b3dfb547adddb6a838c4f44d6fc1459273d9db7bdf37ebd8"

[[files]]
file = "config/slightguimodifications/cts.groovy"
hash = "9e5a27686f70c354edf2be39c5bdf218c691a8766d622d288edeb9913f1969ed"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "94f7fc7719381bc6e474b6df30840d2aab0e8c4ed80d2f6191cf1b5b7d92be3f"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "99ecb0cc231f75abd0e0cfb6ebcfae0fa407c1dab9956587c1792d45e715b6c7"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/yosbr/config/colormatic.properties"
hash = "e0dfdbd6f39f1fc0a92b3fd18c981d20953e681f56eec736038f8940afa20d72"

[[files]]
file = "config/yosbr/config/cullleaves.json"
hash = "6ba25b17d218c13aecd7773fb0dd9f01783997854cc7123891e526e82490662e"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "d755fffa95330f9083560f4a9f197c01bd18acccf5f262e506b4d80a4809e6bf"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "67a031c7e7c187bf7b93db9d7419e0c9b01fefecaf1e54f408b16fb9d7fc57c0"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "2744ebcd3589f1124ab556b12e3d73b878fe89901789fdf18787cca12e6a6c0b"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "1a0c50101df35b82a3015882331c4b1b76bec59a05c25cac50bff3547b891f25"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "8bffacf0777bdc9e35022109e9580583d40fcaa05f0abfed1bf32220a5b39ab3"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "8ea79f86612f7167b3dfb547adddb6a838c4f44d6fc1459273d9db7bdf37ebd8"

[[files]]
file = "config/yosbr/config/slightguimodifications/config.json5"
hash = "7da931e9b7389034de203f2719b99ab74ab8e500a898ad5d563d64f13c501120"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "120fa73cd1bc43ef382877ba62fc193254903aa60695ec712e74da61b9e6f623"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "7e597a01436a7da6f68b3456848ad6b6a000c0efad3e5c04d75249b1df170b18"

[[files]]
file = "config/yosbr/options.txt"
hash = "040239c0e00a49830917b1b2e2332a393b7d90f5366b5e1efd846a51df8b815d"

[[files]]
file = "mods/advancementinfo.toml"
hash = "efc4a3d5a04408d86d7145d8acf9bee604ad0a0136afee84f78d0ba16d72a2d4"
metafile = true

[[files]]
file = "mods/animatica.toml"
hash = "5f86bb4e54b5d5a10be7ed909c0b106f6bb246578c9b76aa0284f1a99e9d67b1"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "e9cca5bbca986eba920e6e5ff1c81f81def15590fde9810a956f6b8c75393aae"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "0cb15ecf2dbcd17db7d220f4dea657b79419d0c1dbab7a26b4d569d4752a1981"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
hash = "93dc278b289483148e3474c88243f8fa640a1be7934bd70bb4dbcb9619a1711f"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "5d910a686f63efcc856b2e8fd694cc1d95311107624cebbe82d37e3adad2eb23"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "cbce67550c67978ca8fbc4bbbb5ec5ce849155e34f6bdd1c407f882801a7609c"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
hash = "3c329350a1ade79fa329aa932188659dc361d4917a0fcb07159b5eeb240f97f2"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "8085a1c52ea30800552f6351d14a1a435e5aa55f4853733aa1f710a41af2ac80"
metafile = true

[[files]]
file = "mods/colormatic.toml"
hash = "28ced5e2d2022c47104ce91416756873d16d458f30b7184757f7c9518116bd1f"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
hash = "2aa0ee934a5fd927a9c22df206bed48398079eda3a8e6ce549e97adae070d060"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "0563271b36703c2594ac9b3c7382b614f4396ec664f12109a79bcffb95824143"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "9303f6ef825ac9dac488d37017ed6ef9eec0572e0e87133eb4450de4182d7af2"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.toml"
hash = "5a609203ae9f32d5ff7998edd49c50b2ca8d7fe28233664b5621befe87176ee2"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.toml"
hash = "2a1799426d31ac5da9f01cbbd1b611df5b74499ae46d7d1a5e2e4f805db1570c"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "a3c3d4f35494103eb96d62ad1e63932d4407c90b7878fdb1d2d1f75e26da1ce4"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.toml"
hash = "15122ef9ddae952b8b99d79556b1dc726f9a9c9c09a57ba03de8bad3ff4a4ab4"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "e5d58b089848f10d56194c507735ce7255230cc0da4e641737eb10f19b55b9d3"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "f3657399363cb42c00dce1256e320a49ca6a3c5465d20ae0642fbd70ebdee1f4"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "2e585b6ce11bc8f187a3178debba7086dfebdd37c667aee1dd46d627ab94e083"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "dcabf5541393b6b96d4f45a5638cb7d41ea7a40b0d8ef03129e8dc78eba984bd"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
hash = "765dda5cfe882d95c502139428b69867798ee1be80f15b26ed4c972fa80451ee"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "0e1a6f22d9e5538561be2f2a8bfd4998704124266c2af98d23e9adc67df5f9d9"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "63fd94202dbec36cd058b0cd9b34e3464e4f96b3262b4013e5456a269809ddfd"
metafile = true

[[files]]
file = "mods/irisshaders.toml"
hash = "0dbe6d7faaa4fd2768dd4e3de1935bef6b49f1e1ae44649e35e7c8f3ed93431c"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "8cb021b388cdac45c85fd6559ebe7f98f8db1ee93fcd5641816414808107296e"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "9b6ae1f491e5db99c57f0fca6da4db2bd999bf8bda287cf60cf861dd3d18fa49"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "2b0756538b98e29702e74d8f194b70eb8c472fa086e5a3084d903347cef4d623"
metafile = true

[[files]]
file = "mods/language-reload.toml"
hash = "4dfbc6d2a8716a65c5ff3418f7af899bb1515c9451a18c98d19c03be757701e3"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "d29c81118c71783f1a833ec2b5b5e2be98d1bfce3652026b24161cb27288e3be"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "74d84f7a4e66e0a93bd53e7a8d8962abf1be37ae4873d33f2c9f907c74468c68"
metafile = true

[[files]]
file = "mods/littletweaks.toml"
hash = "e9bc92a4aa19f32a6d42b1470ffa56546652a3abde8dafaaddac12473418619e"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "3af260ca28e4c1c1a56bbe496a43ac757b49123f33468131d3589df4c8591033"
metafile = true

[[files]]
file = "mods/more-chat-history.toml"
hash = "62c18f83be5eb3a91395b9466418065271a56ea4df82004066c1dd0c6f7729bf"
metafile = true

[[files]]
file = "mods/no-fade.toml"
hash = "a40d9644e1ae0e994374d1dcfa2ed19cddd244cff4f2d372e3ab63690bd5b831"
metafile = true

[[files]]
file = "mods/no-potion-offset.toml"
hash = "497343aea45b8f9c81a059f3c2724c2aef668cf05104ebac898fa0461ba98349"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "ff0adf938e6d4bf6076a3ceb95a2fd0b89332621f505c88c94a7d703f507b04b"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "f145d86214942cb703c09ad638e368be9a2734184d5d0f7280f35b0fd06e41c8"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
hash = "938bae2eba4070fa5b35631561bc6978ff28c2fed54af8dd3f45c1188931ce44"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
hash = "5b33de3c55d5c60d41ac57d72b7697b6e6ad8795de481895b3f0d11e2e0d974a"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "50643f42ce49a49dab5a766245eed97c9acb6e4c84cd59524a10d13b0d2092f6"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "d6b54a334333066b499aa84b1ac648a1dedf7997caac97419c7a0c7d9216d482"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "44ced0414da499770b40c515af4956025fa623a06d786e1c6aaca670d01c123f"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
hash = "a68996a8acfc3d77101278e0fe5ec9c908ca5a077faeb8974ca7e896f1b65fb0"
metafile = true

[[files]]
file = "mods/wi-zoom.toml"
hash = "c45b7f814c25bc2c9804fbd86f9b340cdbf81eaf82833e73f0778e2c41fd208d"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "25ba1f543d497256054d05bbbab6e0c4f5aa9796cd53191d4b381297fd98c81d"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "66107bbc5a698d094f0dd546d5cfe2dcd049a32c4dd79b2bfc6d2df5772de637"
