hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "861e09447ba6c92f25522d7217a67ebb65deb9e99de8b871c9b8d705a778e47d"

[[files]]
file = "config/midnightlib.json"
hash = "8bffacf0777bdc9e35022109e9580583d40fcaa05f0abfed1bf32220a5b39ab3"

[[files]]
file = "config/modmenu.json"
hash = "7e94b21de48ce733607b86c3c60f7297a066e3d6141f27fc6de994e2fe5d46db"

[[files]]
file = "config/slightguimodifications/cts.groovy"
hash = "337179a4dbb392aa432355ed3fbd02bfb7b82c8d2175fc4fadac7706797dd957"

[[files]]
file = "config/sodium-mixins.properties"
hash = "051558518a6f3350fadb1546346d937e7f78f69834a075bf91b59921f151cc26"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "67e294546dd7b0c9e0490574590273283da61a4363c68c9a4dcc86e4ba4b4195"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "94f7fc7719381bc6e474b6df30840d2aab0e8c4ed80d2f6191cf1b5b7d92be3f"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "99ecb0cc231f75abd0e0cfb6ebcfae0fa407c1dab9956587c1792d45e715b6c7"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/yosbr/config/colormatic.properties"
hash = "e0dfdbd6f39f1fc0a92b3fd18c981d20953e681f56eec736038f8940afa20d72"

[[files]]
file = "config/yosbr/config/cullleaves.json"
hash = "6ba25b17d218c13aecd7773fb0dd9f01783997854cc7123891e526e82490662e"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "d755fffa95330f9083560f4a9f197c01bd18acccf5f262e506b4d80a4809e6bf"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "05b7909baff3cd0087fe07937c86a7fede1a904ace562b8df5116eca50f1f1e4"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "2744ebcd3589f1124ab556b12e3d73b878fe89901789fdf18787cca12e6a6c0b"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "1a0c50101df35b82a3015882331c4b1b76bec59a05c25cac50bff3547b891f25"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "8bffacf0777bdc9e35022109e9580583d40fcaa05f0abfed1bf32220a5b39ab3"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "7e94b21de48ce733607b86c3c60f7297a066e3d6141f27fc6de994e2fe5d46db"

[[files]]
file = "config/yosbr/config/slightguimodifications/config.json5"
hash = "7da931e9b7389034de203f2719b99ab74ab8e500a898ad5d563d64f13c501120"

[[files]]
file = "config/yosbr/config/sodium-mixins.properties"
hash = "051558518a6f3350fadb1546346d937e7f78f69834a075bf91b59921f151cc26"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "d7db2ecda246d459f1d65c2c60d3581b8d5c02242a957d0c66b2e17a51d86af0"

[[files]]
file = "config/yosbr/options.txt"
hash = "040239c0e00a49830917b1b2e2332a393b7d90f5366b5e1efd846a51df8b815d"

[[files]]
file = "mods/advancementinfo.toml"
hash = "efc4a3d5a04408d86d7145d8acf9bee604ad0a0136afee84f78d0ba16d72a2d4"
metafile = true

[[files]]
file = "mods/animatica.toml"
hash = "97465f9cd297279d178451f7667b1118e127822c7c92587aa2cb7908841b58b2"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "e9cca5bbca986eba920e6e5ff1c81f81def15590fde9810a956f6b8c75393aae"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "0a08fd6ef2b5d07a11e308406bed1c215fdd4d3d5dbec5bb0f031c62a3dbfe94"
metafile = true

[[files]]
file = "mods/arrp.toml"
hash = "22203e5764097d5d7e17e6082417f8b69ba3af34336e4d9406f9389266523de5"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
hash = "93dc278b289483148e3474c88243f8fa640a1be7934bd70bb4dbcb9619a1711f"
metafile = true

[[files]]
file = "mods/borderless-mining.toml"
hash = "3b82c6c39fd621dc11e2e8a1fc1ca84cb40978d89685b5f9604dfa2e24d97f09"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "5d910a686f63efcc856b2e8fd694cc1d95311107624cebbe82d37e3adad2eb23"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "15f1f9a5754582a6e626a72fa35683f6b46b623251c0aec0f8aafd7fdd340fe7"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
hash = "3c329350a1ade79fa329aa932188659dc361d4917a0fcb07159b5eeb240f97f2"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "c8b792cdc006780b256e1a1a05fca91cc32542547d9805ece9b48eff78e5b2d6"
metafile = true

[[files]]
file = "mods/colormatic.toml"
hash = "28ced5e2d2022c47104ce91416756873d16d458f30b7184757f7c9518116bd1f"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
hash = "2aa0ee934a5fd927a9c22df206bed48398079eda3a8e6ce549e97adae070d060"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "085fe63a5eb184f27fa75481047de205138e2b23951ea319ce17b2edfb7a5fd4"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "9303f6ef825ac9dac488d37017ed6ef9eec0572e0e87133eb4450de4182d7af2"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.toml"
hash = "5a609203ae9f32d5ff7998edd49c50b2ca8d7fe28233664b5621befe87176ee2"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.toml"
hash = "2a1799426d31ac5da9f01cbbd1b611df5b74499ae46d7d1a5e2e4f805db1570c"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "a3c3d4f35494103eb96d62ad1e63932d4407c90b7878fdb1d2d1f75e26da1ce4"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.toml"
hash = "15122ef9ddae952b8b99d79556b1dc726f9a9c9c09a57ba03de8bad3ff4a4ab4"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "e5d58b089848f10d56194c507735ce7255230cc0da4e641737eb10f19b55b9d3"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "a81b96c7081399790a24e8d5cf38ce3c9b5528755fb6bde8b435625fe68f89d2"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "7f4996fc7ac9367f157cbd94ac9b4601225279d457df78f66941a157e8592eb0"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "dcabf5541393b6b96d4f45a5638cb7d41ea7a40b0d8ef03129e8dc78eba984bd"
metafile = true

[[files]]
file = "mods/fastopenlinksandfolders.toml"
hash = "c9f9623a4f5a3dd5edecf5450929d417ac97a8e88411a18037fd3ca96d2d1ef3"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
hash = "765dda5cfe882d95c502139428b69867798ee1be80f15b26ed4c972fa80451ee"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "0e1a6f22d9e5538561be2f2a8bfd4998704124266c2af98d23e9adc67df5f9d9"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "63fd94202dbec36cd058b0cd9b34e3464e4f96b3262b4013e5456a269809ddfd"
metafile = true

[[files]]
file = "mods/irisshaders.toml"
hash = "444faba93ab74fd26cfe2437f66442e8d1d5492030c62aa578b4a4195d9099c1"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "680733c8f73fd5f5e1998124bdca39063713af261e9b7c2248478d0594954f4a"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "220ab04d4b6e98672a143f8761e6044ecdd6190036e1248638e940d46fcb7c97"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "2b0756538b98e29702e74d8f194b70eb8c472fa086e5a3084d903347cef4d623"
metafile = true

[[files]]
file = "mods/language-reload.toml"
hash = "4dfbc6d2a8716a65c5ff3418f7af899bb1515c9451a18c98d19c03be757701e3"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "d29c81118c71783f1a833ec2b5b5e2be98d1bfce3652026b24161cb27288e3be"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "74d84f7a4e66e0a93bd53e7a8d8962abf1be37ae4873d33f2c9f907c74468c68"
metafile = true

[[files]]
file = "mods/littletweaks.toml"
hash = "e9bc92a4aa19f32a6d42b1470ffa56546652a3abde8dafaaddac12473418619e"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "3af260ca28e4c1c1a56bbe496a43ac757b49123f33468131d3589df4c8591033"
metafile = true

[[files]]
file = "mods/more-chat-history.toml"
hash = "62c18f83be5eb3a91395b9466418065271a56ea4df82004066c1dd0c6f7729bf"
metafile = true

[[files]]
file = "mods/no-fade.toml"
hash = "a40d9644e1ae0e994374d1dcfa2ed19cddd244cff4f2d372e3ab63690bd5b831"
metafile = true

[[files]]
file = "mods/no-potion-offset.toml"
hash = "497343aea45b8f9c81a059f3c2724c2aef668cf05104ebac898fa0461ba98349"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "8b9781cc92550a3518da58925f15e8f48e5664196a7aae7d41a24c7e5a229668"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "f145d86214942cb703c09ad638e368be9a2734184d5d0f7280f35b0fd06e41c8"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
hash = "fca0ababf5eccca1dae2a19d671157fc69b98174f6f44962983c8ffd3253c3d7"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
hash = "7a626545d40c1dc1f22fec009b47f640de21df9aeca937ad0c83e173082e5f67"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "50643f42ce49a49dab5a766245eed97c9acb6e4c84cd59524a10d13b0d2092f6"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "75e82d1342fc64d64d70bc53291e49a8398a540e02994f2102fd5810107e107e"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "7cb8a854f154a0461d2c7fe759160fa19b2f6407f8b2494f8b64b9621f7f579f"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
hash = "a68996a8acfc3d77101278e0fe5ec9c908ca5a077faeb8974ca7e896f1b65fb0"
metafile = true

[[files]]
file = "mods/wi-zoom.toml"
hash = "c45b7f814c25bc2c9804fbd86f9b340cdbf81eaf82833e73f0778e2c41fd208d"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "25ba1f543d497256054d05bbbab6e0c4f5aa9796cd53191d4b381297fd98c81d"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "d405e2542f970be8a1c6b9a57e491c41e358f5e958d09ea38202387b371760a9"
