hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "745da5107ecb302f0bdcc3871db964a105f50745730c59882c0e7c3bfbbfe9b0"

[[files]]
file = "config/midnightlib.json"
hash = "8bffacf0777bdc9e35022109e9580583d40fcaa05f0abfed1bf32220a5b39ab3"

[[files]]
file = "config/slightguimodifications/cts.groovy"
hash = "0347867062ec4ddbb97a4826e5808a13c661f7ab2ba017e86b3d385aa954e81b"

[[files]]
file = "config/sodium-mixins.properties"
hash = "051558518a6f3350fadb1546346d937e7f78f69834a075bf91b59921f151cc26"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "94f7fc7719381bc6e474b6df30840d2aab0e8c4ed80d2f6191cf1b5b7d92be3f"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "99ecb0cc231f75abd0e0cfb6ebcfae0fa407c1dab9956587c1792d45e715b6c7"

[[files]]
file = "config/yosbr/config/colormatic.properties"
hash = "e0dfdbd6f39f1fc0a92b3fd18c981d20953e681f56eec736038f8940afa20d72"

[[files]]
file = "config/yosbr/config/cullleaves.json"
hash = "6ba25b17d218c13aecd7773fb0dd9f01783997854cc7123891e526e82490662e"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "d755fffa95330f9083560f4a9f197c01bd18acccf5f262e506b4d80a4809e6bf"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "67a031c7e7c187bf7b93db9d7419e0c9b01fefecaf1e54f408b16fb9d7fc57c0"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "2744ebcd3589f1124ab556b12e3d73b878fe89901789fdf18787cca12e6a6c0b"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "1a0c50101df35b82a3015882331c4b1b76bec59a05c25cac50bff3547b891f25"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "363188965154bf65b2151d6695a35c2588ae7b185a4a761e5a1d6b084259d0b2"

[[files]]
file = "config/yosbr/config/slightguimodifications/config.json5"
hash = "7da931e9b7389034de203f2719b99ab74ab8e500a898ad5d563d64f13c501120"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "120fa73cd1bc43ef382877ba62fc193254903aa60695ec712e74da61b9e6f623"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "7e597a01436a7da6f68b3456848ad6b6a000c0efad3e5c04d75249b1df170b18"

[[files]]
file = "config/yosbr/options.txt"
hash = "040239c0e00a49830917b1b2e2332a393b7d90f5366b5e1efd846a51df8b815d"

[[files]]
file = "mods/advancementinfo.toml"
hash = "6a8810f580393762531fe79c4af28bf577040f17450e758dfebb1c43cbb5d525"
metafile = true

[[files]]
file = "mods/animatica.toml"
hash = "b9924f833272e1afc0d7214f0a4b2301b3391ae98d4da4a94a315a15de9ecd3a"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "5db5823578bbc8f2d1389439e42d13fe2254b2833f5784d07d833b806df2fc4c"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "c1ac0ea5003f230698651f3ea3a3a1d53e87de3add18c41409bf29d7f1d53f3a"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
hash = "305f28a2361765477b348ac3d034053808bce0ab2989873a1ddd9c35ce455b45"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "ae4188fd623361d5dec78a2768324b6d93742e9e2d53d84a3d9366c511cbf1ca"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "ce8975eae119cef91ea2b1784eb91bfc17f92fb9d477f4f85b82cab7e3d71643"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
hash = "6f9c3f657c6e3ef033d0e778096004ba4554b0db609dc80338590b3970e8daa3"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "1bbb7759542ccebcf1d5157dd889050c371277b8d26f7c1b9b18f0968ad7c33d"
metafile = true

[[files]]
file = "mods/colormatic.toml"
hash = "8ce725c32e1c950da3f7f8982b3aec818c71a6d203716d8a0aca78fb01f69987"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
hash = "dac12eae85ffde6cd4efc4bba7da0c9059e0d6cc52c5a9ae8ce6c5a312c275d0"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "dfa81d8b8c5e9090e43cc007bf902ec2a1dbb44734f3f48a37a66d823074942a"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "b1c2ad054923a66fef20c205f4e270d366549daf099a3cbecdf995f6ad332c94"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.toml"
hash = "993aebad8c508712972999680cb2356bd3e435602535214f81ad2f2d8448fc8d"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.toml"
hash = "a1dcacb03cde9cfd48b0b0e0b8aaa73aa01e83db9eab39534a7c3f4697c28f11"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "0da6ce612463f35b1e5df156d2e2535e5ecd22b263cf506a82928aeaa93929c4"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.toml"
hash = "2e14d066b2e67b3ee7573b364ea50c35c483fd57029079b94369a82f04fc3569"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "729ed8c7252a48b332b7b701eddf9737b6844662fa9d6a442cd2d1d36d41257d"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "76fac2cfd09d5b73e428a698f9ad1fc4e7ed59f807997d848c5bf9a5024a87ac"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "3b55a084c08b2afd69c50bb00a802abc4387ecb1ce3525fe9db36a1ade7fde9c"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "9131713b5dd19789c6d25cf7e10a787e4454f1b9b958b1854746f9d3a72782a8"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
hash = "ef41380ef2612b9d2b0c2aa81e10d13a8116a956f8e67de96c3115619562520c"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "0e1a6f22d9e5538561be2f2a8bfd4998704124266c2af98d23e9adc67df5f9d9"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "7f298bc09aeec405b8cfc2a0c0b2f4df0dfa8ebacb1747a7848b002dcc5264bc"
metafile = true

[[files]]
file = "mods/irisshaders.toml"
hash = "2e964d2fbfe404b4e49147392c84106f0c49ad35fc7032bed186d0ee7737138e"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "1fc81c2fb496ad395c8d81c55b292f2131548d6654fc1201f79d61e1564052cd"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "83cd473f679ee67f828d7660f8c546d04744c7a79a43bfd7c039e73eb3d5e45e"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "d1b7566f8022927583b3a112c30a9867d9d9e7f6736cd06ec30eebbb57fbdc55"
metafile = true

[[files]]
file = "mods/language-reload.toml"
hash = "3022ee68bd70f582513f1165cca332b662b477782f363a5c564998c922c82150"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "b47b2d6351087ad346299faff6daca6047870901fa3ce4c9a79bda719db0a74b"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "b68e9befb8f9dff5f8d548c6c2be177b2dcf5f49f5f3b99fe3b31dac9ec91659"
metafile = true

[[files]]
file = "mods/littletweaks.toml"
hash = "66e256d0483ce706769e675498fedf4d7e94edf587944faa58615b86d5c9041b"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "7c761c51deba63b76caffc2d41af96ccae70ef0cbb789db682d3fc7b43994f67"
metafile = true

[[files]]
file = "mods/more-chat-history.toml"
hash = "326923ededc54c81a3630e10afcff8eec27a3a352cea2569d73cd4d338e2f06b"
metafile = true

[[files]]
file = "mods/no-fade.toml"
hash = "00e39f0a666b5418c9e149ec75bc1b6fff68a720efc2669908cec788103dff33"
metafile = true

[[files]]
file = "mods/no-potion-offset.toml"
hash = "3864b5de7c1ea8afaccb95ee351a27e7f5b2dba30b47f385b07b4ff72c1cded4"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "61554b360052d048d2a47a510945a757e2263d19bc72fa239e9b1a5f5ebccd2e"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
hash = "a609236c4f7cbb215561d06fe823c4ef70990f17ecf29509bfc95b4260e1834f"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
hash = "e0dbfb0ae19e329c972716748125ff0722c87eb4c63f3b4b7dda28361a6cf83d"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "d02b56170076cc508fe31ff0e4d36b4576cb0ae7cf2c008b273cd64c34787408"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "0a037711955c1f0108d195683e2d8018f9193270e86a61d2e5cd2d874cae7000"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
hash = "3ef460e68b01f02bfddc1d3b4c5edf6aec9470a3c7ebdf577ad4e26668c3485e"
metafile = true

[[files]]
file = "mods/wi-zoom.toml"
hash = "acc7a3d78125c57ebef774099e7dadae8b9249032b030c598569377f10fe4384"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "218b2b38862091f96e1db0ee7580c6f9cd5e8f008f88e4fe00016c6dea1065b3"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "095546774e35e6466c659a2236ce497cb7c46465055c699abf100a33b334a963"
