hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "c0ea016e992b3093ebf05ecbb099361b0c11e8cc4dc53c81aa959b0a5fc42381"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "84b82b6a4610dcf0f2992d3b86a3abfb8748c54ada513020bae4154581f012ea"

[[files]]
file = "config/midnightlib.json"
hash = "d742dae2f8d0881d6770e189137d0c08513fee5608f26d484b6912845b874d82"

[[files]]
file = "config/modmenu.json"
hash = "cf0aaef402dc0b2be5b09f9f9a99f81c9ff64f585e077b0fdad7655b13a6055c"

[[files]]
file = "config/slightguimodifications/cts.groovy"
hash = "0ae5f8f503210afc554ff9feba7c7a54fddedc6598f57412612ce51472773139"

[[files]]
file = "config/sodium-mixins.properties"
hash = "051558518a6f3350fadb1546346d937e7f78f69834a075bf91b59921f151cc26"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "94f7fc7719381bc6e474b6df30840d2aab0e8c4ed80d2f6191cf1b5b7d92be3f"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "99ecb0cc231f75abd0e0cfb6ebcfae0fa407c1dab9956587c1792d45e715b6c7"

[[files]]
file = "config/yosbr/config/colormatic.properties"
hash = "e0dfdbd6f39f1fc0a92b3fd18c981d20953e681f56eec736038f8940afa20d72"

[[files]]
file = "config/yosbr/config/cullleaves.json"
hash = "6ba25b17d218c13aecd7773fb0dd9f01783997854cc7123891e526e82490662e"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "d755fffa95330f9083560f4a9f197c01bd18acccf5f262e506b4d80a4809e6bf"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "67a031c7e7c187bf7b93db9d7419e0c9b01fefecaf1e54f408b16fb9d7fc57c0"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "2744ebcd3589f1124ab556b12e3d73b878fe89901789fdf18787cca12e6a6c0b"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "1a0c50101df35b82a3015882331c4b1b76bec59a05c25cac50bff3547b891f25"

[[files]]
file = "config/yosbr/config/slightguimodifications/config.json5"
hash = "c44249c87c48216b9ce39bd233b88e2a5e901fb7589b54cee79ac566bcb0c018"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "120fa73cd1bc43ef382877ba62fc193254903aa60695ec712e74da61b9e6f623"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "7e597a01436a7da6f68b3456848ad6b6a000c0efad3e5c04d75249b1df170b18"

[[files]]
file = "config/yosbr/options.txt"
hash = "ef7dc96d24f915a87d55e51748a4c06a34bf7a65114e7e7d67f6e1ed2a2a4d7e"

[[files]]
file = "mods/advancementinfo.toml"
hash = "4bdd914cc09497cbfa0122dab0f888f4bfd8d144a394db1746a592c95667fba7"
metafile = true

[[files]]
file = "mods/animatica.toml"
hash = "b9924f833272e1afc0d7214f0a4b2301b3391ae98d4da4a94a315a15de9ecd3a"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "5db5823578bbc8f2d1389439e42d13fe2254b2833f5784d07d833b806df2fc4c"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "2f084a168e35bc5a46a9b4d60401ffcb4ab228a61bfc8f7a651dc5724a285b76"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
hash = "305f28a2361765477b348ac3d034053808bce0ab2989873a1ddd9c35ce455b45"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "3adc9339abe9872d3d0a7b2098f7efd1679203c204d06f4c34488a488a3d8215"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "8fe663f39df5542c3777669c1f19f128298a520bce6c41d90bbca0d4eff2e015"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
hash = "6f9c3f657c6e3ef033d0e778096004ba4554b0db609dc80338590b3970e8daa3"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "94c221982b03971e906ac09835fae62e95acc7341aaf549cec289ae9f28f15ca"
metafile = true

[[files]]
file = "mods/colormatic.toml"
hash = "ed3b4fe8523e09ea329c0c25d11625cc025320feebd8137b1547ef6e9360f826"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
hash = "dac12eae85ffde6cd4efc4bba7da0c9059e0d6cc52c5a9ae8ce6c5a312c275d0"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "d24baa89c8049503e02ab41c7318af6367789dbd9b64128483dada9a7161a3ad"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "8276d048a71d2b7f84c52b946db639e832f960a1a15a7104f609c167850da84d"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.toml"
hash = "993aebad8c508712972999680cb2356bd3e435602535214f81ad2f2d8448fc8d"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.toml"
hash = "a1dcacb03cde9cfd48b0b0e0b8aaa73aa01e83db9eab39534a7c3f4697c28f11"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "0da6ce612463f35b1e5df156d2e2535e5ecd22b263cf506a82928aeaa93929c4"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.toml"
hash = "2e14d066b2e67b3ee7573b364ea50c35c483fd57029079b94369a82f04fc3569"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "729ed8c7252a48b332b7b701eddf9737b6844662fa9d6a442cd2d1d36d41257d"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "b021631b3c9eb2df67a922cf29afbfc01616cd86b1eb2a1f489930d8a478c6b1"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "3b55a084c08b2afd69c50bb00a802abc4387ecb1ce3525fe9db36a1ade7fde9c"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "9131713b5dd19789c6d25cf7e10a787e4454f1b9b958b1854746f9d3a72782a8"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
hash = "ef41380ef2612b9d2b0c2aa81e10d13a8116a956f8e67de96c3115619562520c"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "0e1a6f22d9e5538561be2f2a8bfd4998704124266c2af98d23e9adc67df5f9d9"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "7f298bc09aeec405b8cfc2a0c0b2f4df0dfa8ebacb1747a7848b002dcc5264bc"
metafile = true

[[files]]
file = "mods/irisshaders.toml"
hash = "2e964d2fbfe404b4e49147392c84106f0c49ad35fc7032bed186d0ee7737138e"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "1fc81c2fb496ad395c8d81c55b292f2131548d6654fc1201f79d61e1564052cd"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "83cd473f679ee67f828d7660f8c546d04744c7a79a43bfd7c039e73eb3d5e45e"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "d1b7566f8022927583b3a112c30a9867d9d9e7f6736cd06ec30eebbb57fbdc55"
metafile = true

[[files]]
file = "mods/language-reload.toml"
hash = "769305d6f3ed63fd0e38d1680709180b515149acaed0e07e6a1306ea8c1fa50f"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "b47b2d6351087ad346299faff6daca6047870901fa3ce4c9a79bda719db0a74b"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "290f25ecb199d3010dd5fa5ce6e148577766e0a362129cfa5de6250bfe2702d1"
metafile = true

[[files]]
file = "mods/littletweaks.toml"
hash = "4551539b96ebf730cd9221ec90bcd562340be4fd21921547b5d6ee3ffdfe31fa"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "7c761c51deba63b76caffc2d41af96ccae70ef0cbb789db682d3fc7b43994f67"
metafile = true

[[files]]
file = "mods/more-chat-history.toml"
hash = "326923ededc54c81a3630e10afcff8eec27a3a352cea2569d73cd4d338e2f06b"
metafile = true

[[files]]
file = "mods/no-fade.toml"
hash = "00e39f0a666b5418c9e149ec75bc1b6fff68a720efc2669908cec788103dff33"
metafile = true

[[files]]
file = "mods/no-potion-offset.toml"
hash = "3864b5de7c1ea8afaccb95ee351a27e7f5b2dba30b47f385b07b4ff72c1cded4"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "3755504caf9a9d519bcc358be8208816e6aad2cfd8384ac8cfc249de592582e3"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
hash = "a609236c4f7cbb215561d06fe823c4ef70990f17ecf29509bfc95b4260e1834f"
metafile = true

[[files]]
file = "mods/slight-gui-modifications.toml"
hash = "cc5d7a90874f5022a32a51f00b61513538278b13819321193cf953ba0b7e6cfd"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "d02b56170076cc508fe31ff0e4d36b4576cb0ae7cf2c008b273cd64c34787408"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "0a037711955c1f0108d195683e2d8018f9193270e86a61d2e5cd2d874cae7000"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
hash = "3ef460e68b01f02bfddc1d3b4c5edf6aec9470a3c7ebdf577ad4e26668c3485e"
metafile = true

[[files]]
file = "mods/wi-zoom.toml"
hash = "acc7a3d78125c57ebef774099e7dadae8b9249032b030c598569377f10fe4384"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "218b2b38862091f96e1db0ee7580c6f9cd5e8f008f88e4fe00016c6dea1065b3"
metafile = true
