hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "603e4c376d5595c9aabcd836523e6cbf2fe28bc61edef6b978ffe329bc683806"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/en_us.json"
hash = "83f7850f17c4b4c4f3363e4df2c01eb9cbfcaf184d119cf49c002aa80acba061"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_es.json"
hash = "c6af158e02fca9590d7f688d8a4bad410ccdabcb58787f0bd55c88a6543157f3"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_ve.json"
hash = "5e3660aff589b69711dba7347af9d030c545e76793ac6752111256a97edcc276"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/et_ee.json"
hash = "3ffce5d4f7b2efc2c98816d22871ef45fad912fded5606a9498a9d2f7ac7378a"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/fr_fr.json"
hash = "35b0783789f6735aa8cc8957c6f0bf5640d051bf9c6bdeeed5c508ab78b894e2"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/he_il.json"
hash = "cdf6c2143d6b4a6634c34a427ed849b15c5175c943a2474a5e3bfff6fab5b5da"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/it_it.json"
hash = "49d95b6a84e164b2e8e203e9772a6912ae23fc5c0fada8e26969c8f326f1cc90"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ms_my.json"
hash = "9abad57cb53a894ed4f4b496008e2bab0833f482e8e7f56938a8a62e5638bd6a"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/pl_pl.json"
hash = "4ae15643ae98cc5121547cb787adc92b13161391f1d3572ab5b5bcd3d23acb53"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ro_ro.json"
hash = "f6afd3fa7e12990ed7181c04366bb5ce340a38981a2a54d8a95958b53bd8e296"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ru_ru.json"
hash = "f862137ff1847ac341f3f5f4571d157aa2b27c527d02240e239f64f1d96c6f5e"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/vi_vn.json"
hash = "4e7a3160e2ce7128a3fc583cd0a1cbb874b78eecb314ddbd9a0a209b7d3ee1a6"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_cn.json"
hash = "5ded8a669ee5be80278281c2a03477edc59e207e08f7addedfc144be6cf7dd08"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_tw.json"
hash = "15ca1dbab8723faf3a690cff0bdb0cbb63d20d138975083825c22c7a42643394"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zlm_arab.json"
hash = "9abad57cb53a894ed4f4b496008e2bab0833f482e8e7f56938a8a62e5638bd6a"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "981eba810d5575320ab1da1407c7c6e9a788a8893bd5e67e33897a38f2103ac1"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "a111822a7cc12384c2d7579c99fe36ea34a7faa86857c4edcb7c36f0fa0dbfd4"

[[files]]
file = "config/modmenu.json"
hash = "b7b9cdc1e99bdfd86052e373dc3e0ae87c73760816454b801b09d0cfd7b79604"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "375d545e83e1aabc7700c5f0bea4f7bcf1a19e5e35f9a2155bde2e1c9b0ebc61"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "9a04eaf0053e9b9c3f181ec7ebce30d00edee3f0c42214c6b57668fdcaf3fac2"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/yosbr/options.txt"
hash = "f6a8443f05e331bd996658a4c5e3c9001794aa6a5358a8eea9ecca360f7d63be"

[[files]]
file = "mods/animatica.pw.toml"
hash = "23b3d1ad268ba3a1eaaea01b74ff3dd5ae9123c0cb0ba29ec85c98b0e6eadfba"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "24b0177dacb547321d83487699e13bf6f6fa004c0d8199dbcc0867b2c21097ee"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "35b9793a1e87175951af122d2cc46ca116679667dce4f51288e1ea7c42dc987a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a6016a18dd396dde6e1736449b65d59a06ec8de5c6652f11106980ae60bd7157"
metafile = true

[[files]]
file = "mods/crash_assistant.pw.toml"
hash = "ddc78275a3d99bf49a68e7a22305aa62bf07f68938acc55df8e6fd71a67522cd"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "fa5a32122b8b82bc8a4d16ff435338be6f05b2e554c86642cea02aed4696b755"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "2ff1bb119b7763d711afc341eeb276ec5f693a996317e45228d3309249a694d9"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "194e9bda187343b1f4bf6ced6e224623f758a6d00a13c94acc97b7f443fd91a4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b85324df1857259a3dd811e75755ae6fdecbe6d6efb84c16ba687dd715b0335d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7f53b315580609c3da12ae3338d201003eb54dfaf5dd6e1d4dafb168c8bda1f5"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "1bbacf4844881b1367ff761b3ce1c5cc7ef61eb6514d3a7f41cc994e43cc57da"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "8533ce030f217cfbe8d60ff6dbb76d9697b6589a3918d933e1810359eeefd3b7"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "fc4aa26ffde0be629f71d9bd75ed5dce9172afd43a0f931af4935cf68a318fc5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "ccd09b8f830aa8681444278f7631f4c24a6216c58b96d27ec4d1b258c56e5727"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "1e83fae4a8f5a347dfb12c0b7aada8752fb8bbda33374bc37e468800b84a622f"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "21843e75802603fc737c7599bbd6550e85d77e882e9b0aa5df279ae1270392d6"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "c4daa01ee591308f371c3c179b47ca19205f5472bf328ace5e5da61887a29d0f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "8d64e4327e37f80a8be7c85e50bf2e039a31dea436a0ec23034f1b5d8217ee60"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "3e1a9a1b31ba5f73ee04ca0b9c2c10fdbfa0b2e216f82a659110361f9f813b7a"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "f54736dc5981aaa887c8004e8453919609e5110c13f7c4626625bc0f17582eca"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f5273d4065ede04639ac6796cac0420d6cafed743a930a8f2c70f6f9c37e7bf3"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "cbe531f3cb8cd726ba811e3f8c4803ee7c3485be0ed6fce91908aa80a55c907e"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "2ca4af6d236636e76a9f9aa9b531bbd733b26bbbfaf6a11bb5b87d5f72bc55f2"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "7a804b1e9a763f70121cbc18e3b63f16fb593a486e8dac02c31f55ba138aed7b"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "7c8c6b30bb6ae9a8ea1bd030aa4b4cd7d43b1d0abdfe70ec200174930b70e0a7"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "b0a8f520aaf989acd69739bf1258839f1333a783aba2ea13ca47124964d3effe"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8e1e00b5ed99b8573d1a23bf49d9b8df8c298ddbd4afa31ca34b7656b4075e9c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "899540d668ce17eb5c501237f37ef9f73d6e12c4257a5c92fca8bc77a939a07f"
metafile = true

[[files]]
file = "mods/sspb.pw.toml"
hash = "02b501d90c32539cf2bb25204bbc8d68c227ebed4fbeafc1e8b3c75c5aa075b4"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "b8df62f282af4313eb6ce0c9504ab81c4ef690bf6ccb44b27113310579197707"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "e683db766df47c85f21224eaa0226986b16d0620924efe43df30e9e51e4588b4"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "b7383d421a21538a9c9c700ac3bf268e7f7d7e66013df77a69096cb04a9158c7"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "759c399fdd144681ea7af9715fd8cd67af94534fa52446d7c1609f6b09c5e030"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "392055e7808591f495d3562bfb93247c20aa3b7ed4ccad9cda6af5e02efcf4b5"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "f50e0b9531c33463972ce272a091532fdefac5860a1c83908febd7ced6da25f7"
metafile = true
