name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6939350e3717681e7a07cc124d43543e763af9f2f956cef3bce580f6be90f2cd"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
