name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-alpha.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "170e2127df5cf914cd87b65f85c553100997eadc38bda0e96cfbee1c2b70cb6c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
