name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd08ccaa8f7493c373d8d9c5acd69ad0cfb7e7c0909aa1739958ab2dce6f4863"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
