name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-alpha.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23e353a3db05bf402a2d375e3945081f6ae32a346cc61ea2ac64da3ae997ff22"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
