name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e81d1167136a655a4dc183176982179c0c313356122bb3af56946b23a9269162"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
