name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ee16396f73cbc86743f3c7af89192b70f56ac715a993e2b128dceca9345a01c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
