name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ac6782ea4ce51af3aa5b726d339c1270da994a403e96ef000f118b50345aae4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
