name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36242e430d0d76aae40b3c05a9c400570659b7424f53c78418ff38fa997997c2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
