name = "Fabulously Optimized"
author = "robotkoer"
description = "Improve your graphics and performance with this simple modpack."

[[Resource]]
name = "Don't Clear Chat History"
filename = "DCCH-1.18.x.jar" 
url = "https://cdn.modrinth.com/data/sUbMm93i/versions/2.0+1.17/DCCH-2.0+1.17.jar"

[[Resource]]
filename = "farsight.fabric-1.18-1.9.jar" 
action = "remove"

[[Resource]]
filename = "farsight-fabric-1.19-2.4.jar" 
url = "https://cdn.modrinth.com/data/LXJlc5WJ/versions/TbJQtyy8/holdthatchunk-2.0.1%2B1.19.jar"

[[Resource]]
filename = "farsight-fabric-1.19.4-3.5.jar" 
url = "https://cdn.modrinth.com/data/LXJlc5WJ/versions/TbJQtyy8/holdthatchunk-2.0.1%2B1.19.jar"

[[Resource]]
filename = "farsight-fabric-1.20.1-3.9.jar" 
url = "https://cdn.modrinth.com/data/LXJlc5WJ/versions/TbJQtyy8/holdthatchunk-2.0.1%2B1.19.jar"

[[Resource]]
name = "Mod Menu Helper"
filename = "Mod Menu Helper.zip"
action = "override"

[[File]]
name = "Copy all 3 folders and add Sodium!.url"
action = "remove"

[[File]]
name = "Copy all 3 folders!.url"
action = "remove"
