hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "7a278df1cdbe626dead5c58415f38a0d23df1ef480f6804570166d6e920a1167"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "8c072f22c2492141e7ab445975b41e56a60116f679498748deeaa64a7ef68f47"

[[files]]
file = "config/yosbr/options.txt"
hash = "8ee3d84907824eea9ff0ee1f8d289ab8d5ac97793cde120f630d85f96c63ab65"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "122efb712417e034281b2d1d431026569038f05d86fbf7df3b0f9b66e769d2e0"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "eef3cca5127037fc337391ef49889a03e7102d6c2d1af866dcf007353b52324b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "eefa86fa9a8df6eda5d39d3bbbf53138a44df71a01a24262c27584badea97d79"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "803ff4e47c28c30ff514ec5b3f35509f2e94f51ff649e882386b761235dbd06a"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "e4b230e3eccc42c8b650eebb49945f4d9bde3746e5de2e969a89c18e8c4ef85f"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "250965108408ff2b4b0a8388eff286a5ebca573507b805dcbca8ea19841b86a2"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "41397f8ebb5a1137f559761cee66b18a85c7289e89ac84a738140d651eecccdd"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "5d4ebf1c83e189cc4b67a579f89fc473aded16d6487683dabafff261a944190f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "76fdd8c37f1d68fbddcb5264d9fe8d353009a93b2b61892f26f2fc0b890770af"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "bc152bd80888c6e54544a034c8d50d9b6e6672d4dd271f6a363153b21f9e5f3d"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "65df17c363eed6e37080d134f548a22aa0b14a9fecf94d5045d5b451bdeb88f4"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "0991a1ba8449cb9b99040bfdaf563d98b64b1d22a6ed2bccc401d2af1fdc731c"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "3c166fe5bb9777c16f216d1858ddfa04fea30076e100ddcbca28e8d026e225fe"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "9ff8f4849fa3f67c9f4793b41f4104d28fd8927d2644a151e85f4da3d2ed761d"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "46b374d7fe5d804f9bf848b7e842ff31f55ab80dd4c0ee3699b38461be96006f"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "2d15ca4433c2f72c9993abeb452efc16ec5a1b70be1fef99e998d6e9aa4dc2bd"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "3774cefdeef0f7e171793e1b79e8f7a52f538aee8349bac0366758c8f9cb5d23"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b2ff77837c1d567a80a0b6e9cbcaad901f4a7b468c42eb7ceeab658640f7250c"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "244b4480c5a64f728d9b4ed3da1da37d1e4a4139ec71654ddfe506ac0b0e340f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "9326ad2077287f079ab68743e5d597af75bf7f166927079fcfa7545fc86c4cd5"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "2f97c60c94970f11901d0cd28279d0e95e5122dbe954a86ec66c83e2e66e4f12"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "c42d8d871c9abfdc7abc6c35eac953fb492222c6d703105d402be2b8cd2fd5ad"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "abac7fa35a6bd77c59fe23d31ffa4f31d09421fdfd0bf137dca9701142e17322"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9d43225a578cd36fbaf754c73a8ba77d8583b1c34bdcb9fdd8199b6a807bdf94"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "d645f76d29084e30a3ae28ba202a5a39d4f56c242c09fafc7bdc6b5f6af8e086"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "84b9a9378a376f194df9a8bf5036d56511a2f05491fc2db8b62e24e7511f7973"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4c37ec6ad2f9c08ad3ed424564ea1e9723ebfc210cd01609e5bfa3791417cf8b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "96894becb83952f56cd2fdba6f69c3eb1a9282c13e63363fa6c83717c2e8d6fc"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "67eab554a2fcaaf2a7be48bf9ee45fddcd9b6634ea76510684dab5636eaaa92b"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "a660173f854ce29f69ec9ae483e5f68d90a8897f1cb592f0b0ac43b9664e745f"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "1b242182d81d92734769025a6e13805764213dfd1f676b1e4745e80c5077691f"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "161387186b13e4ad434cc4a92b9fd315ac30b98881c4d7849ef5b8ee52099943"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "5a75de5c6b0d7399a76172bc9ed9865f54b85c535b6658dcb47fc0dc92bcaaaa"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "c895b10d9f5fda7098a2ca162639a850e9dfaeec43ff24fe09830f7491acc7c4"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "642f9c44190b4dd9ec3a9f292cdd7d84abd7c5cf215512f6c43b4e06444b851a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "68657362af56b1e0a17bc0551992e05527b00a709dfb557fdc926568251299bb"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "a3cdbb046021c386b62ac097524fb15563491285780230c9222af741b1cc827e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "92c8cc2b6a72e68f874e9e57515d06de3570b628422408523e5b584fef025480"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "3454ba8fd73bb6187232dd8bab7fa60cb0cadc4b754e48f82b017e7df84045ca"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "21a2419f108b99b45613df390480778254e9c5cec614a667736d819232ef310e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ff1e17e5c0670835621e2dcc69e6d29908c928253fa43019bca2f69c983776e6"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "a8c3a598ab5619672bd3516198953e6e19efcafe00533a67e5119d612bd62ac9"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "13ca48713a50af57796f5252317d156fcfbde3325a021187410ff85db7e0f182"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "38f94a9f4aaff8aa39f36b963c15c8e740e55cbce6d5d43681a62c073fdb1c80"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "1ea8c70816656d2ad602d616f5733203600ee93f1758ef2e38a7b6cc2edeeb69"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "72411e2d4b2e93a3b503838def9abf47abbc517304074be275295fe5eb422b75"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "5ce2f4ca8c22e9bd1def9f669d7ce1b4f61ed7fcbea57c8678f97239f8f8d94c"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "70ae3a41c953a21d879183e52706031cd25c9ebffbdff478d5d0cddb50ef656a"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "35f482aa3e8acb36cadafa8ef0832c8760b576c94731eaaecdf6b8e60359ddc5"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "732b6071ba95013c414560dd93d99adf24725dd36502405b753232d3c8bea2d7"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "0cb3bdbf727015acdfa5e51baf669aa07f9ac30b200bfe02f24e6441548855cb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "f936ecb530a5a93f72fb92acff6ea6cf384db68d077cd6dec5ecd515e98e0d61"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "736bb573b96ab40f1afaa6e0353f03b509bc164285821fe8a16e99d9ccce8dbf"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "93267c2751b96362180f31b749a63bbe3750642c2ba52a4c299e8e606ea336be"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "e13d84282eadfb56b43feca620ab4a133b36cd7d20161567817b9a1de8a2dc98"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "3406966a9084ec2b7efbcf6a39e3498ca631850e64288a461a80accf841f5ca5"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "1185e63e7327860f0e1f0a1e3c4f96bd83dfd3ac524fd2ac8e93b360bcb18e9c"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "babe37470bafe497c63e48608a9bd6447cd7d311851173b8f658a9d496c76fda"
metafile = true
