hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "d0929cf1802fb8b0963f11a7f6dd9ecf6f8f44089561cb5a78fd7d2420cb3f31"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "c14498f73cae48808b5ec973d1514f9ea8ff2ab0963cc166bf10f3b8dd4ba55e"

[[files]]
file = "config/modmenu.json"
hash = "f41188846cffe4f8847e69de8e456ca6b301c9dc409d0c515edf1666fb78e29d"

[[files]]
file = "config/yosbr/options.txt"
hash = "79bbe17c1414a833965d44be59ab81687384143112bcbf924e10b46d58339f2f"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "8c79b471bad59fcb9d73c4689dd6687be63facefd73a17f11f1bf4acf00c158d"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "30bf7c21557b8e83356ef043c044d76478b531013a290c97443740b2c7a1b73d"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "cef51db1150ae1f30f504c8932c274ba174441d4fa177cda048b407da59d5865"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "f0fa91c42d9a753f8f2773f193864fe248fe1a3527189d1490a0e0094bcd7049"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "3c5317882a50941e2384b9739ec3aa688f297105691c9d8d577936ad29c1d575"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "41397f8ebb5a1137f559761cee66b18a85c7289e89ac84a738140d651eecccdd"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "ade080447491d2a630c65b7343df636833f8283fe5af9db74b51c4e122bf0550"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "ae2b1f0380610c46cb8d2093c083a4a0ee1077b5c345837041403bc75824034c"

[[files]]
file = "mods/animatica.pw.toml"
hash = "65df17c363eed6e37080d134f548a22aa0b14a9fecf94d5045d5b451bdeb88f4"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "f4478d92dac05ad1226a764825a8fdd3012f184ec4c9d631e680fdfa08d96c0c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f1fd6d2d2900f38af4a64f42ce102b1f59f2abc13144487d6604a5d55305830d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2481588ce600e2a77400f48b193a44db3d2dee7a3d571db332ea70c1cd57375a"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "b3838fdf49d6d8b8321889805f59fd0e410d6ff69938c2f68e5e5927cf12a874"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a0426ebbc7ddbe1bd99aea015f713913771e0701ad292359371422fbb73a6f66"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "653f03fb24254449bd709cc75ea11be5c750097535db3c9d95f4b35bca7caf9b"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "3fabf6957b398ab34be705c8d76c61b4dcb93ee1ba308a2cb99c1d16766b2a22"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "83508b385b24abc42539a53f6a4412d4b46aaedcf0fd0f188358392919e80127"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d71e0684cab9614b42d0cb682e23b955ff40fbd9417cbc5b762d389eafd2ddd7"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "80ce92b0b6ca05d30b34023cb86452955bb556e7469cd0436870e47c57596a3a"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "6f3897453ad5c9dd8b827f009c6f828e6597e6afa2ba4fc2e1e9027b6fc8b589"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "36d7ddc72e4400ff5ddcef63d520d3bbbd6d05912ef46735488bfcbe1697dbbe"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "731ca414932a8a08904a9719e4b9b0e6504b05772a158746b38407c2476fd6e1"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "cbc5f3e10f5dd93fc685e1ac412e2497f4867e97562c442185863be24b329dd2"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "2ab6ab95f7ef07902a8695fec0427a03c2f4d64ff69b2126b10b006b451bf848"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ad68291896e892edafe6d0ef625f0e909a01045bc1e25f5e34a0ceb072f42351"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "b26b8bced90483417fe1b26e1a706f4d65b0802c86817255b9bcab35a1db0406"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "58cb23ae5bc7b769a9af318e5f78328a96f8cae493995169898b026de07cf8ca"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b8eb96819f629cd66657ded2826d3ee599a1939043d943343d68ef0cf5683ca7"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "fc34f10a6ed5a5e2eef2d290b651622939feaf00b5e3d67d3085c1f547181dff"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "208a440bc255a39ecd7511f8e988a0654edabb57b6a6ee6edc08dc97a1a1a14c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c84e931bde72de07690a57bbaa93f48163a7f5f5e817235060eb4b373cfceb1a"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "b6bf3418e34dd16bd2c84de01f72f655fc224a59f117388246f592e02e635391"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "38f94a9f4aaff8aa39f36b963c15c8e740e55cbce6d5d43681a62c073fdb1c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "49cf77aeabe9438181dad0980077d4d2ebd18f94e3dd11156e0d04d7c58fbc61"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "181cc501630389686f9e5fee1100c3b7a9d34c5b94c50de456ae869c784eb9a9"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "08304f1522489857f57482ecda6434306f438a6bb9e8be9f9b1a4da04747c548"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "70479556928526accf71a4d5f99465029b28b6b8690c8f0f39dc12f3e5eb0fe3"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "86c8e8a437965b4da10430e4629086ba9d6fcb7608d56de46fc858ecb4b75c8b"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "c8e63d0b1770e8e36bee5ae3172693113b56ead0095ec101ed8562c5cf7066ad"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c44a7b77739c4a9efd346963317cd4c412c412132c10b87095916b8c078599c7"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "06bd37311a1ff75aa8f15e9dc61a637d11c552b5e21b02e3609601ff2c9de647"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "36830ddd92d96a95f5ef05a6973d3786c9423e5692a485fd4297f3125c6c0829"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "99928eb2c12fe8efa872d47b1eaf28ee49374bdf8e249e2d0204f5473812ac5b"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "31349f46d8bb78708e94068aa228761b53e69e9e208de890d247438435e38bab"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "59eb823d9f16ff4bf1c4641a324d2044aba558fa4c531eb7f46f720eecdc461a"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "95011705b9ed9a8bfd704c7a84cf196a0b938e7ba046650aac952d09433351e7"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "04bf1a39c73bfecd2ebde0288852d431299da4b925aecb2d0a8316225f60f169"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "88aacf53016ef02f7108a2f661b7bdeb9a12de0b248d65d5bfccbd80edf0602b"
metafile = true
