hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "d609c376a4158dee487ac0afd3d735d54906840a90718347a72a57c3bdd587d8"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "f40a7e6bc8ca435ff3ad4621f255a2b5d289d1adcbe8fb1e559da5758d6f8096"

[[files]]
file = "config/lithium.properties"
hash = "a3d5b0ce0244e4253ebc7082631b294635adda1c3c29f5d8d20b84027f04f99d"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "8c79b471bad59fcb9d73c4689dd6687be63facefd73a17f11f1bf4acf00c158d"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "30bf7c21557b8e83356ef043c044d76478b531013a290c97443740b2c7a1b73d"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "cef51db1150ae1f30f504c8932c274ba174441d4fa177cda048b407da59d5865"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "f0fa91c42d9a753f8f2773f193864fe248fe1a3527189d1490a0e0094bcd7049"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "3c5317882a50941e2384b9739ec3aa688f297105691c9d8d577936ad29c1d575"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "dacff858c9d3d3d96a4b6b902133d0691e320e21a2f57adc6bb6cb9875763582"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "ade080447491d2a630c65b7343df636833f8283fe5af9db74b51c4e122bf0550"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "2223abc38145c490a6874a551dbd7c69ef618d1c7fc0cb157874ec86c9659a62"

[[files]]
file = "mods/animatica.pw.toml"
hash = "a934e9af85943168909d444e611e2808e99bfddb65ec95469f2f14bf1c46afcd"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "5876d245719b4fe6f21052d7ee8a390f9813384e53ac5cb5bbe8661cfc4b56aa"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "f4478d92dac05ad1226a764825a8fdd3012f184ec4c9d631e680fdfa08d96c0c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f1fd6d2d2900f38af4a64f42ce102b1f59f2abc13144487d6604a5d55305830d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8c4ecec7ea0de2a1c2cd296a570616d6357a0ebdb2b094bbe9273783bc3936ba"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "af7ba9a855567c938724a041b106ebae0b24cf0507faf35c9828033ed3bdd9ee"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a0426ebbc7ddbe1bd99aea015f713913771e0701ad292359371422fbb73a6f66"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "12912cdd8780459ffcfd9b3a086455d471b821606ec6115fb476a40171249d85"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "3fabf6957b398ab34be705c8d76c61b4dcb93ee1ba308a2cb99c1d16766b2a22"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "f2942effcaac370a0f4390d423cfa51ad47cf98ceea84509f82c3dc56ec453cc"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "8044b519d8a469c1a44b5e4d86c971ca0081e6826e49583e8726221752c7e7df"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "80ce92b0b6ca05d30b34023cb86452955bb556e7469cd0436870e47c57596a3a"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "f8390372cf6690d499291f5765589a2c87a3225061748f1a703289c856078b37"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f0ff2f7cc8405638b72d23811abdc70c9aaf45ce15ea0b4e2b15880171be291"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1be9b44db329a60cb8cb8788513d9afd65daffc6ed81d782aa878b377768df5b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "fd77f7cba585f7c462c9ed313886628a9330d6cc0534cac6bdde274c040a60ea"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "cbc5f3e10f5dd93fc685e1ac412e2497f4867e97562c442185863be24b329dd2"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "7ab8dbeecbffa2163b485277dfc72457d8173fea5597bfc6478206bd2290cd32"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ad68291896e892edafe6d0ef625f0e909a01045bc1e25f5e34a0ceb072f42351"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "b26b8bced90483417fe1b26e1a706f4d65b0802c86817255b9bcab35a1db0406"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "58cb23ae5bc7b769a9af318e5f78328a96f8cae493995169898b026de07cf8ca"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c759c039943112f23d7ded0313837391a8f885f381bbd05968b5bbbe560cddb8"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "ff885929d968bef5dc511e3856ada307924387143c71151aed3b09d848e8490a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "9d2e0dfd94eb62908978d01be253a002e26e8989ca60a5b7e18c4b8eca34b18f"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "14323f05c107c6209c7dfcbaba6ab5a1fc94ba13304a62078e93833d183ac31f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "cf34c354995f34c289f75b8a58a75ed118444610d2a799b8e964bdd22e315c9c"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "0ccc4fed97855325f60ad11f87f29ba22f8b6f733d99ea97bf24c0a7af720b21"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "38f94a9f4aaff8aa39f36b963c15c8e740e55cbce6d5d43681a62c073fdb1c80"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "1e8711c6e962e12e47b2829990025d389918ddd7420182f9b292cacba060bd05"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "181cc501630389686f9e5fee1100c3b7a9d34c5b94c50de456ae869c784eb9a9"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "08304f1522489857f57482ecda6434306f438a6bb9e8be9f9b1a4da04747c548"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "86e5b2f4b762776ac703c68c39d3685f1d61a3095ba5f77e5aec7eeb3b4bb33c"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "70479556928526accf71a4d5f99465029b28b6b8690c8f0f39dc12f3e5eb0fe3"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "76872df7e0905a20a6e440e84da00c8afef7a695ace473f5893cd0f47b9df824"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "9a28cc0003fe6f127e755229e0d3c0b3d85e2ef0c3207561bfd97262cd5b5744"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "0c973b947024ffe607360c783242978b664add01aea108a5d99d9c10a8804d54"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c44a7b77739c4a9efd346963317cd4c412c412132c10b87095916b8c078599c7"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "c1cac4b26c49750104520e154b680d53cdb576ffba7c89d14ad3585300aae7bc"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "34e7847c059f800287be138993723f925800433f430d43417b3721c28d9e076a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "617ad1fecd27929adda2e5a3d17e5e76dfa8edfbfd8a06ec7461d2e1ad4a9082"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "b2b0ccd3a983bceb2c8f54d3c9b55c035eca8f3218a0a4d541b023674a204425"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "1247d3b0f92bec14be87b904327b679b7a72fbd36f883275f2d2506f4705ae13"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "e952110e87a6a07a1da63a5fa6483577332240da4d8d81f5b4560cc9dbe353dc"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "290391e0d98878f0a9218891f04e7fd8d6259c8feb032a3c503c75007a3189ef"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "6b2999ac5ab3ca5fe894286f237030af2664c7abdf6a5b3463d578d46ef4a005"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "3a0eb4f4a4888830292e774382ac51d0e7e63109ce2e0731c2b642e2538f84a9"
metafile = true
