hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "e42d605709dbede0b7db4b3392a12c851d572398af021e285e02e3499bca8b7b"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "9779eb5b854deddd60401411214da6d405e2168f1916a030ff0d64d71e93a10a"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "8487c2cd20a677ad23e8a9f0ff31f370e4d5d39e05c16e6835d3cf6c9071036e"

[[files]]
file = "config/modmenu.json"
hash = "cfa9f824ba0800de177f2708d7ab0b05ead854aa5447fca5db1f54be89889509"

[[files]]
file = "config/puzzle.json"
hash = "2a7c463f581910b0daf713ece461106f92894f9cb4af3655dad13152003005cf"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "7668a9ed5d5d6878dd49d552396b7aab57e5345d031a0f776b90f9a477a06195"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "5157cba377614babb525e4346d3f56cd9502e0f20e91ef3f31601a5c90080852"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "18620ae9a07d266e519b66e9c3f256168831ab90c8ce9380569a3ca7f479f90c"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "35cb31f6ae8e293fed8e4eb5dff841c1e913ca2342af5fd47296f31024e14950"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "cfa9f824ba0800de177f2708d7ab0b05ead854aa5447fca5db1f54be89889509"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "2a7c463f581910b0daf713ece461106f92894f9cb4af3655dad13152003005cf"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "cc6f863a8e250641184bfcd3b59169491fe5414a036996401b66bc019ebeedd8"

[[files]]
file = "config/yosbr/options.txt"
hash = "8cf4e887764bc764235990460c9214a000bd434d47839d240656803cd809bee4"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "a1b123fa4c9cc0c4cf25c6ef33694cf6c94f9dd88388188f34feab9b6d367e2a"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "b40504ead60f1250508367553fee38e3bbe1dad16a6b590c9be7feb9672d5df1"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "6ecdff2bb7086af0673bf95992c425d3b4c82e27d6070c86ed4906611af0a6b3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2f7e95dedbd6679133a383341ce12d5873b59d974e6e0e9c452b8c57a788aa35"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "43ad173e5e3b92a29c52ba9f7af4c9ba63bf2c57076ea83349967f37499dccef"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "fe0fb406a9ba81b2e501d41db4606ed512687045e5c515481edc12b00119940e"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "880d63ceab82d4f5167fcb38796a1d767efa4bd749b4caa70b8ad33f6d80fe6b"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "620b2a59fe1a9080b0d8410585037b23461d9601c6e53c287d3570933ec38a88"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "2ba7ad3bc444713c63def40c42c2a0d27df69f45cc0cfa543a6814ec9afac2d3"
metafile = true

[[files]]
file = "mods/cloth-api.pw.toml"
hash = "033f1b85664c3726d95f32f66bb36c38c93bc087006b3abd0aae1d4a3e2ba657"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "848802e4af9c2e37ba369feb7568f694a4ce22c7b7414ecef6010b57a32fe3d1"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "7aa8ced63d137481245c7ea9a15b5486193dc2ff944a15ca92479f093da0dc85"
metafile = true

[[files]]
file = "mods/completeconfig.pw.toml"
hash = "c38e8a0abc8f71ec82439c0a8a59677b4e13c673cca28793f00f9ea7cc40a10e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "e6b7cfbe39ff45eb44ca26dbafb9e66a8505bd56dcad6350b7a8271e91274bb7"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c8ea01498d57c9c2c3690b01d752dd5cc1e2acc3f910f2e560d8cd1618f1cd57"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.pw.toml"
hash = "f78fdd7d632b5e90ba87232795ce5862bfb6c57df924e1b8e3510b4ad8bcf37f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "93d9cc77eb3643dbb0d2bffe6ca9c88033ab909061d35d2aaa0270340d8d10b7"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.pw.toml"
hash = "4077565bcdd87a21d72ff4a89553a13c25f9ffea39f5e13f1e43bca15440223f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "71952509ce4496bf508aba29a68aba01ceacd31e8c9e8b9d9ded1e1da70a93ff"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "8e2685957447d16441aad91b258d93e818d6f607cd2ca12e485960f4ec566089"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "93065188da30c0ac9e3859ea0f296fdc055d130b74ec0540cb9ffc8493cea997"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f1e92c9d139c489a86d38ef8765e5f81fb9dfebbf840f0e5951c44e84a01c929"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "44038b3e5f904112c81af6cc291ff4f46af2dabc2648c2d20f43dcd3abbef0f2"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "3c3d7e7f9e0ae6a978564276c618a802d0c54c4ca098a7a897252a662ff4723a"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "2e25280e924e9a871142a5a95f35016e04f0eba2c86f4b84815d5db009ed19f3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "41233eadb61c59cd9fb298f21709c79f45c78dc3e03b08c40d0c094c86a821d5"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "0eccead743b7a2a4fdd6ba5c58fc109b4a08f360b0d7f66df135501728ae102e"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "691b50fe8d77ffdd2655ad44156fa4cc64f012ac56808fda9bdf4713876ee3f0"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "c141133aa236e002f9b32baf6e9c8c2c3f4618fcc3defbd3bc3d2aa24f7b96b7"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "7848466b7f337faf90f5edb14aeed716c398f8abfe091cef7c4894102e2727d4"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "c3385cf1d17ee86c70b6cd41e42510e7d5df1a81ed5af6ce34d4cb731d20fe17"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "a65c430042d328c630757454bfc46226e4a5083a4e331df3979ebe1c6fbd62b0"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "c4a890bcac6c13bc25eb1a559dc990ad10cbb2f229ebfb9aa7c645234d9c5755"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "e75515de6f60227e731affe8077018bd68d8556ebd62032a5e5bd5217b28d44f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7f22345473b4c9ab8382171e2ae3c87e6e88e02ed3843fb44637fcb12171d0f5"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "c91d9d252064cd1679362225321edf30113333ae3ae1e5fb2acaf07c7a58709e"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "10f9b8c4662bf605f853b970a0ff14b7e3fba721604f18b62e6714c02fb9bb22"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "46902c5093ff6acac3fc4c40583f8e38af28f4576c39f7132ad4d01e6e35ff28"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6b1734388b472b28a3207eba2c470bd3eb6a08e5446a742737dcf401da694ee9"
metafile = true

[[files]]
file = "mods/more-chat-history.pw.toml"
hash = "7e064b9aa45508aee054ab21617ee081895ff10ba3547c4dcc061c1c02242716"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "c91a0e5e41ca1131346bec3429a5b54dd46ca826a228620b52333de9184a864a"
metafile = true

[[files]]
file = "mods/not-enough-crashes.pw.toml"
hash = "d7495dfea9e8f9fe45d1e449f7b858f135c9f1651db0c5b6d46139c83046d623"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "86c3442582a49b7748ec304095c4e7367e7dace7db01507abc9db97127891f07"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "f2c200a93671fb9108c7bdc53696d530c43b0988e6f7c47de046c7afcb158497"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "29b8887bfa6d02773b797f8144ecf1522e398d7f3480cec9c2b948eee6989521"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "612eeff30958ca942d29aa15ddab76e03b2d3de10fa3768dae0e377fbf201f8e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "4bfa59263c3c2e8b8435eecdd8a944d1345b4b249191ccbadc953f3417b93608"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "873384feb93e60940f653af72b20eeb2a9ded4da80fab455710bfeed35a48203"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "5520c1dc76ba02ac7ab0648ca5facc2e5e65e6f98b5bc1c9b95d6f8be8280238"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "003dee7fef878abc298c3c6589b7b21e8922def090c9cf8259ae8c6aacc0946f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "b28b9f05014ee4d421223b69cc5921a4f9792629258203d523091e5ad6ac19b6"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "34447de73eefb20d6be996663a10828c080a24363a24d831b4791a82983f2d50"
