hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "e42d605709dbede0b7db4b3392a12c851d572398af021e285e02e3499bca8b7b"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "646c1487eb142576fa76b87fef987a895bb9a9d18a1649180969469796013609"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "3fd0bca90569cc0ca367d72e7c84c988de9a03bedc8757c58af94f532884e6ff"

[[files]]
file = "config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/puzzle.json"
hash = "2a7c463f581910b0daf713ece461106f92894f9cb4af3655dad13152003005cf"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "7668a9ed5d5d6878dd49d552396b7aab57e5345d031a0f776b90f9a477a06195"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "5157cba377614babb525e4346d3f56cd9502e0f20e91ef3f31601a5c90080852"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "18620ae9a07d266e519b66e9c3f256168831ab90c8ce9380569a3ca7f479f90c"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "35cb31f6ae8e293fed8e4eb5dff841c1e913ca2342af5fd47296f31024e14950"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "2a7c463f581910b0daf713ece461106f92894f9cb4af3655dad13152003005cf"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "cc6f863a8e250641184bfcd3b59169491fe5414a036996401b66bc019ebeedd8"

[[files]]
file = "config/yosbr/options.txt"
hash = "8cf4e887764bc764235990460c9214a000bd434d47839d240656803cd809bee4"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "1adfed1eb9468a7aee481cac91008bdb8e0af1048c54900a5a408dc40c446500"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "b40504ead60f1250508367553fee38e3bbe1dad16a6b590c9be7feb9672d5df1"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "3460db95383cf24e5171f466bfc196c7f953eb7624ac10381de2c65356e265c0"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "43ad173e5e3b92a29c52ba9f7af4c9ba63bf2c57076ea83349967f37499dccef"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "fe0fb406a9ba81b2e501d41db4606ed512687045e5c515481edc12b00119940e"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "9190e39e3a8413bfe35d0b36befe8be2f49b63c6d20973df934f598e192f329a"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "620b2a59fe1a9080b0d8410585037b23461d9601c6e53c287d3570933ec38a88"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "9900ca7501a0cedb1cb1292fb51250c1820f4cc1dc6b7d572824a18738e118de"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "7aa8ced63d137481245c7ea9a15b5486193dc2ff944a15ca92479f093da0dc85"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "15fdaff0cb9342b772aa104d98eb4b116b3df442f689fa607ef6656c66468ffc"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c8ea01498d57c9c2c3690b01d752dd5cc1e2acc3f910f2e560d8cd1618f1cd57"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.pw.toml"
hash = "f78fdd7d632b5e90ba87232795ce5862bfb6c57df924e1b8e3510b4ad8bcf37f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "93d9cc77eb3643dbb0d2bffe6ca9c88033ab909061d35d2aaa0270340d8d10b7"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.pw.toml"
hash = "9e8a66d43611d16b5809628f192db4c81ec55c2a6dead5d4cd85923f0cbb2d6c"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0db89b28d9d11cd967580baed30d7ba8930b3c3a9b9e7426a92664a1f48ef24c"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "8e2685957447d16441aad91b258d93e818d6f607cd2ca12e485960f4ec566089"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "93065188da30c0ac9e3859ea0f296fdc055d130b74ec0540cb9ffc8493cea997"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "fb056d772175c202b054fd2fa32ff8c3f98e618249f1078b8f2c6b24997a0f13"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "23c82cc89e5e080d3ea3a56052708782ee511091c387ef09ff5870d0dcd98827"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "cd7812412623eb47d8f612f3b276b4d86db3794496cc2a053fc709b19072afc3"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "54566a4d869db8c6139ed8900bbb2a3977f5328dcfcf9e43f1b63d008c93a43a"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "41233eadb61c59cd9fb298f21709c79f45c78dc3e03b08c40d0c094c86a821d5"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "90934a8f07aad60a6a696e2b63db60f4aa0a5439b89fea95fcd0a100d526da6b"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "ff2edbb00b2de30cbd9e3c8b65ef9c6b532a73445d94b02eb11dad91819361cd"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "c141133aa236e002f9b32baf6e9c8c2c3f4618fcc3defbd3bc3d2aa24f7b96b7"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "7848466b7f337faf90f5edb14aeed716c398f8abfe091cef7c4894102e2727d4"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "c3385cf1d17ee86c70b6cd41e42510e7d5df1a81ed5af6ce34d4cb731d20fe17"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "6efed395750fd72a1396750da222739ed5708b63bfb5fbad59b05ebec779e22c"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "c4a890bcac6c13bc25eb1a559dc990ad10cbb2f229ebfb9aa7c645234d9c5755"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "e75515de6f60227e731affe8077018bd68d8556ebd62032a5e5bd5217b28d44f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "cbedab2ca0ec5c65cbcb2e1c51c8cc638109b60d3774c3232534ccadda9b9335"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "c91d9d252064cd1679362225321edf30113333ae3ae1e5fb2acaf07c7a58709e"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "70f89a1865f7b6ba615807cc8212da1e52a37273cb02048881ebbf87a8d51355"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6b1734388b472b28a3207eba2c470bd3eb6a08e5446a742737dcf401da694ee9"
metafile = true

[[files]]
file = "mods/more-chat-history.pw.toml"
hash = "c142ea1d12ea1cdd44f16218eb9e4b295f5e08cd7e3b6b79dc2c9cefd9a7f609"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "c91a0e5e41ca1131346bec3429a5b54dd46ca826a228620b52333de9184a864a"
metafile = true

[[files]]
file = "mods/not-enough-crashes.pw.toml"
hash = "da2f881af5407adbed6f097b5169950d9fb6c704465b5e82bf3f260c4e140f0f"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "86c3442582a49b7748ec304095c4e7367e7dace7db01507abc9db97127891f07"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "e5a6e7fb7994702cc2e4787aad7b042d91df44148140ed5bad245448536091e0"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "29b8887bfa6d02773b797f8144ecf1522e398d7f3480cec9c2b948eee6989521"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "612eeff30958ca942d29aa15ddab76e03b2d3de10fa3768dae0e377fbf201f8e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "4bfa59263c3c2e8b8435eecdd8a944d1345b4b249191ccbadc953f3417b93608"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "873384feb93e60940f653af72b20eeb2a9ded4da80fab455710bfeed35a48203"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "5520c1dc76ba02ac7ab0648ca5facc2e5e65e6f98b5bc1c9b95d6f8be8280238"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "003dee7fef878abc298c3c6589b7b21e8922def090c9cf8259ae8c6aacc0946f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "33dd47f911a5e7f0b1414375cb9b4e43378cf9497cb1af5424fc852ca4885840"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "34447de73eefb20d6be996663a10828c080a24363a24d831b4791a82983f2d50"
