hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "e42d605709dbede0b7db4b3392a12c851d572398af021e285e02e3499bca8b7b"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "22a4fd52c52bb80131daf59b50ea3591cb345f70d0a04a3e9af78fea4b490c22"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "5c42d668bd091a5d5af743cbff80ea631ae4c09a22766be5f248b965896a547b"

[[files]]
file = "config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "7668a9ed5d5d6878dd49d552396b7aab57e5345d031a0f776b90f9a477a06195"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "8f5c4bac35757d624f296419976aff70a4a5b95c4430aff06048013ea7dd25c4"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "35cb31f6ae8e293fed8e4eb5dff841c1e913ca2342af5fd47296f31024e14950"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "cc6f863a8e250641184bfcd3b59169491fe5414a036996401b66bc019ebeedd8"

[[files]]
file = "config/yosbr/options.txt"
hash = "69305f9d9e0c54cc866cd9d3a381f14532e3be6b9b00a80707c19517e6a0874b"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "a1b123fa4c9cc0c4cf25c6ef33694cf6c94f9dd88388188f34feab9b6d367e2a"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "728c85c89f01a18eef1b03d6de2285e2bbf4c50e90b1ce8ae355e73207551584"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "4312f252c472b5befd7fd21fa014c2a52f773f1bb0607cff57f534ae1b2d1465"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "fe0fb406a9ba81b2e501d41db4606ed512687045e5c515481edc12b00119940e"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "880d63ceab82d4f5167fcb38796a1d767efa4bd749b4caa70b8ad33f6d80fe6b"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "4922c6a60082afb777fbe456695c6ee321b7e051baaacf3a94020a2308613e51"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "80ececd3824fee3732b1b3907ffed32c0f8c8aa8537ac0f7d40b9537a073645a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "8f07b2408013a7217caacec87c977635fdf94eb21a10bf281f2bba67ff7c4dc1"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "4e2a3f28c677a309e6fa5c2039d8bcdc7cbf6ea186cf479680c5c8e480412b83"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4b0fa19ea767d239fad702863b87571bc7ab22981168d9715efe9bb14fe3e5d7"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "119967d6984daefc2dda4e34e9f2fd3edb4ee48abb3edf8ce8edd460e6e680be"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.pw.toml"
hash = "2550d281034e7f21eb4e03c46b552bdd2571213b2a8b172451b527015bd48270"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "42aa424ca423493f8fc20a7792761e64056dd25a5684cea7f6af25c3280f315c"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.pw.toml"
hash = "4077565bcdd87a21d72ff4a89553a13c25f9ffea39f5e13f1e43bca15440223f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "71952509ce4496bf508aba29a68aba01ceacd31e8c9e8b9d9ded1e1da70a93ff"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "26fc1b6eed34ae6c622682efd66c82c99e22027750c31853709255ed3d672902"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "20dd8853a5b18df0b2cf9f7efc241d69d20ee786fc17090b6153c3a453077a7c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e075e0b77fafbf166171df8412138fe15cb6d6f6dbbe96129349dce357d70d9c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d95379da217fbae889dc9b9e66a55d484ee63a28da2ffc9d79bd020cc4e2cc8d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "4559f01f8da539982476e058019d8e9b7906f3d9b84f06652b9687cee648515f"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "2e25280e924e9a871142a5a95f35016e04f0eba2c86f4b84815d5db009ed19f3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "41233eadb61c59cd9fb298f21709c79f45c78dc3e03b08c40d0c094c86a821d5"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "0eccead743b7a2a4fdd6ba5c58fc109b4a08f360b0d7f66df135501728ae102e"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "b823831af9d57c2e6429bfd0cb51026658c507aa267dfdcaccccbe2d9c3f4a3a"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "a225d816e319a04116b6e7e792040b3bc9b23760eaf8b233c646c576cc86cb12"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "7848466b7f337faf90f5edb14aeed716c398f8abfe091cef7c4894102e2727d4"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "c2f8fbbfa209673ad71c2157b07254a096d423100c3c1e25aa1ba57822368abd"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "531d8c87df493544f0fe91f525bf7e65a77c065e66614b976a362dff7abecbc7"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "6c187a1fc257c5f3c369e2751a00798feb8f508a14aa59ec88eb9aad32b57a49"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b59cda50b7fa539aa9783bb8d87b55ca4e05d0269c9f2e2df69fa2134d0e644f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c5fef2f9b5aec665ad9c09712c0c9d88157ba2cf48ac19fd0eef30b00c97dd5b"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "198084fae4ff7ee526c4d1b82b82f36585445d2c07b5f1c82e4121724c81400f"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "1fc89f8a9bcd5f2595072474dc27c617a64cd7505e7f622db0e2f87b2cbca5c5"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "845c6bfd1410cfac22e042a2839c0a3250c571d6075c384cc5814388012dbf89"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "f8c57b83b826e6447a6a97f88f0fab03bb76caebc8272b74f3b890c6b5821d5d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "86c821389c1ecfcf2b83975287bf3a549b00b096989324bcc15fe8a0cb06e80e"
metafile = true

[[files]]
file = "mods/more-chat-history.pw.toml"
hash = "7e064b9aa45508aee054ab21617ee081895ff10ba3547c4dcc061c1c02242716"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "c91a0e5e41ca1131346bec3429a5b54dd46ca826a228620b52333de9184a864a"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "1ca96ec71e46c97fef13cce6c8ad0f0cedce7b1ed3039e7fd879b28e3f9408b9"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "ec94c69f7b433748cd8bd9878672a89ebe1fe1559ebcbf0cd43738f0a39a131d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "198733c09fae4a7c0ea76f0a4c1c9f42cd572a759df023748a839acab8dc75cb"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "9a031c4018bdcf4e8d70f5009a3069914b8febf96712222fdd31f8d0ae2451b4"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d4df17e2b322206eb00376847bc989cb9e302414b60768a164450bdf27e015b4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "470c19232a750a398997935c13778a662468fa69fb78c9f269189f41b132d094"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "73259e05c16e2461736d7d7ddc8775ca97c9efd70e6a912dc2280e2bf2c67396"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "69214e78788c8db0b1b2e9fa48deff5fdb090dd590ced6898ac5b4286aa370b2"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "003dee7fef878abc298c3c6589b7b21e8922def090c9cf8259ae8c6aacc0946f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "49e25ec166b7824d8f1d7feccbd08a8e904c90b089f6485b05df9173a489bd54"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "30cae3d640c7a768890e806908c703db5cd61f3933b5c91985c67f91f82f43a4"
