hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "e42d605709dbede0b7db4b3392a12c851d572398af021e285e02e3499bca8b7b"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "fdb01934a2e6666033b1977ce13906e2a540ba5a103b2b96562512a35c362e90"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "c56bfb6b158bc92d21225888520e86c88a2792eae3541173c80f32d30876d3b5"

[[files]]
file = "config/modmenu.json"
hash = "b140184afb51de3614a0ca47132396e931cd7c74e8c1af05f3b6020b34350157"

[[files]]
file = "config/puzzle.json"
hash = "7a362321cf036dfe648f46c08f9e6bcfb77f1c036f96cf33dde682b9bbd508f7"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "7668a9ed5d5d6878dd49d552396b7aab57e5345d031a0f776b90f9a477a06195"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "88b3f30015ae7da848f736cffee62758ff245a947c85fc83adf99895d66fad6c"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "e42d605709dbede0b7db4b3392a12c851d572398af021e285e02e3499bca8b7b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "93980f4922f93c81db7e7e934524f6fe70c7aa1fe187cea0de642601468cd850"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "1786a6b8a60d295944e28a4585ba7f9a2f4d2c58bbe5e1932675e27b6f11f3e8"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "b140184afb51de3614a0ca47132396e931cd7c74e8c1af05f3b6020b34350157"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "7a362321cf036dfe648f46c08f9e6bcfb77f1c036f96cf33dde682b9bbd508f7"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "e1a60c1be5f7d715cd4604bb4fd0af7514ad2345af75ea3d280834c34518182f"

[[files]]
file = "config/yosbr/options.txt"
hash = "75524549ac5777b8a92d9be522ff06e50f8f64b889f178c1b61702f2be80c3c0"

[[files]]
file = "mods/advancementinfo.toml"
hash = "2a7fd6600075e0b6e5ee90e289f031f5822aa0c859e3b3fa1ed8c8a99ad51e80"
metafile = true

[[files]]
file = "mods/animatica.toml"
hash = "4434f950f298b99f19434496a998c0a46951e9a025e07c5c7000b6fdf52b5f20"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "3e3074cb6a900a2714d125469354d0e2a9e89e899723c3e7fe5dffa035f72917"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "612eb5b02d9f18e9c5327bb96373c692c72c9ebbae3541eea03feda76dcd764a"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
hash = "85f3ba11c05d688f772f04f226eb010bc4d667b7da987182e15aca89a578f3c9"
metafile = true

[[files]]
file = "mods/borderless-mining.toml"
hash = "29617ba69cf27f8892a63fa113386a0d86a43600a0b6c5f382e1c4212a9faafc"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "b5e992d432416b2948f6d441232da5e6169ea3093f895f01715ad5d9be32837e"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "30aa8e08b8206182bc3a1d4da8e73a8633b289f2c001f9edd2e92f61855d66fd"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
hash = "0f325317ced484dc5fdd2e9b3d455223eed66c565c426ffd326468e472a951b1"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "3894f56dbf821aebef6d4149ef30474d19c09ec9d27b8ee6f971ddfaa9057aaf"
metafile = true

[[files]]
file = "mods/colormatic.toml"
hash = "f37004ea1a77170a692e5f072bec6419c00b42b8fbd4803d189e01946f4eaa67"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
hash = "ac4ef5d0e3ee33ed06232cf813b710f2f39e38718ff064fd7f7853080c53a526"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "a2503cd9f6455bcfd5b5d5d7d5f1350bc005e799918dca1e7d3203c5b67f9ae5"
metafile = true

[[files]]
file = "mods/cull-less-leaves.toml"
hash = "0d7be112f0d024dec435732b4af7e99c9edce54b59af752b8696999774f69d39"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.toml"
hash = "2c60cef285ee93b3188da4592b0067cb9d5dcd5ca8d1a9e70c0f2e25455ab7e1"
metafile = true

[[files]]
file = "mods/debugify.toml"
hash = "765c0266e2e6ec1e6a7e5790729f7af0f1fdef205d284d68c3a737ad84bd088a"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.toml"
hash = "c77ae8f60d73419f5e363d87b470a35c5b20958054e899846df9db9fb40ec7c5"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "13013b1ab312945c0d4c1b008f0deb9193c010a161e161cc59642c185889abc6"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.toml"
hash = "5f96cbfa5842b2fa1977bed45bff4b2230a1608f34394ca75945fa65d8e555da"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.toml"
hash = "68ea151b3a2b580cc1c8378ce58970e4375fe09b41c42db39b802f16ceda0891"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "c2ee93e74ad106f20b997ffb054f46189f941da0c37c73a1a97d5dd85ff530a5"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "99fb566fe03abc87d64b6b541cbe225fa856d15c1ef7a6d4de85e6b6fb0c14e8"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "d2fbaf45c8aed07525a3d592a02242db2c2a9a76cf6c995585835282e87d24f5"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "f1127b63021453ff95eab3d0812173bbfaa1513de0d52315162d5d4b771a079a"
metafile = true

[[files]]
file = "mods/farsight-fabric.toml"
hash = "342460b8b5e2e7656e3e8001da9cd2ee92bec4e288eb7701a319aac391f8295c"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.toml"
hash = "25785a86466d4b51296dc71da2110bcd8972b6cdc47069f0ed3c4e8f72512d08"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "fab378c0172e0251334a08f0c6013b087847d3c6aa3eadc40de2e77b33fbec5e"
metafile = true

[[files]]
file = "mods/irisshaders.toml"
hash = "f8b55cf573545a31ba3fcd99b8005513aa00c34e73a53493ed55c3e5be547db0"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "9ab8949bcb4280b1a4b97d40ded17b4786a6c4db1271c121a7fc52ea6f838e0e"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "4269b7e2a817dfd03ce2e43aca5b15b3dc96210a44b0c056d4712722063c5ce0"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "f53ac074b0938319dc0ff805692993a9941beea49c3e86d7e0a42c3db1e64243"
metafile = true

[[files]]
file = "mods/language-reload.toml"
hash = "8ce38e4c7ff2ced58e55e405fb69d926588767809cc43b78bb4338ae27e62e3b"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "d469405ae3ba7e17c6603477e0c444914e48932ffca884f630b9ee459ffe0039"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "954032fd7697535870f901eb03abc1439e228de7bc598c7bde3073ad7f5bfeb5"
metafile = true

[[files]]
file = "mods/main-menu-credits.toml"
hash = "229746e66cad817f3f4c757f5b25d57561192237fb6ebd35cc120768b176ced9"
metafile = true

[[files]]
file = "mods/midnightlib.toml"
hash = "8cf8faa6b8d2e856a998cfd590f3ff330d088a0827e04af2643ef8e9577582fd"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "439297a26554e1723ca14ff0142e18a12180700578c270e23501e4b1083dc2f4"
metafile = true

[[files]]
file = "mods/more-chat-history.toml"
hash = "6e491af660315658150add9c80d9ba6936563e6f55c45ee0aad5bdb0737e6fa8"
metafile = true

[[files]]
file = "mods/no-fade.toml"
hash = "35f59eea8f56885041a17d971f15cc79e084746c90f195139d78dcfa2b275510"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "3b8c2cec272a08fce467e51a52e9125d070dcdc1fc4ffc0bf7cf9b0b23e2a319"
metafile = true

[[files]]
file = "mods/puzzle.toml"
hash = "26b1a2e1fdfc61594bfdf13e88c5edf9e42a1c68023098233f4cdfc215536867"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
hash = "b1ec378adef0a4d8fa1b27de650895dcab7d05e99515f02254ebd58dffa645d4"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "0bb8efa177ff2c5b54bb0bcbadf5e5fd2ae57c0cb71e533e7d8b896f12d9af4b"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "ce30f904d04f28ccc48d443fbf07034c46a7491dce470c81fe343733073baff7"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "629cba9c7cd4bfbb4f5be04e7d2ebfb71ef1c44466c7a1614b9c31b78b97f7a1"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "ed3ce42c6cccaa9989d3b7a8769bd4c0a9c643ccb2fdb7d41ef9604163e4a8e6"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
hash = "57279a8ae2d7c6e5053da3909d95254118db533d9a38c1a0763bf602d80c933d"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "527e21c9bc55b0d1db9016a2fec4ff2dee2a93c53edb8c1363d2d2ee7730afd0"
metafile = true

[[files]]
file = "mods/zoomify.toml"
hash = "213370c5103daf420baccbd5bfb9c022273fbf8d4e1b54625e0a3575217dd2ee"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "64b2a1bb9394edeb6056deee2fd665b8eb57a6a14bf4f8ee9d0310ee8d37d8dc"
