hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "f6e7fd1a6ada739da42d8cb8395232b28595fb7b74fc3c990d1947a3ef3a79cc"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/en_us.json"
hash = "4fafb86ca4e0aa03abcb6c769106810dcd1a6f1d23c13c215e5556e41a9cfea1"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_es.json"
hash = "d275f6a87d202dd095487a0cd5c7203f14fce61dd5ee35a929a76f017163dabe"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/es_ve.json"
hash = "d275f6a87d202dd095487a0cd5c7203f14fce61dd5ee35a929a76f017163dabe"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/et_ee.json"
hash = "cc3ec39716498b9fa147f71baa082ae9d0c0dbb7a0805c3d47054474d2ad7fa9"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/fr_fr.json"
hash = "6010c841df9af4ab572aa17e94d07b3661c136b63e8e0174e69bee9c52f36676"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/he_il.json"
hash = "c746a1103ed59842e1520dab19aba57c5785457e991c356dc21621123545fbf0"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/it_it.json"
hash = "5c7a5eb2218640ea7e6f3ab8c5629ae773b8dd59acbba998c92900054eb760f1"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ms_my.json"
hash = "400e2975812eb3be3b0739679c29f89540c96376a711b954eb803cd946e6bfd8"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/pl_pl.json"
hash = "f878e7fbf52e211892dbc8bd100793e8627b7facc87c1dc954f4fd757b11af72"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ro_ro.json"
hash = "898eb21ab8a2b1721c28d616b98d2f329c48d9a734820f18b3cbfc274d0955eb"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/ru_ru.json"
hash = "9a1530734bfc7dd66250679ecc1a38d2dc99df6962031c98a6ed3c73567c6a0f"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/vi_vn.json"
hash = "96d9d1950ba059bcf5e71b16cd3513f8a64595f8bca747f383398ab682f0ce03"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_cn.json"
hash = "902c431486ecdd638cada3673a50778c65f2fda4aa0fbf6d31da35dc798461fa"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zh_tw.json"
hash = "15ca1dbab8723faf3a690cff0bdb0cbb63d20d138975083825c22c7a42643394"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/zlm_arab.json"
hash = "400e2975812eb3be3b0739679c29f89540c96376a711b954eb803cd946e6bfd8"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "d0c25e870d350248b778e81fea8e58d73557944c83dd0d6cedde9c3459bb61dd"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "db5f5a50bf6747cce36a063803eea351199a3ccd43f47c20c0f07de84173562c"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "375d545e83e1aabc7700c5f0bea4f7bcf1a19e5e35f9a2155bde2e1c9b0ebc61"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "b7b9cdc1e99bdfd86052e373dc3e0ae87c73760816454b801b09d0cfd7b79604"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/yosbr/options.txt"
hash = "edd18730edde6d07394ca0631b03a8ea4dbe65294f4f13e42152a71ddb3645de"

[[files]]
file = "mods/animatica.pw.toml"
hash = "23b3d1ad268ba3a1eaaea01b74ff3dd5ae9123c0cb0ba29ec85c98b0e6eadfba"
metafile = true

[[files]]
file = "mods/bettergrass.pw.toml"
hash = "6a4438861eb234be921396599e8ea655b404ac20c20e03a8a40432ab414c706b"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "24b0177dacb547321d83487699e13bf6f6fa004c0d8199dbcc0867b2c21097ee"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "d7384472a7c1c58b70d0b27e3681f79082e87150402c8bab4eda8e77a8209a7a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "91ec280bb0b40533a4f43601f074eb0d3ff52a606cd0a3b700802b228670f4ef"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "59060a934906e4cbd6a19b91ab63e40761de5699166366bf2e0e6d2062aec539"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "e5ada12d6a7002a1307bca463a24f1e5ffc50f5850ff56c48b8339500b78bde2"
metafile = true

[[files]]
file = "mods/crash_assistant.pw.toml"
hash = "b054f3f180baf16065a098b53b32abc60a8fee6af72706652244c29dc7c59c09"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "867f8e4be9bc139a517dbcf55aefc2938c5e461640bd08024ec4716fce068025"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "40cd28ee0012a938d0bd8dedf94f44bc7890d69c6a824597197e30f26f8b229e"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "cc89fb82436fb6a1b0711f3d6ca3e5ea598a726a18b063d6c2202b2e2c44dbaf"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "1ab2a6ac0ad703dc27e4fd7e6355320f8cb24367b42b7872ac658e1992b8a508"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "3839761576edb967af437a8b5dc8fb6868996a6accc6a1ac666e15348e6b5372"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "38b2c338d7b5153212b9fb38ad7021b03dba9265d88028d1599ad86140c7c97c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9d62264174b60141a12bda075ba08569ee0d8a96074f052231feea874fdd9ffe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "08a7da23c3533ff859cfbe0660630b2bce51e26b03a95ba4654a6184bf28a428"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2831d2be7f52107b8cb23145f8812485c7ee12107a4eabf47d39d5b5d778cf04"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "1bbacf4844881b1367ff761b3ce1c5cc7ef61eb6514d3a7f41cc994e43cc57da"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "cbeb9402a1014268ead085555ddc841281ec08101d9df27fb9aa7d1d91cae79c"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "9ad131939560892cd4e453e26a56c826d1d4922b24dab991357f89d0f0e26d2f"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "59763290be9efedece6960fa2d4afb42cd10776a9ed73ceec786391154462947"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "396fbea89f28317c634a5914e6089ca629cbc8eb5feb0b109d0dce437dd1c568"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f871de4d57dbdf4e5ad512ec21f1e9baa3a6ff1596399ac57a758a1c26b2418e"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "21843e75802603fc737c7599bbd6550e85d77e882e9b0aa5df279ae1270392d6"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "a4d49814dd3f38c133ca49ed66de88234c69578a3f586c0434d1b6502d6d31de"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "c575ad32315d38916df9a7148afb4d05430a40869074c1e87dc61873f5a77747"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "186ff3d734f9d6718daa6e8242884d69be59f4d1d0b0eb95a1140934e497289b"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "20853b64aec9d938a92a6b3b45158b67159f16bd2c08b659aea6e29df23d3be1"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9dba1fb1be6e3876cc3fb52831957a0aab142cf5ab8c688d55aee8921855de01"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "c3d0746be98e5f5eaf1731a84e84724289f45f6b49836c5106e8d4669d3f84ec"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6006fa2a1c9e1ecb4faf424b2a4c0086ad18077f6cc22c0d25fe59f1d3839900"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "e01e4e296bff245a222574cb664cdf07d934356c0de81c6a9ac32a1c9bd25cb2"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f5273d4065ede04639ac6796cac0420d6cafed743a930a8f2c70f6f9c37e7bf3"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "cbe531f3cb8cd726ba811e3f8c4803ee7c3485be0ed6fce91908aa80a55c907e"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "78edf00f2118746d8653541d5a9dbac5c064bc69d8e43a99edc0a20e97d7fb74"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "983290f26e4e746fcccfcd6701b0afe547e2c01952d3560625c1e996c751c10c"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "b039f55985a83e7ed5f5004a21ee3d0faa5f566ee5c8b595718febfc3e4a75e5"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "2c3600d467605594f87dc652fcf0e4eeef916f7a3abad911eec46330727a5355"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "146ad722eecbf7bc624c86e4f03b10fb05a139f9910cf67cb3262101bf9787e4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1b05c3d841542fdce7815a7fcef89e73f01a754943f292cb1e81e047cb3db362"
metafile = true

[[files]]
file = "mods/sspb.pw.toml"
hash = "9a7b77d36b9aba3015e540205750b0bc64223afee043a7146708e26d1e501af9"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "9047468f7e046a63cbd1a18d78cbfc246a4f853777c719c02415bf0209aada2f"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "74426c00d217e12b0ca740e13a901273a704cced4a7e3f51d9fbab9cae3f056e"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "2d0fa08197a563fe705757891381c8e4fee1a229e184cffd58e390de3d293040"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "3d4be0a921b3c4076cbf0f03d740b7854158388c71e7a68fb292d6ac2e61cc07"

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "5e603fd0023d079585770e3d98a201badd4244be17d8c8aeb4ed4075e54871c0"
metafile = true
