name = "Fabulously Optimized"
author = "robotkoer"
version = "11.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03afa5a18bfbfc3533f8512c14ec843da5e1e06d35add343d09722894e4b4591"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
