name = "Fabulously Optimized"
author = "robotkoer"
version = "11.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa31260009e201d8e89d561ac16eb8246ca01dd9cd1e59d5cb0cec2baf99682b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
