name = "Fabulously Optimized"
author = "robotkoer"
version = "11.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b868b6199f68c5930c02d28ad399e3e069d7a1c71a46d5ea9a75bc344a1c3b7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
