name = "Fabulously Optimized"
author = "robotkoer"
version = "11.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d017fcb89ae6ba5be0620ac3b876e3828246c92a4589b3e9d97f4319f7b21464"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
