hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "8e683a923285b2661e1492cf5ee17d4415478e70f8b06bf7c01a65afa705f471"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "5c0926fe0e7686e798d0486781a0c6510394e4a5a96f2d7f2952761cef64f9c5"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "30d2bdee0e007766a81150064ab25f391b129ac5d06b92c1f44d3709630bb622"

[[files]]
file = "config/modmenu.json"
hash = "b2d6f97d6f09d3c02504264a778ab1958378c91e5d743afed9ab71846073bf60"

[[files]]
file = "config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/yosbr/config/NoChatReports.json"
hash = "ce052ce133fcc17bf3151ec2634431ba11342d60da3bf0383117f4a1116d6e0f"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "7668a9ed5d5d6878dd49d552396b7aab57e5345d031a0f776b90f9a477a06195"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "5157cba377614babb525e4346d3f56cd9502e0f20e91ef3f31601a5c90080852"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "35cb31f6ae8e293fed8e4eb5dff841c1e913ca2342af5fd47296f31024e14950"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "b9196e07b7b1a7239992b737b50ea35a337c87d1828a20d5f23300b18050f37c"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/options.txt"
hash = "15ce78106c5e206e4bddf1da45e84967dafb9c04bf87a4b4ae09433229ec8990"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "e6ee4e0303ca4666aa8f53f1920d1abf23c00a2c197edac0ad246812cb329493"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "6e37a53e0cc21c40bc27956d667189c278cefe61dab2a798fd4ba39bbf741687"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "e8de5feaf8b78bd44e38d9502937ea49cfc6679ebc82e2d45eb36d2340115c93"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "fe0fb406a9ba81b2e501d41db4606ed512687045e5c515481edc12b00119940e"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "e0f6cbba2f655e4d7906d95d5c9e00837a72fa6a0c52ddadcd35de33c160f017"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "968dabb91375ca143c3c8eb7c6de76add0cff8d33bf30894650f4d4b2d0c1ce1"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "a662fdb75dc2676b5912ba07b17a481fb1f9c64b9bd93820936997a77aa1636e"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "7aa8ced63d137481245c7ea9a15b5486193dc2ff944a15ca92479f093da0dc85"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "15fdaff0cb9342b772aa104d98eb4b116b3df442f689fa607ef6656c66468ffc"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "a4f1b4126dc3fdd6815012df939a60df9d4ae2721a2bc869d216b946ffe7b757"
metafile = true

[[files]]
file = "mods/custom-entity-models-cem.pw.toml"
hash = "f78fdd7d632b5e90ba87232795ce5862bfb6c57df924e1b8e3510b4ad8bcf37f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "6fb5b9849b6ba0cb9ff0057318b87b476aebd86d9505763233e1b1d150e73bf8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0db89b28d9d11cd967580baed30d7ba8930b3c3a9b9e7426a92664a1f48ef24c"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "07f493206b01ebeb4064854f473e947b7d175229f5e2a1b46e74964ff240e2f0"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "bc927da092ee23dc5668d9607fb91362bde587b280564c00d45e44cac244205f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c7deffd338b695e2e6e6f034cf6704f9b2743aca64f2c350945ad5a57dd4b03b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "91520be992ba24e8b7a4e5d5b9dc3f20ad2807d1c789f20eb0583c5fdfaa0401"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "54566a4d869db8c6139ed8900bbb2a3977f5328dcfcf9e43f1b63d008c93a43a"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "35ede7e1fc3181ecac4f75f57a7c64eef817d8336395d76df8c1228b685895c4"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "90934a8f07aad60a6a696e2b63db60f4aa0a5439b89fea95fcd0a100d526da6b"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "0abb6edf141e1050711172ae1f1848239b5d2eb472735bd091d8152c17eb45cb"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "7befee16152b92859affdb23cf8015c71c6f3cf39f8e544a8af67462595241c7"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "0cb1859becba06e139f96d2f99d6a6840d4bf20818753ec6b28f495f1716a4b3"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "0d66d77d7354d3b8d4b89983c3a576895e9d3e74250a8797897ccf6e0291e6e2"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "6efed395750fd72a1396750da222739ed5708b63bfb5fbad59b05ebec779e22c"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "398b1a30ec518b3e2e88ea6bb5154499380d9a495772e2b037276edc81a43a29"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "e75515de6f60227e731affe8077018bd68d8556ebd62032a5e5bd5217b28d44f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ab6559c392627be06948d290c10b1af211e0c153b8a333b885e2dc910f18d47f"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "198084fae4ff7ee526c4d1b82b82f36585445d2c07b5f1c82e4121724c81400f"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "98b6983ca2bd063b9f4f980bcf14ade7c25a5cefe36ffacb3ac8bc557147dd4e"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "011cdac05926935d1b86941f21b192514bf58d7178c83e1d40fa5a616f18ac8d"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "e711296fa29d5659dcc38c4201e7a208e7e1dc8e75be919428dcbb6954765219"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e441993c15186052f35a1981df9011175d285a35e1d54b856c7c8ae2e0377b7e"
metafile = true

[[files]]
file = "mods/more-chat-history.pw.toml"
hash = "6ba02ed36bd9c31c7585b3788ea70b8fbfd4027e8a4e05481e35bfb7470eaa46"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "5431bb6956b7c1ae5ea4adac6e4f0ced6537081a28ed5b5e7a9ce0994ba1074a"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5c29672e914ed228c0e79891bb13291aa56c2bdbf7e7b6c47c2c3376ee17fcd6"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "c91a0e5e41ca1131346bec3429a5b54dd46ca826a228620b52333de9184a864a"
metafile = true

[[files]]
file = "mods/not-enough-crashes.pw.toml"
hash = "da2f881af5407adbed6f097b5169950d9fb6c704465b5e82bf3f260c4e140f0f"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "c4aebe0362765c366bc23fd89150f8249877f6bad869aa3328cdbfd0c5cacbdf"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "4d5f84481c08f43d7dd35bae05f815a5b1fa39dc7220a62d6226b229f7062569"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "242d59152c19a148d3d5b6a0bf46ffb0280e822f90e78b417e9669518bcc1ab5"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "3819426b160a445edb28b35d2286b4a9af8944744191a6ea609903ee685d14bf"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "4bfa59263c3c2e8b8435eecdd8a944d1345b4b249191ccbadc953f3417b93608"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7b110f0f87bb5f21381cc9c2338be6689219a36ef13cb34c22e745df4e6afbff"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "5520c1dc76ba02ac7ab0648ca5facc2e5e65e6f98b5bc1c9b95d6f8be8280238"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "003dee7fef878abc298c3c6589b7b21e8922def090c9cf8259ae8c6aacc0946f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "ad716fac8b1178432a76af304dd6d4e2806bb4f66e63a1f729097aa9ba523811"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "65de574d1ad10a12341f51697391532c5fcbd63f9d9b122cd81be78b00745387"
