hash-format = "sha256"

[[files]]
file = "config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/debugify.json"
hash = "4cf30e65cc64f5df736a38740e30730aba2794643e73446a786cc15535a72f1c"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "23b2f3e81050079808116efd97b0405d0313d77775acdfc259de661b19278c24"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "3d619651e1cc95002c2787f3fb9be598a8c8512810f06dfd398d39015295dd7d"

[[files]]
file = "config/yosbr/options.txt"
hash = "f1476ae055d1722d41a58adc860fb90a290a003ef5f9f6161adb7fbad7083c90"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "eefa86fa9a8df6eda5d39d3bbbf53138a44df71a01a24262c27584badea97d79"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "b04558e3aa16f01cb56278cbb0ae1a2a7c65b5288ee056865a07b2764a850f65"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "e4b230e3eccc42c8b650eebb49945f4d9bde3746e5de2e969a89c18e8c4ef85f"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "97a19031a10809c206b89c366bf1e802e4f2d39e9df798c3c627bf0d63448447"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "1db967817059276c90dd3fd34e2573abe7883f2a169285a2c03632f6c9d31fe8"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "5d4ebf1c83e189cc4b67a579f89fc473aded16d6487683dabafff261a944190f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "b369693a2ca0239cca70b1ed98049ad03a01de470cd58225807678d9b135924d"

[[files]]
file = "resourcepacks/Chat Reporting Helper.zip"
hash = "f326bd5655efdadb322c0de3381dc323c47e2067965a79748382ed6fe37c6fb1"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "22a48b7ebf469f9c9678bb41697a0c9fa0a2a475783d627c61978be0a77a8c58"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "181b6bda59e65cadc29604b2053955e9fd8299939ccc4604309e4ac97f2659ac"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "b023edfcaca9f400d9afed65ec077cc98a35943fedb4392542f87fbf8613e839"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "bdbbc306c1affe5017f7ff15ffdeb053d019f7c8882253f2579b21e9a7ee06ee"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "64b46649facff7bb1b20ed8bb93f7ece4f8e397e5a18f670aba5b741fa16973f"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "b6fdebc38bf3e988d5386bd781394545a06456e0f8fd238f2a380023de2165a7"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "fbc0d426c5035a94ef922a9acac048ae1fab1fe459b45e841e5b288e66b99975"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "497f177b703010fd23c90eebc701872008fb73812643bbb5d8c53f4fd233d06f"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "7c5caeb7e0652bdaa73614281535d015fb45ef303edb607f4dc4baa4c493bbac"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "32c0f9fb79de5b3d833942d1bdb9d98f0f0528859e3845872dacffb37e7c1bcb"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "3b3d6b2c0a9256dab61c5e084b3a89d1f946cac9c2da8601dbc184d82053584c"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "f99b11f9c689295a830e45b4f688c2e134cf45e13ce1657256ba6bdd09332b29"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "abd0949e818e68738937917ffd23d5a63258867e577912852fe172939ea11239"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "7fbf0ed096ed4d7f137c475ba5670bc3abe0f96c5c010778ce31aa881f7a6444"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "d2377d3e2e77423d3f2484de6115fe6cb236d723f50ed1a400f15f77dca39d03"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5b3c42c6cbf6d41ec3149435efa35e9e459a73aff589d07cd16809df3dcd9bba"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "cef05d8db8ea72a37f1c8d7418ccb446278dd17d2b9d2f8bd087e505adfc90ec"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "bf7266cfbc1e6f837183a0ba30d435922c5bf349c6be04f2f260a599dc7beb38"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "3bf54134dbf492b27b52b95cc994bfe0e3ec089a884ea1fdad0ee4cc33cf28e3"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "248e44131bf9ab35abdd27646066ede72f2128d51fd43150c9676d6eb5eeb64b"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4378ed8c8083eb922d2e4dd552b3525986cbb0d509a2d6ed0e4872866da3b0a8"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "61ef8d453af948c20fac3a9bf99e11e12f77325070fa68ad68b83089a96ad569"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "2d642d7261e0361b701387987dafc63cd05f63beaab4492be0d0a5b60c649c8b"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2ce5718fa5c58015b0985e436fa6ca9a6ee439ba05202f6e0bf95d7c2133288a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e03cf5c46362d6c43aa2eec2b395c17a96d8e4efcd83973e58a9187a11c10bf8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a5d569097a69daa3de0bc6dfa85a0a77cb449c7e342e1824c52790f81b9d425d"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "358fa6b2c04a9141a808ab267f0cef9c738078b57b47edde2e3b96f24336f84c"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "8b6676f4c7330e532dc04d4209a5b9d10d6e32d9db6b0b0f6db1b9d2df26d28f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "1a9b19f754179d965cbafd4f3742c74dae03d3252f88a3c9b0fdbd500972bc23"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bf619ec7dae9e2dcd694424a7c702c7fa1f549c3589f9ea0f4ef4d40d9041c2a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "295fc4a373635cba66d10cc200075c22b785fae9d4b6be513725abbeb93c2e62"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "e55608355a86866c5b1f7e34ab1cd8aff69ff43a927a28d18783b840103103b8"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "24e905f67dfa82bbc818cd97e9cdf8e3652ec7db77b761c9c2174aa89ece8419"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "7332dfe2de4bf26667ccdeeb6d53eb0a2f36395b3fa1601e3a9ed7afc55b277c"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "db37d57adc3779c2db85517569783149b88fabe8507d4918bc68fc43fd8cc49d"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "6df739768992a26671f5eaa24916b12a7e3fff45b21292e3b15a0433ad4fd389"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "1ec5381fa05c03da84135acacfe3319c3962d9c6063841f485f2ab1182621bdb"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "fbd01936002e972f20909ba45e74dd1bba065510417fb9afd42987053b3e35fa"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "ee73ca959f10d7cc4b9e4e6536b75f909065b73d3b0355c4a8830eddebfd725a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a01fe815be48ef7f992855c106ca4a5de351c6890dcb85940af96de4d29968db"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6517f6543d0be925c443d5e0074dc7f374e4b85c05797a48f2ced025b71edf63"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7c42bb0fe982cf5004bfcb62690e9b433890ebd76ea94611fd91c68b00f386fe"
metafile = true

[[files]]
file = "mods/yet-another-config-lib.pw.toml"
hash = "e5e4d9d46d0950637f5a60d123d0818e6bd1f4e0fdd1217d4b93466e8a231fd5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "9dffabf569e9e1b272c7311579a4a758a88e551bf2b2c1d75319489656053c55"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "ccc7d4bef305b6d910eee258672518a7a1551a9ea99ed0fd1fc8a1c0581c3eff"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "4af41c9832766bf24c5fd04be78aaf2d8399eb281c32d11effd62c56cdf67541"
metafile = true
