hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "9531554b7adb24581355741dada8540848abbe512bbd1f7f0162266f2d8029b0"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "2b5aa36e45ebf87274d0305dae716972d5e619a4ebe041c076cbf2a5cecea51e"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "5d4ebf1c83e189cc4b67a579f89fc473aded16d6487683dabafff261a944190f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "d7c81fae39b82fbc4be62a0fef141c7da80e96b6f97a0d80b44c245cb9a8bff6"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "c88ac7aec7bc08f867f8a9f6c7bf9396871d03d12b0f4d7100e8ef1fddfac68e"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "dcb9f9dd8184ba8ee7c81e785f677434c7cda2acb925fd3d542e2a361ee78e32"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "4cf30e65cc64f5df736a38740e30730aba2794643e73446a786cc15535a72f1c"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "eefa86fa9a8df6eda5d39d3bbbf53138a44df71a01a24262c27584badea97d79"

[[files]]
file = "config/yosbr/config/fabric_loader_dependencies.json"
hash = "e5210a18a1f67104b6eda85a9ea68f475b75a71bab9cff7cf7dbcc10f627369a"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "b04558e3aa16f01cb56278cbb0ae1a2a7c65b5288ee056865a07b2764a850f65"

[[files]]
file = "config/yosbr/config/holdthatchunk.json"
hash = "acc20d0a92edcf0497ebb62c7c673a8d9c99d872890bb53027722390f453e9dc"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "803ff4e47c28c30ff514ec5b3f35509f2e94f51ff649e882386b761235dbd06a"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightcontrols.json"
hash = "b792f2977c2889e388d0a0e83e316ed4f27050729d86c8623e8472accb8a2a46"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "f7f7122784c7a6bcdb034e663fd756e16ffe69a668cb1b334e2be622f8c7bd55"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "e4b230e3eccc42c8b650eebb49945f4d9bde3746e5de2e969a89c18e8c4ef85f"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "97a19031a10809c206b89c366bf1e802e4f2d39e9df798c3c627bf0d63448447"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "41397f8ebb5a1137f559761cee66b18a85c7289e89ac84a738140d651eecccdd"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/config/tr7zwDonorSettings.json"
hash = "ef73ff0fcd6f7e7f3727f493ab61fdc8a65d710475426a55f72eb772ef0ed309"

[[files]]
file = "config/yosbr/options.txt"
hash = "f1476ae055d1722d41a58adc860fb90a290a003ef5f9f6161adb7fbad7083c90"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "22a48b7ebf469f9c9678bb41697a0c9fa0a2a475783d627c61978be0a77a8c58"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "65df17c363eed6e37080d134f548a22aa0b14a9fecf94d5045d5b451bdeb88f4"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "b023edfcaca9f400d9afed65ec077cc98a35943fedb4392542f87fbf8613e839"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "bdbbc306c1affe5017f7ff15ffdeb053d019f7c8882253f2579b21e9a7ee06ee"
metafile = true

[[files]]
file = "mods/borderlessmining.pw.toml"
hash = "64b46649facff7bb1b20ed8bb93f7ece4f8e397e5a18f670aba5b741fa16973f"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "e1eaf47ef2723dd16ce48593636f72a6a80d7644e0132b7654a12c809c7aa065"
metafile = true

[[files]]
file = "mods/citresewn.pw.toml"
hash = "fbc0d426c5035a94ef922a9acac048ae1fab1fe459b45e841e5b288e66b99975"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "be13db40f1b984f04d9fa1009cfcc93bdb81cfc810fa97325f4bf627c648c10c"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "7c5caeb7e0652bdaa73614281535d015fb45ef303edb607f4dc4baa4c493bbac"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "32c0f9fb79de5b3d833942d1bdb9d98f0f0528859e3845872dacffb37e7c1bcb"
metafile = true

[[files]]
file = "mods/dynamicfps.pw.toml"
hash = "3b3d6b2c0a9256dab61c5e084b3a89d1f946cac9c2da8601dbc184d82053584c"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "ca199c56727323ca124d5c4c4d6be14748d6602ca94e17daca9d7046f80170e4"
metafile = true

[[files]]
file = "mods/enhancedblockentities.pw.toml"
hash = "69f7e005fe3c4da686afcca23b9d0fe3e0f184a08836ebfa77ddaaeac78529e6"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "773d733db06655972e55b8c5e0ca202fcfd490b60cd03e06c466e929de674747"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "ce763aead086b7babd9d3e83fdee1d30f206023734cde29c348a913bf9aa59e7"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "abd0949e818e68738937917ffd23d5a63258867e577912852fe172939ea11239"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c58344de4609bd7cc276ec54fd0a1c48395761562d8cc4a52060236c5bb3fa56"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "11f0ea2ecf7afcbaa0a1c6874feeb4a1d77e1c620441ed71875e18af67712299"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "1925f94710355356ace084bd36bbf7f33adea9a32b6a523f52ba1390e82cee3e"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "cabc105f32fa00d7988e1c8ebe1d9d2ee95ada93ffcfef59c33251ed2c602714"
metafile = true

[[files]]
file = "mods/farsight-fabric.pw.toml"
hash = "183a624df188b2c096fe8d0a5d38c6e2748f6721363fdc99f954620c01c99c8f"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4378ed8c8083eb922d2e4dd552b3525986cbb0d509a2d6ed0e4872866da3b0a8"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "61ef8d453af948c20fac3a9bf99e11e12f77325070fa68ad68b83089a96ad569"
metafile = true

[[files]]
file = "mods/fsb-interop.pw.toml"
hash = "8e9e370140f3550886239f5c8ca588cd20cbc98c53d902f331197d355a74a621"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "568fb074f132f4217940a451fe3e78ac736dcfa7bc070a0cbeb299c0497175cc"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "c53d59573dfc61d4b92f47e28667b2177800db586c8a0a2c606b8ca9269176cd"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "77e23d0c36439849ad78e00928277341ed2251a946918dfe34cc97d838fb8eae"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "a8c3a598ab5619672bd3516198953e6e19efcafe00533a67e5119d612bd62ac9"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "d870c01d20b60505d5542e8b838cfe64575959a3d34af67135692adbe072091a"
metafile = true

[[files]]
file = "mods/languagereload.pw.toml"
hash = "d86a4dc4d5df4693bbe8ac14e2782d7707b279a81c916662a54fc1616a273715"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "1a9b19f754179d965cbafd4f3742c74dae03d3252f88a3c9b0fdbd500972bc23"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "295fc4a373635cba66d10cc200075c22b785fae9d4b6be513725abbeb93c2e62"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "e55608355a86866c5b1f7e34ab1cd8aff69ff43a927a28d18783b840103103b8"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "24e905f67dfa82bbc818cd97e9cdf8e3652ec7db77b761c9c2174aa89ece8419"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "04271276ca53acaf0ff05d7ef54bbb06930faad439bb4bc55f06ebdb3dd6f82e"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "2bf8a3291d840b5f6ca368d86e005740cf6156f2c51364c29eb5cb3d157a45a2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "db37d57adc3779c2db85517569783149b88fabe8507d4918bc68fc43fd8cc49d"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "da5bc04ce1665f78ceae93794202796d2041d6274ffdcfa227bf9e3024ca5ea3"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "80c5074d944c5d709abadb1f38f51c48668342d2e9e8465c3c13de9a23642b98"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "75a1ddf873abbb7428c45146ee8d8532396f54481b86d9eb845a396f68851257"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "fbd01936002e972f20909ba45e74dd1bba065510417fb9afd42987053b3e35fa"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "ee73ca959f10d7cc4b9e4e6536b75f909065b73d3b0355c4a8830eddebfd725a"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "5e6cca8ce375951d7363e08c1abf20ccba36b43d7594ee3089adfcced415e4c1"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a01fe815be48ef7f992855c106ca4a5de351c6890dcb85940af96de4d29968db"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "6517f6543d0be925c443d5e0074dc7f374e4b85c05797a48f2ced025b71edf63"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "7c42bb0fe982cf5004bfcb62690e9b433890ebd76ea94611fd91c68b00f386fe"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "c99fe607e293f5a68671099ccc017f75756f60e7ab64e2fd74e1f1d704c8b5a7"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "ccc7d4bef305b6d910eee258672518a7a1551a9ea99ed0fd1fc8a1c0581c3eff"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "691131d231501bb59a5a67aef6298e505bff528032bc1a63ae2bd8b7ad4ef721"
metafile = true

[[files]]
file = "resourcepacks/Fast_Better_Grass.pw.toml"
hash = "4af41c9832766bf24c5fd04be78aaf2d8399eb281c32d11effd62c56cdf67541"
metafile = true

[[files]]
file = "resourcepacks/Mod Menu Helper.zip"
hash = "c57d36422f4aa8087e4daf835ad222718194ae83a6105abc8eb9bbf50ad751bc"
